### ISSUE TITLE
Orthologues_using_outgroups

### ISSUE THREAD

**Issue by jckhearn** [davidemms/OrthoFinder#107]
Hi David,
I am interested in both orthogroups and pairwise orthologs using orthofinder. I have 16 species and get an ortholog results directory for 7 outgroups (0-6). As I understand it orthofinder is choosing these outgroups and outputs results for all, how does it do this?

The numbers of predicted species pairs are very consistent across orthologues. Are you able to suggest what may lead to the minor differences? 

My plan is to keep those pairs that are consistent across orthologs for further analysis.
Best wishes,
Jack

**Comment by jckhearn** [comment]
Final sentence should be:

"My plan is to keep those pairs that are consistent across outgroups for further analysis."

**Comment by davidemms** [comment]
Hi Jack

OrthoFinder identifies shared gene duplications in the unrooted gene trees and uses the branches where gene duplications are and are not observed to work out where the the root of the species tree is (i.e. what the outgroup is). The method is called STRIDE and is described here: http://www.biorxiv.org/content/early/2017/05/19/140020 (we hope to have it published very soon now).

In most cases this is very effective and identifying the outgroup. Sometimes, however, there are not sufficient gene duplications (with strong evidence as to where they occurred) in order to pinpoint exactly what the outgroup is. Instead the method is able to exclude the root from some parts of the species tree, but not all parts. In this case OrthoFinder creates a directory for each of the remaining, possible outgroups and works out what the orthologues would be in each case. 

The minor differences in orthologue predictions are due to the fact that if you have a gene tree, what are orthologues and paralogues can depend on where the root of the tree is. There is a nice visual explanation of this in Figure 2 of the STRIDE paper linked above.

You will find the rooted species tree that has been used in each results directory. If you know (using other information) which is the correct outgroup then you can use just the orthologues in that directory. Otherwise if you do not know which is the correct outgroup then the method you suggest will give you the set of orthologues that you can be confident in, regardless of which of the 7 outgroups is actual the correct one. If there are only minor differences then this sounds like a good approach and it should give you all of the well-supported/non-contentious orthologues.

All the best
David

**Comment by jckhearn** [comment]
Great answer thanks.
Jack
