### ISSUE TITLE
How does OrthoFinder infer a rooted species tree? 

### ISSUE THREAD

**Issue by SWittouck** [davidemms/OrthoFinder#113]
Hi David,

First of all, thank you for developing OrthoFinder and making it publicly available. It's a great piece of software and I use it a lot in my research. 

I have a relatively straightforward question but I couldn't find the answer in the article or manual. What method does OrthoFinder use to infer a rooted species tree from the gene trees? 

Best regards,
Stijn

**Comment by davidemms** [comment]
Hi Stijn

We're working on the second OrthoFinder paper which should be completed in the next few months which will describe all the new functionality since the first paper, i.e. gene trees, species tree and orthologues. 

Currently the (unrooted) species tree is inferred using the [DendroBLAST](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0058537) approach (it uses BLAST hits to infer distances and FastME to infer the tree from the matrix of distances). This is then rooted using [STRIDE](http://www.biorxiv.org/content/early/2017/05/19/140020) (which will be coming out in MBE soon, although you can see the preprint at the link). We found STRIDE worked in most cases to get the correct root for the species tree but you can also provide your own species tree to use for orthologue inference using the `"-s"` option if you already know what it should be.

All the best
David

**Comment by SWittouck** [comment]
Hi David, 

Thank you for the answer. Looking forward to the new paper! 

Stijn
