### ISSUE TITLE
No alignment files

### ISSUE THREAD

**Issue by swuyts** [davidemms/OrthoFinder#120]
Hi David,

My apologies for posting another issue, so soon after my previous one.

Yesterday I've invoked Orthofinder v2.0.0 using the following command:

`orthofinder -f $p_in -M msa -S diamond -t 8 -oa`

Everything went smooth except for the creation of alignment files. The Alignments folder is completely empty. I also think this part of the log file was a little bit strange to me:

```
Inferring multiple sequence alignments
--------------------------------------
2017-11-08 17:12:21 : Done 1000 of 8129
2017-11-08 17:20:08 : Done 8000 of 8129
2017-11-08 17:16:47 : Done 2000 of 8129
2017-11-08 17:19:19 : Done 5000 of 8129
2017-11-08 17:19:37 : Done 6000 of 8129
2017-11-08 17:19:53 : Done 7000 of 8129
2017-11-08 17:18:10 : Done 3000 of 8129
2017-11-08 17:18:50 : Done 4000 of 8129
2017-11-08 16:50:46 : Done 0 of 8129
```
The last line seems a little bit out of place?

Thanks,
Sander

**Comment by davidemms** [comment]
Hi Sander

No worries, the missing alignment files has been fixed in the working branch: https://github.com/davidemms/OrthoFinder/commit/73e54a4657fdb8f959c3a31bada313aa52cb996d. You can get this from the "Clone or download" link on the front page.

The order of tasks completing in the output file is nothing to worry about, it's just because of the parallel processing (in fact, the time stamp is earlier but it has appeared on the terminal later).

All the best
David
