### ISSUE TITLE
STRIDE with 3 species

### ISSUE THREAD

**Issue by jconover11** [davidemms/OrthoFinder#126]
I tried to run Orthofinder-2.1.2 on 3 species; all of the gene trees were made, but I received the following error: 

ERROR: Not enough species to infer species tree
ERROR: An error occurred, please review previous error messages for more information.

As such, the program didn't run STRIDE on the gene trees nor produce the Duplications.csv file I was hoping for. Is there a manual override around this issue?

**Comment by faguil** [comment]
Hi, 

I have the same problem, even if I tried both STRIDE and DLCpar. But when I ran Orthofinder with at least four species, everything goes smoothly. So, I think for an unknown reason the orthologues part of the pipeline doesn't work when you have three species.

Can we override this section manually?

**Comment by davidemms** [comment]
Hi 

The problem is that most tree inference programs will not infer a tree for fewer than 4 species. This means that the later steps in OrthoFinder that use the species tree wouldn't be possible. 

I'll try adding some code so that OrthoFinder produces the species tree itself in this situation, which should resolve the issue. In general though you should get better results with more species as it provides more information for constructing the orthogroups.

All the best
David

**Comment by davidemms** [comment]
Hi 

You can now do a complete run with just three species and get a STRIDE analysis of the duplications. The one proviso is that you won't get branch lengths for your species tree as FastME will not infer a tree with only 3 taxa. The tree will be rooted using STRIDE though.

All the best
David
