### ISSUE TITLE
Paralleling Orthofinder: how to use more than -t for blast?

### ISSUE THREAD

**Issue by rafaeltiveron** [davidemms/OrthoFinder#134]
When I run orthofinder using the argument -t, I've got a maximum of 5 parallel tasks comparing two FAA files. So high number of threads, just stopped in 5 tasks.

How can I increase parallel tasks, reaching until 8 parallel tasks? Is there a way to combine orthofinder with xargs or GNU parallel?

Thanks

**Comment by davidemms** [comment]
Hi

The parallelisation for the BLAST search is across the pairs of species that need to be compared. With 2 species there are only 4 pairwise comparisons (including self-self comparisons) so that's the maximum number of tasks that can be run in parallel. OrthoFinder is generally designed for larger-scale analyses and here the parallelisation reduces the time more substantially. 

Another way to get it to run faster is to used DIAMOND instead of BLAST ("-S diamond").

All the best
David
