### ISSUE TITLE
restarting OF after a kill

### ISSUE THREAD

**Issue by l-yampolsky** [davidemms/OrthoFinder#140]
Question.
OF job exceeded walltime limit and was aborted. Some of each.vs.each blasts finished, some did not.  I understand that I can restart it by combining options -f and -b. Just to make sure I am not doing anything stupid: 1) if there is a BlastX_Y.txt file saved in WorkingDirectory, it means that the search of sp. X vs sp Y has been completed (i.e. not killed mid-way having saved only partial results) and 2) OF will restart correctly regardless of which searches have finished and which have not, as long as all .fasta files are there.

Are both correct?
Thanks so much in advance!

**Comment by davidemms** [comment]
Hi

Unfortunately neither are. 1) The existence of the file means that BLAST started the search but doesn't imply that it finished 2) There's not any functionality in OF to restart from a run that has been killed part way through (the -f + -b option is for adding extra species to an already completed analysis).

There are two options I can suggest. I think the first one is by far the best as it is easiest (it won't require manual work) and will be the quickest computationally too:
- Run the analysis from the start using DIAMOND instead of BLAST. This is what I always do now. The DIAMOND searches are about 60x faster than BLAST and the results are very similar. You can see some OF benchmarks comparing OF with BLAST and DIAMOND here: http://orthology.benchmarkservice.org/cgi-bin/gateway.pl 
- **If** you wanted to complete your previous run you would need to work out which BLAST searches still haven't completed, run them manually and then use the -b options to run from the now completed BLAST searches. (If you used n threads then you know that at most n BlastX_Y.txt files have been started but not completed. You can identify these from the time stamps. You'd need to do these searches and the ones that hadn't started when the job was killed. The command OF uses for the searches is `blastp -outfmt 6 -evalue 0.001 -query ExampleDataset/Results_Mar08/WorkingDirectory/Species1.fa -db ExampleDataset/Results_Mar08/WorkingDirectory/BlastDBSpecies0 -out ExampleDataset/Results_Mar08/WorkingDirectory/Blast1_0.txt`)

All the best
David

**Comment by l-yampolsky** [comment]
Dear David,

Thanks for the detailed answer.
How do I tell OF to use DIAMOND instead of blast?

**Comment by davidemms** [comment]
- First download DIAMOND (https://github.com/bbuchfink/diamond/releases) and put the executable in your system path.
- Then add the option "-S diamond" to your command line. Note, you can see all options by calling orthofinder with the option "-h" for help.

All the best
David
