### ISSUE TITLE
Calculating gene distances step error for a big dataset

### ISSUE THREAD

**Issue by edsonmachado** [davidemms/OrthoFinder#149]
Hi David,

First of all, thank you for your contribution developing Orthofinder.

I'm trying to run Orthofinder for the Quest for Orthologs reference proteomes (https://www.ebi.ac.uk/reference_proteomes), but the Orthofinder returns error in the "calculating gene distances" step. See bellow:

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /archive/users/edson/GENOME_DISTANCE/OrthoFinder/Results_Mar06/Orthogroups.csv
   /archive/users/edson/GENOME_DISTANCE/OrthoFinder/Results_Mar06/Orthogroups.txt (OrthoMCL format)
   /archive/users/edson/GENOME_DISTANCE/OrthoFinder/Results_Mar06/Orthogroups_UnassignedGenes.csv
2018-03-24 11:37:11 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1549, in <module>
  File "orthofinder/orthofinder.py", line 1398, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 948, in OrthologuesWorkflow
  File "orthofinder/scripts/orthologues.py", line 392, in RunAnalysis
  File "orthofinder/scripts/orthologues.py", line 269, in GetOGMatrices_FullParallel
  File "multiprocessing/__init__.py", line 259, in Array
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+483c819-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "multiprocessing/sharedctypes.py", line 39, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+483c819-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "multiprocessing/heap.py", line 36, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.3.dev0+483c819-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 545, in load_module
IOError: [Errno 2] No such file or directory: '/tmp/_MEI0PGxyU/mmap.so'
Failed to execute script orthofinder

For datasets with few species, I've got success.

The complete logs were attached.

Can you help me?

Best regards,

Edson Machado

[orthofinder_Quest_for_orthologs.log](https://github.com/davidemms/OrthoFinder/files/1863760/orthofinder_Quest_for_orthologs.log)
[ortho.log](https://github.com/davidemms/OrthoFinder/files/1863761/ortho.log)

**Comment by davidemms** [comment]
Hi Edson

This looks like an error in PyInstaller, which is used to create the binary package from the python files. I will have to contact the developers of that tool to see if they can identify the problem. Thanks for reporting it. 

In the meantime, the best way for you to continue your analysis would be to download the source code version of OrthoFinder and use that if you are able to. Because the problem you encountered was with PyInstaller, it is unlikely that the issue would occur with the source code version of OrthoFinder instead. You will require python 2.7 with numpy and scipy installed, it is a pretty standard configuration so if your machine doesn't already have it then it shouldn't be hard to set up. 

You can restart the analysis from your already successfully calculated orthogroups using:
`python orthofinder.py -fg /archive/users/edson/GENOME_DISTANCE/OrthoFinder/Results_Mar06`

Just to note, I've already run OrthoFinder on the Quest for Orthologs benchmarks and the results are available on the public website here: http://orthology.benchmarkservice.org/cgi-bin/gateway.pl

All the best
David

**Comment by davidemms** [comment]
Hi Edson

I've created a package that will produce debug output as it attempts to run, would you be able to run if on your dataset and send me the output it produces:

`./orthofinder -fg /archive/users/edson/GENOME_DISTANCE/OrthoFinder/Results_Mar06`

[OrthoFinder-2.2.1_debug.tar.gz](https://github.com/davidemms/OrthoFinder/files/1875990/OrthoFinder-2.2.1_debug.tar.gz)

After the failed run, there should also be a directory with a name something like /tmp/_MEI0PGxyU/, would you be able to send me a list of the contents of that directory too please.

That should help identify what's going on. I think the run should get to the problem in a short amount of time since it will start from the orthogroups you've already calculated and so it shouldn't take to long to get the debug output.

Thanks
David

**Comment by edsonmachado** [comment]
Hi David,

Thank you so much for address this issue so fast. This package solved the problem! 

Unfortunately, I started the process and saw the result after some days, then the directory "/tmp/_MEIETJIzR" it is no longer available. But I'm sending attached the complete execution log and I think it has enough information for your analysis. Anyway, if you want or need, I can run the Orthofinder again and send a list the content of /tmp/ directory during the process.

About the results available on the Quest for Orthologs website, I do know if I'm wrong, but that results wouldn't allow me to create a local database and add other species. That was the reason to process this dataset on my server.

Thank you for your support.

All the best,

Edson
[ortho.log](https://github.com/davidemms/OrthoFinder/files/1890564/ortho.log)

**Comment by davidemms** [comment]
Hi Edson

If this is running ok then I think I'll class this as 'working', unless you find that the problem happens again if that sounds ok. From the log file I can see that the original problem isn't there. As a brief summary of what seems to have occurred:
- I use PyInstaller to create a single executable of orthofinder. When I run PyInstaller it reads the python files for OrthoFinder, finds all the libraries that are used by the code and packages them all up into one file.
- When you run this executable, it puts these libraries in a unique directory with a name like, '/tmp/_MEI0PGxyU/'.
- For some reason, when you got the crash, it was because it couldn't find the file 'mmap.so' in this directory so I thought there was a possibility that it wasn't getting included.
- However, the debug log you sent shows me that this file is in the package, does get put into the temp directory and it successfully loaded when you need it. Why the mmap.so file wasn't found the first time is still a mystery, but hopefully it won't reoccur.

As for the Quest for Orthologs data, you're completely correct, you'll need all the intermediate files in order to add species yourself so running it on your server is the best way of doing this.

All the best
David

**Comment by edsonmachado** [comment]
Hi David,

I'm so sorry for my late response. That's ok, all is working well. Maybe something happened with my own server.
Thank you so much for your support and explanation about the problem.

Best regards,
Edson
