### ISSUE TITLE
how the species tree generated in orthofinder?

### ISSUE THREAD

**Issue by ChengYunazhi** [davidemms/OrthoFinder#153]
hi, @davidemms 

 how the species tree generated in orthofinder ? using Super-tree way based on all gene trees or Super-matrix way based on concatenating single-copy orthologroup alignments to infer species tree ?

If orthofinder can generate ultrametric tree and a output file which can be fed into CAFE for gene family evolution analysis, things will be more cool ! Just a suggestion.

Thanks 

Yuanzhi

**Comment by davidemms** [comment]
Hi Yuanzhi

This is the paper describing the species tree inference method: https://www.biorxiv.org/content/early/2018/02/19/267914

Basically, each orthogroup will all species present (typically hundreds or thousands) is used to infer a species tree and a a greedy consensus tree is taken of all of these individual estimates to get the final tree.

I may have a script that will convert a normal tree into an ultrametric tree, if I do then I will add it to the 'tools' directory.

All the best
David

**Comment by ChengYunazhi** [comment]
Thanks for your kind help.  I set "-M msa" and run orthofinder, Alignments of each OG were generated, and a SpeciesTreeAlignment.fa were found, if the SpeciesTreeAlignment.fa was generated by concatenating all OG alignments (no matter whether the OG is single-copy)? and the rooted species tree was generated based on this SpeciesTreeAlignment ?

**Comment by davidemms** [comment]
Ah yes, the MSA option is different. It is done from a concatenated alignment of single-copy orthogroups (those with at most one gene per species). For some species sets which have been diverging for a very long time there aren't enough single-copy orthogroups. In those cases, orthogroups that are mostly single single-copy are also used for the concatenated alignments by only using sequences for the species that are single-copy in that orthogroup and gap characters for the other species. For all cases, the rooting is done via [STRIDE](https://academic.oup.com/mbe/article/34/12/3267/4259048).

All the best
David

**Comment by ChengYunazhi** [comment]
What is the cut-off for "enough single-copy orthogroups"? how many sing-copy orthogroups are enough?

I saw gaps in alignments, whether these gaps were used to infer species tree ? I mean whether the tree infering algorithm used this gap information? I want to use r8s to infer the rate of evolution and divergence time, and r8s need to specify number of sites (parameter: nsites) used to infer tree, if I use tree generated by orthofinder, how do I set the "nsites" in r8s? Just count the total sites in SpeciesTreeAlignment.fa (include sites with gaps) ? Does orthofinder adopt some of alignment trimer (e.g. BLOCKS or trimAl) to trim alignment before infering species tree? 

Thanks

**Comment by davidemms** [comment]
Hi Yuanzhi

The method for 'enough single-copy orthogroups' is quite involved because of the problem OrthoFinder most solve. It uses the method in Supplementary Figure S2 in the Supplemental File S1 in the [STAG paper](https://www.biorxiv.org/content/early/2018/02/19/267914) linked to above. The reason for the complexity is that it has to work completely automatically for whatever dataset a user gives it. This could be a few very closely related vertebrate species or a combined set of lots of Ekaryotes, Archaea and Bacteria with a last common ancestor billions of years ago. And so the availability of single-copy genes will vary massively. As a minimum, it will aim to use genes from more that 100 orthogroups.

The alignment file you have seen is the one given to the tree inference program to infer the species tree. By default the tree inference program is FastTree, which uses a maximum likelihood model, but you can use other programs if you prefer. Columns with gaps in affect the likelihood calculation for taxa which have non-gap characters. Feel free to look up the details of maximum likelihood tree estimation if you need more details. The alignment (as seen in the concatenated alignment file) has been trimmed. If fraction *s* of species must be present in the orthogroups (as determined using method in Sup. Fig 2 and reported by OrthoFinder in it's output to screen) then columns with fewer than 0.5*s* non-gap characters are removed. I'm afraid I haven't used the software r8s so I wouldn't like to guess how they count sites if there are gap characters in the alignment.

All the best
David

**Comment by ersgupta** [comment]
@davidemms , you mentioned "I may have a script that will convert a normal tree into an ultrametric tree, if I do then I will add it to the 'tools' directory." Were you able to find one?

**Comment by amit4mchiba** [comment]
Hi David,

I was wondering if you have method to create time tree using output from Orthofinder. I wanted to run Cafe to identify gene families which were either gain or loss using orthofinder results from several species. 

In your first comment, you said-"I may have a script that will convert a normal tree into an ultrametric tree, if I do then I will add it to the 'tools' directory". I was wondering if you may advice smthing.

thank you so much in advance,

with best regards
Amit

**Comment by davidemms** [comment]
Hi Amit & Saurabh

Thanks for the reminder, there's now a script for converting trees to ultrametric: tools/make_ultrametric.py. It should be self explanatory.

All the best
David

**Comment by njliangdong** [comment]
> Hi Amit & Saurabh
> 
> Thanks for the reminder, there's now a script for converting trees to ultrametric: tools/make_ultrametric.py. It should be self explanatory.
> 
> All the best
> David

Hi, david,
when I run make_ultrametric.py, it return me error as below:
  File "make_ultrametric.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

my command is: python make_ultrametric.py species.mega.nwk; and here is my tree:
(Alaibachii:1.2622935409,((((Pcapsici:0.0223133256,((Pinfestants:0.0429607623,Psojae:0.0431443457)80:0.020266,Pramorum:0.0569652237)52:0.007308)100:0.226232,Pyvexans:0.2236009541)100:0.190778,((Pyguiyangense:0.1495680103,(Pyirregulare:0.0529655120,Pyiwayamai:0.1167789301)96:0.071600)85:0.067899,Pyultimum:0.1561296562)97:0.140509)99:0.186905,(((Pyaphanidermatum:0.1811009821,Pyarrhenomanes:0.2141837458)40:0.063070,Pyinsidiosum:0.1524106534)31:0.048141,(Pyoligandrum_CBS:0.0046188299,(Pyoligandrum_M1:0.0000021434,Pyperiplocum:0.0142780813)67:0.000002)96:0.195411)38:0.079124)63:0.150624,Sparasitica:0.7446785980);

**Comment by amit4mchiba** [comment]
Dear David,

Thanks a lot. It worked the way I expected. Thats great.

I have one more question. Is there also a way to scale the branch lengths into time units (similar to what the r8S or pathD8 program does). If for example the divergence time ("cal" in pathD8, see example below) between B and D (e.g. 50 MYA) and the number of sites of the alignment ("seql" in pathD8, see example below) that was used to create the tree is known, then rescale the branch lengths to time units (see example below with pathD8)? 

Also, I understand and agree with you that generating phylogenetic tree using entire datasets rather than concatenated allignment is more robust. But is it possible to identify number of sites used to draw phylogenetic tree in Orthofinder, as this will then help to assign time units and calculate divergence time.

Please let me know if you need more details to give me specific advice.

thank you so much in advance

Regards

#
pathD8 example in R at https://rdrr.io/github/heibl/ips/man/pathd8.html :

cal <- rbind(cal1 = c("Rat", "Ostrich", "minage", 260), 
             cal2 = c("Human", "Platypus", "fixage", 125),
             cal3 = c("Alligator", "Ostrich", "minage", 150))
colnames(cal) = c("tax1", "tax2", "age_type", "age")
phy <- read.tree(text = "((((Rat:0.007148,Human:0.001808):0.024345,Platypus:0.016588):0.012920,(Ostrich:0.018119,Alligator:0. 006232):0.004708):0.028037,Frog:0);")
seql <- 1823
pathd8(phy, exec = "/Applications/PATHd8", seql = seql, calibration = cal)

**Comment by davidemms** [comment]
Hi njliangdong, can you tell me what version of python you are running. Thanks, David

**Comment by josecarballo87** [comment]
Hello David and thank you for your very informative answers.
Do you know if there is any way to know how many orthogroups are included in the Species Alignment file?

**Comment by davidemms** [comment]
It should say on the output to the terminal.

All the best
David

**Comment by davidemms** [comment]
Also, in the latest changes since version 2.3.1 there is a new file `Species_Tree/Orthogroups_for_concatenated_alignment.txt` which lists the orthogroups used.

**Comment by caonetto** [comment]
Hi David,
Trying to run the ultrametric tree script, but getting the following error,
Traceback (most recent call last):
  File "/scratch/conda/envs/orthofinder/bin/tools/make_ultrametric.py", line 12, in <module>
    from orthofinder.scripts import tree
ImportError: No module named orthofinder.scripts


Is this because I am running a conda version?

**Comment by wangjw065** [comment]
my command run python  /yourpathto/cafe/bin/tools/make_ultrametric.py -h
returns:
 usage: make_ultrametric.py [-h] [-r ROOT_AGE] tree_fn
make_ultrametric.py: error: the following arguments are required: tree_fn
I think you should run the script in its install path

**Comment by vappiah** [comment]
Dear I would be grateful if I can get some clarification.

I have whole genome sequence of 9 bacteria isolates. I have already extracted the CDS sequences into fasta files and run orthofinder to identify orthologues. 
_python3.6 /opt/apps/bioinfo/orthofinder/2.5.4/orthofinder.py -M msa -A muscle -T iqtree -t 36 -a 6 -f ./proteins_

I would like to identify genes under selection using PAML, can I use the Species Alignment file to do this?

I am a bit confused here. Please advice 

Thanks
