### ISSUE TITLE
stupid question: how do I extract OGs with all species present?

### ISSUE THREAD

**Issue by l-yampolsky** [davidemms/OrthoFinder#154]
So, I got quite a number of such OGs:
Number of orthogroups with all species present	5276

I would like to have these 5276 OGs in 5276 fasta files, one defline per species in each. Or in a single fasta file with sequences concatenated. How do I achieve this?

Ideally, I would like to include only those in which all genes are singletons in all species.

Thanks in advance!

**Comment by davidemms** [comment]
Hi

You can get a fasta file for each orthogroup by running: 
`orthofinder -fg RESULTS_DIR -M msa -os`
where RESULTS_DIR is the directory containing your orthogroups results files (e.g. Orthogroups.csv). I'll release an update soon so that you get these files from a default OrthoFinder run.

In RESULTS_DIR there is a file, SingleCopyOrthogroups.txt, which tells you which of these have all species present with exactly one gene per species. I think that answers your final question. 

If you did want to find all the orthogroups with all species present (but no restriction on copy-number) then you can open the Orthogroups.GeneCount.csv file in excel and use that to identify them. E.g. for the example dataset I used the excel commands `=COUNTIF(B3,">0")`, `=SUM(G2:J2)` and `=K2=4` as shown here: [Orthogroups.GeneCount.xlsx](https://github.com/davidemms/OrthoFinder/files/1889054/Orthogroups.GeneCount.xlsx)

**Comment by l-yampolsky** [comment]
Thanks! Yes, I see now I could have figured this out from the options diagram. 
And I also see that should use -oa rather than -os if I need them aligned.

**Comment by yuzhenpeng** [comment]
I also have a question here, that is, we use protein sequences for alignment and clustering analysis, and if I finally want to get the corresponding nucleotide sequence, what should I do?

Thanks in advance!
