### ISSUE TITLE
Orthogroup fails when finding best outgroup for species tree

### ISSUE THREAD

**Issue by caonetto** [davidemms/OrthoFinder#158]
Hi,
I have been trying to run orthogroup in a big set of bacterial genomes (149) and it keeps on failing in the same part of the process. I have ran orthofinder in smaller sets without any issues. 
The following is the command I am using,

orthofinder -f '/data/WICgenome/all_strains_pep' -t 15 -a 16

My cloud has 16 threads and 64gb or ram.

Any ideas what could be failing? 

The following is orthofinder output.

```
Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /data/WICgenome/all_strains_pep/Results_Apr20/Orthogroups.csv
   /data/WICgenome/all_strains_pep/Results_Apr20/Orthogroups.txt (OrthoMCL format)
   /data/WICgenome/all_strains_pep/Results_Apr20/Orthogroups_UnassignedGenes.csv
2018-04-21 00:54:16 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2018-04-21 01:01:03 : Done

Inferring gene and species trees
--------------------------------
2018-04-21 01:01:05 : Done 0 of 4157
2018-04-21 01:01:17 : Done 1000 of 4157
2018-04-21 01:01:23 : Done 2000 of 4157
2018-04-21 01:01:30 : Done 3000 of 4157
2018-04-21 01:01:36 : Done 4000 of 4157

1337 trees had all species present and will be used by STAG to infer the species tree


Best outgroup(s) for species tree
---------------------------------
Traceback (most recent call last):
  File "/home/users/conetto/.conda/envs/snakes/bin/orthofinder", line 1549, in <module>
    GetOrthologues(dirs, options, program_caller, clustersFilename_pairs, orthogroupsResultsFilesString)
  File "/home/users/conetto/.conda/envs/snakes/bin/orthofinder", line 1398, in GetOrthologues
    options.name)
  File "/home/users/conetto/.conda/envs/snakes/bin/scripts/orthologues.py", line 976, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, all_stride_dup_genes = stride.GetRoot(spTreeFN_ids, os.path.split(db.TreeFilename_IDs(0))[0] + "/", stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
  File "/home/users/conetto/.conda/envs/snakes/bin/scripts/stride.py", line 504, in GetRoot
    list_of_dicts = pool.map(SupportedHierachies_wrapper2, [(fn, GeneToSpeciesMap, species, dict_clades, clade_names, qWriteDupTrees) for fn in glob.glob(treesDir + "/*")])
  File "/home/users/conetto/.conda/envs/snakes/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/users/conetto/.conda/envs/snakes/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
Exception

```

Thanks for your help.

**Comment by stubbsrl** [comment]
Hi - Just a heads up this same issue is already open [(#151)](https://github.com/davidemms/OrthoFinder/issues/151). Subscribe to that thread so see if it is resolved. It's interesting it is happening to three of us with three different datasets. 

Best,
Rebecca

**Comment by davidemms** [comment]
Hi

The error message here is different to the one posted in issue 151 so it's best to treat them as separate problems. 

I'm just trying to research the error message here, I'll let you know what I find.

All the best
David

**Comment by stubbsrl** [comment]
Awesome! Thanks for the update. I was just trying to streamline things...

**Comment by davidemms** [comment]
The error is occurring in part of the code that is being run in parallel, and unfortunately in those circumstances python doesn't print the original error message and you just get the message above instead. Would you be able to send me some files so that I can debug the issue. I'll need
`/data/WICgenome/all_strains_pep/Results_Apr20/Orthologues_Apr21/WorkingDirectory/STAG_SpeciesTree_ids.tre` and also could you compress the directory `/data/WICgenome/all_strains_pep/Results_Apr20/Orthologues_Apr21/WorkingDirectory/Trees_ids/` as well and send that to me to? You can send it to david_emms@hotmail.com.

Thanks
David

**Comment by stubbsrl** [comment]
The file is too big to send to a hotmail address apparently. Attached here and I'm going to delete it once you have downloaded it. Also I can’t find the STAG_SpeciesTree_ids.tre file. My path is slightly different than the one you posted I went to /amino_acids_all_genes/Results_Apr23/Orthologues_Apr24/WorkingDirectory. But inside that directory are four folders and not the .tre file you mentioned. Where did I go wrong? 



[Trees_ids.zip](https://github.com/davidemms/OrthoFinder/files/1943385/Trees_ids.zip)

**Comment by davidemms** [comment]
Hi

Thanks, I've downloaded that file so it can be deleted now. However, the directory  `/amino_acids_all_genes/Results_Apr23/Orthologues_Apr24/WorkingDirectory` doesn't match the output posted above, which refers to `/data/WICgenome/all_strains_pep/Results_Apr20/`. Did you get the exact same error message with that run as well? Otherwise I might end up looking for the problem in the wrong set of files :s

If there's not a "STAG_SpeciesTree_ids.tre" file then the species tree could be called something different like "SpeciesTree_ids.txt" or similar. Do you have something like that in the WorkingDirectory or its sub-directories?

All the best
David

**Comment by caonetto** [comment]
Hi David,
I sent the files to your email.
Thanks for your help.

Cristobal.

**Comment by davidemms** [comment]
Hi 

This was a problem with non-binary species trees which has been fixed in the latest version, if you upgrade to that it will resolve the issue. You can restart the analysis from the already calculated orthogroups using the option, `-fg /data/WICgenome/all_strains_pep/Results_Apr20/` instead of the "-f" option (which would start a new analysis).

All the best
David
