### ISSUE TITLE
raise NewickError error

### ISSUE THREAD

**Issue by teshu02** [davidemms/OrthoFinder#165]
Hi,

Orthofinder finished with error. There are a lot of Bit*.pc files produced  under the WorkingDirctory. 

Orthofinder version:  orthofinder/1.1.9
command: orthofinder.py -t 70 -b orthofinder.30.05.2017/Results/WorkingDirectory/ -f AddTthyandHhuc/​

Please find attached the error i got.

[error.txt](https://github.com/davidemms/OrthoFinder/files/2020374/error.txt)
Best,
Teshome

**Comment by davidemms** [comment]
Hi Teshome

From the partial output I think what probably happened is that the machine ran out of RAM and it killed some of the parallel orthofinder processes. I have recently submitted a fix that should identify if this has happened and warn the user: https://github.com/davidemms/OrthoFinder/commit/8935670aa23bf38f1491aabafca40a31adfa3d9e.

Could you try downloading the latest version of the code from the front github page: https://github.com/davidemms/OrthoFinder, it should now tell you if this happens. You won't need to install the code, you can just download and run it. However, you'll need to revert two of the 'WorkingDirectory/' files to their previous state in order to be able to run your command again. You'll need to delete the lines at the end of the files 

- SpeciesIDs.txt 
- SequencesIDs.txt

corresponding to the species in your directory 'AddTthyandHhuc/'.

All the best
David

**Comment by teshu02** [comment]
Hi David,

Thank you so much. I run orthofinder in a 1TB RAM node and will be surprised if memory was an issue. I just installed the latest orthofinder and started the command after i cleaned the two files as you suggested. I will let you know the status when it is done.

Cheers,
Teshome

**Comment by teshu02** [comment]
Hi David,

My jobs are completed without an issue. I guess memory could have been the reason. Thank you for the help and you may close this issue.

Cheers,
Teshome
