### ISSUE TITLE
MSA error 

### ISSUE THREAD

**Issue by ChengYunazhi** [davidemms/OrthoFinder#166]
Hi @davidemms 

 MSA fail when rerun orthofinder based on previous results (just delete some unwanted species), here it was: 

![error](https://user-images.githubusercontent.com/13846735/40351367-d5fb6fe8-5dde-11e8-92bb-a9ff00d45053.png)

the command used: 

![command](https://user-images.githubusercontent.com/13846735/40351465-0bf8994a-5ddf-11e8-83c1-7f1834fc497d.png)

**Comment by davidemms** [comment]
Hi

It looks like one or more of the 326 multiple sequence alignments was empty. I don't know why that would be, perhaps something was wrong with sequences or mafft failed for some reason. It looks like they were done very quickly, less than 7 seconds to do all 326 of them, which is suspicious.

Could you look to see if any of the alignments in `Results_Apr11/WorkingDirectory/Orthologues_May22/WorkingDirectory/Alignments_ids/` are empty or have no sequence data? Or is it all of them? 

If it's one of them then look at the corresponding input file in  `Results_Apr11/WorkingDirectory/Orthologues_May22/WorkingDirectory/Sequences_ids/` and try running mafft on it to see why it went wrong. If it's all of them, then try running mafft on any of the files and see what the problem was.

Let me know what you find out.

All the best
David

**Comment by ChengYunazhi** [comment]
in Alignments_ids/, files are empty:

![q4](https://user-images.githubusercontent.com/13846735/40361807-210dc9fe-5dfd-11e8-837a-e879b5c2ae51.png)

and in Sequences_ids, files are not empty:

![q3](https://user-images.githubusercontent.com/13846735/40361837-344f63b0-5dfd-11e8-89d4-2a396c0eaa2c.png)

**Comment by davidemms** [comment]
Hi

Do you have an update on this? 

Thanks
David

**Comment by ChengYunazhi** [comment]
em....., it seems everything goes well for this test command.  I will rerun orthofinder -b -m again to what will happen. 
![q5](https://user-images.githubusercontent.com/13846735/40466699-5f86f90a-5f59-11e8-80ce-875528e9ac5f.png)
