### ISSUE TITLE
How to resume tree building correctly: -fg/-ft usage

### ISSUE THREAD

**Issue by reubwn** [davidemms/OrthoFinder#171]
Hi David,

My question is about resuming an OrthoFinder run after an interruption (e.g. walltime limits on HPC clusters). I've read the manual section but was still a little unclear - apologies if I've just missed something.

The original command was:
```
orthofinder.py \
-t $THREADS \
-a 8 \
-I 2 \
-S diamond \
-M msa \
-A mafft \
-T iqtree
```

... and the BLAST and Groups stages are completed successfully:
```
>> ll Results_May23/
total 21M
drwx------ 6 foo hpc-users   99 May 24 00:23 Orthologues_May24/
drwx------ 2 foo hpc-users  32K May 29 11:56 WorkingDirectory/
-rw------- 1 foo hpc-users 1.8M May 24 00:23 Orthogroups.GeneCount.csv
-rw------- 1 foo hpc-users 8.3M May 24 00:23 Orthogroups.csv
-rw------- 1 foo hpc-users 8.8M May 24 00:22 Orthogroups.txt
-rw------- 1 foo hpc-users 1.6K May 24 00:23 Orthogroups_SpeciesOverlaps.csv
-rw------- 1 foo hpc-users 1.3M May 24 00:23 Orthogroups_UnassignedGenes.csv
-rw------- 1 foo hpc-users 1.6K May 24 00:23 SingleCopyOrthogroups.txt
-rw------- 1 foo hpc-users 1.6K May 24 00:23 Statistics_Overall.csv
-rw------- 1 foo hpc-users 7.1K May 24 00:23 Statistics_PerSpecies.csv
```

When I look in `Orthologues_May24/` I see:
```
drwx------ 2 foo hpc-users   10 May 24 00:23 Alignments/
drwx------ 2 foo hpc-users   10 May 24 00:23 Gene_Trees/
drwx------ 2 foo hpc-users 1.9M May 24 00:23 Sequences/
drwx------ 5 foo hpc-users   79 May 24 00:23 WorkingDirectory/
```
... but the `Alignments/` and `Gene_Trees/` dirs are empty. 

However, within `Orthologues_May24/WorkingDirectory/Tree_ids/` I can see that the vast majority of the trees (i.e., all OGs with >= 3 taxa) have been constructed already.

**What is the appropriate command to resume from this point?**

I have tried:
```
orthofinder.py \
-fg Results_May23/ \
-t $THREADS \
-a 8 \
-I 2 \
-S diamond \
-M msa \
-A mafft \
-T iqtree
```
... but so far this has taken longer than the original run, which included the time-consuming BLAST stage, and has generated only a fraction of the number of trees in the subsequent `WorkingDirectory/Tree_ids/` folder so I feel I must be doing something wrong!

Should I be using the `-ft Results_May23/Orthologues_May24/` flag instead of the `-fg` flag? The manual seemed to suggest that the `-ft` flag required output in the `Gene_Trees/` dir, whereas in this case this is currently empty.

Many thanks for your help!
reubwn

**Comment by davidemms** [comment]
Hi Reuben

You're right to use the '-fg' command. You would need the tree inference to have completed in order to use the '-ft' command. 

The reason for the long runtime is that you are inferring multiple sequence alignments and then maximum likelihood trees for each of the thousands of orthogroups. 'Full' ML tree inference using IQTree is a time consuming, but accurate process. It's a lot more time consuming than the default, fast, distance-based method and also more time-consuming than the approximate ML tree inference using the FastTree.

All the best
David

**Comment by reubwn** [comment]
Hi David,

Thanks for your help.

Is there then a way to allow OrthoFinder to pick up from where it left off within the gene tree building module? I.e., does the program look inside the existing `Orthologues_May24/` dir to see where it got to last time, or does the `-fg` command recalculate the gene trees from scratch?

**Comment by davidemms** [comment]
It's a good idea but I'm afraid I haven't implemented anything like that. It was really designed for rerunning analyses with different settings rather than as a mechanism to restart timed-out runs. I will have a look at some point to see if that functionality can be added, but I won't have time any time soon unfortunately.

**Comment by reubwn** [comment]
No worries! Yes I think your current implementation is the more useful, but it sure would be handy to be able to pick up from where it left off particularly as the MSA + ML tree approach is quite time consuming. Thanks again :-)
