### ISSUE TITLE
Bioconda orthofinder fails to run iqtree

### ISSUE THREAD

**Issue by AlexdeMendoza** [davidemms/OrthoFinder#173]
OrthoFinder version 2.2.1 installed through conda fails when specifying iqtree as -T parameter. 
I had to change the config file to specify -nt 1 and then it seems to run. However, it would be nice to know what is the relationship between iqtree -nt X and the orthofinder -a parameter. 

```Test can run "mcl -h" - ok
Test can run "fasta_folder_small_IQTREE//_dependencies_check/SimpleTest.fa" - ok
Test can run "iqtree" - failed

ERROR: Please specify number of cores via -nt option. Use '-nt AUTO' to automatically determine the best number of cores

ERROR: Cannot run user-configured tree method 'iqtree'
Please check program is installed and that it is correctly configured in the ~/.orthofinder.config file```

**Comment by davidemms** [comment]
Hi

If you're using a version of iqtree prior to 1.6 then you need to install the serial version of iqtree rather than the parallel version. From iqtree version 1.6 onwards these have been combined into a single version and this version works with OrthoFinder.

In terms of the iqtree '-nt' parameter and the OrthoFinder '-a' parameter, there's no relationship: OrthoFinder needs to infer thousands of trees. It's more efficient to run in parallel lots of separate trees rather than using iqtree to parallelize within individual trees since the first problem parallelises perfectly and so makes more efficient use of the computational resources whereas the second problem cannot be split as neatly into separate problems. Therefore OrthoFinder does each iqtree inference with one thread. The result is that for a fixed number of cores the complete set of trees will be calculated in less time than if we used '-nt 2', for example.

All the best
David
