### ISSUE TITLE
resume blast or diamond search after computer crash/restart

### ISSUE THREAD

**Issue by geo80** [davidemms/OrthoFinder#181]
I think it's not covered by the current add/remove species possibilities.

I had a run which crashed (due to server restart I suspect) while performing the diamond search. As a result, I have a folder with missing a (large) number of pairwise analyses.
Is it possible to resume the analysis, but make it ignore already existing analysed pairs?

Thanks

**Comment by davidemms** [comment]
Hi

There's no functionality to do this, but you could restart from the completed diamond searches if you can get them done yourself. It'd be relatively easy to do if you've got a bit of experience using linux, you'd just need to run the commands
 
diamond blastp -d diamondDBSpeciesY -q SpeciesX.fa -o BlastX_Y.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

with X & Y replaced with the values corresponding to the BlastX_Y.txt files that haven't been done. Note that you'll also need to run the ones which started but hadn't finished when the machine went down. 

(You can identify the started-but-not-finished ones either by looking at the files that were most recently updated e.g. if you were running 100 threads in parallel using '-t 100' then the most recently updated files will be the ones that were in progress, it'd be best to leave a margin for error though e.g. the most recent 120 files. Another way to check would be to look at the end of the BlastX_Y.txt files and check that they have hits for the last sequences in the corresponding SpeciesX.fa files, but this would be harder to do....)

Obviously, you'll want to run these commands in parallel. GNU-parallel is a useful tool, but I'm sure there are many other options.

To restart OrthoFinder from the completed BLAST files use:
"orthofinder -b WorkingDirectory/" instead of the '-f' option, with whatever other options you'd also like to use.

All the best
David

**Comment by geo80** [comment]
Thank you David for the quick reply.

As a side question, is it normal that some of the blast-results files (not the last ones that ran) are zero bytes?

Thank you again,
George

**Comment by davidemms** [comment]
No, that doesn't sound normal. I would try one of them again and see what you get, you're bound to have some hits between two species.

All the best
David

**Comment by Ingway** [comment]
I had the same issue using a conda installed OrthoFinder from a clean environment. The diamond version installed in this manner is very old (version 0.9.19), the header gets corrupted and some blastp search files have 0 bytes. I did the diamond blastp using davidemms command from the upper answer and resumed in OrthoFinder afterwards.
