### ISSUE TITLE
RAXML-NG compatibility

### ISSUE THREAD

**Issue by aussieEd** [davidemms/OrthoFinder#184]
Hi,

I was just wondering if orthofinder is compatible with RAXML-NG:
[https://github.com/amkozlov/raxml-ng](https://github.com/amkozlov/raxml-ng)

Thanks,
Ed.

**Comment by davidemms** [comment]
Hi Ed

I think it should be easy to use RAXML-NG. OrthoFinder has a simple config file that allows you to tell it how to call any tree inference program you want to use, as long as the method of calling the program isn't too 'wierd' ;-) 

You'd just need to add an entry to the orthofinder/config.json file to tell it how to call it. There will already be an entry for raxml so you can just copy and adapt that. Let me know how you get on.

All the best
David

**Comment by aussieEd** [comment]
Thanks David. 

As soon as I can get the standard orthofinder run to complete (see other thread) I'll give this a shot.

**Comment by AlexdeMendoza** [comment]
Regarding this same issue, raxml-ng is faster than raxmlHPC-AVX, but the problem is that the output files are not named the same. For instance, the command as written in the config file:
`raxmlHPC-AVX -m PROTGAMMALG -p 12345 -s OG0004671.fa -n OG0004671 > /dev/null`
retrives a file such as `RAxML_bestTree.OG0004671` in 1m20.716s. I guess this is the file used downstream for calling Orthologues in the species comparisons.
`raxml-ng --msa OG0004671.fa --model LG+G8 --seed 12345 --threads 1`
retrives a file called `OG0004671.fa.raxml.bestTree` in 1m0.593s (25 sequences, 984 positions). Despite this is a very trivial difference in file naming, likely it would break the later steps of the Orthofinder pipeline (e.g. assigning orthologues based on phylogeny).

Given that raxml-ng seems to be faster and actively developed (and it is faster than RAxML8 and IQTREE, more precise than FastTree, so quite crucial for big analysis such as Orthofinder runs), maybe it would be nice to include full compatibility and hopefully it would not require many changes in the code. 

Best, 

Alex

**Comment by davidemms** [comment]
Hi Alex

That's not a problem at all, there's a line in the config file to specify what the output file is called. I've added the entry to the config file and will submit it in the next few minutes. Thanks for the encouragement to put this in! Also, just a note about raxml-ng, it says that it's a beta release so if you see any problems with it be sure to report them to the developers. I made one change and specified "LG+G4" as this is a more traditional model and should be faster, but feel free to adapt the command line in the config file to whatever suits you best.

Ed, I hope you managed to get this sorted already. Apologies for the delay if not, things have been a bit busy!

All the best
David
