### ISSUE TITLE
Branch support in species tree

### ISSUE THREAD

**Issue by komalck88** [davidemms/OrthoFinder#195]
Dear Dr. Emms,
I ran a full OrthoFinder analysis (orthofinder -f fasta_dir -S) with proteomes from 39 species using DIAMOND functionality. My main aim was to get a rooted species tree. If I understood it correctly OrthoFinder uses STAG for a greedy consensus tree and STRIDE for rooting the tree considering duplication events by default? I used version OrthoFinder 2.2.6

My question is the analysis has generated 7 species trees "Potential_Rooted_Species_Trees" 
![capture](https://user-images.githubusercontent.com/31520092/44405633-02f43a80-a55a-11e8-8b1f-b43f403a36f1.PNG)
all with node labels starting with "N" as shown below:
![for github](https://user-images.githubusercontent.com/31520092/44405553-d17b6f00-a559-11e8-8c62-561006f0ac50.png)

I had outgroups in my dataset, so I can choose the best-rooted species tree out of seven potential rooted trees, but I don't understand what do this branch labels that start with N stands for? Could you kindly elaborate these branch supports in the tree?

**Comment by komalck88** [comment]
Ok, I just got it. N stands for node :-)

**Comment by davidemms** [comment]
Great, they'll be some expanded documentation coming soon....

In that case you should run the final step of OrthoFinder with 
`orthofinder -ft PATH_TO_DIRECTORY_IN_PICTURE -s PATH_TO_CORRECTLY_ROOTED_SPECIES_TREE`

It will do the orthologue inference from gene trees based on the correctly rooted gene tree. It will probably make only make some small changes to the orthologues inferred but will also root your gene trees using the correct outgroup too.

All the best
David

**Comment by komalck88** [comment]
Oh, Nice! Could you kindly tell me approximately when we would be able to use this function (based on correctly rooted trees)? I am asking because if it is soon enough, I would wait before proceeding with my current orthogroups, and instead wait for the updated version and re-run the OrthoFinder.

**Comment by davidemms** [comment]
For orthologues, where you root the tree can affects the orthologues that will be inferred **if duplication events have occurred**. See Figure 2 in [STRIDE: Species Tree Root Inference from Gene Duplication Events](https://academic.oup.com/mbe/article/34/12/3267/4259048). Given that there weren't many clear duplication events to distinguish between the 7 potential rooted trees and the one that it used, it may not make much of a difference. All the same, it's necessary if you want to make sure your orthologues are as accurate as they can be. It won't affect the orthogroups.

For the gene trees, it's only if you're going to be looking at them yourself or had a plan for using them. In that case they need to be rooted and it's easier if it's been done for you rather than having to do it manually.

All the best
David

**Comment by komalck88** [comment]
Sorry, I disturb you again. But the most-most probable root (the one with maximum probability) that STRIDE has generated for my species tree is in fact not the root that was expected. I had included two species from a different taxonomical order (as outgroups) to a set of 37 species (belonging to another taxonomical order) of my interest. Maximum probability should have come for this node where the speciation has occured between two different taxonomical orders, but in fact although this node was one of the most probable node of 7 nodes, it had the least probability percentage. This made me suspicious.

I have attached the Duplication_counts file generated by STRIDE here. According to predictions, Node 10 should have been the one with maximum probability.

Could you kindly clear this doubt for me, is there something that I understood wrongly?

Cheers,
Komal

[Duplication_counts.txt](https://github.com/davidemms/OrthoFinder/files/2331952/Duplication_counts.txt)
