### ISSUE TITLE
cPickle

### ISSUE THREAD

**Issue by spenagon** [davidemms/OrthoFinder#2]
Another dependency:

  File "orthofinder.py", line 40, in <module>
    import cPickle as pic                           # Y

ImportError: No module named 'cPickle'

**Comment by davidemms** [comment]
That's odd, cPickle is listed as part of the Python Standard Library for version 2.7 (https://docs.python.org/2/library/) and 2.6 (https://docs.python.org/2.6/library/).

cPickle is important for OrthoFinder since it allows it to read and write very large matrices to disk very quickly, which lets it achieve high performance without using too much RAM. This means it can calculate orthogroups for large number of species on a normal desktop instead of requiring high-performance computing resources making orthogroup analysis available to a wider range of users.

**Comment by spenagon** [comment]
Ah yes, that error is with Python 3.4.

**Comment by davidemms** [comment]
Closing this issue as wrong version of python was being used.
