### ISSUE TITLE
--help doesn't report long descriptions

### ISSUE THREAD

**Issue by jlanga** [davidemms/OrthoFinder#208]
Hi David.

When reading the command line documentation with `--help`, it doesn't show the long flag options, which make the code more readable.

The [argparse](https://docs.python.org/2/library/argparse.html) library is very handy to organize and parse arguments and flags.

Jorge

**Comment by davidemms** [comment]
Hi Jorge

Thanks, I had considered moving over to the argparse library but I couldn't find a way if doing it while maintaining compatibility with the current command options. I've also worked quite hard to maintain a single page help file so that users can see all the options in one glance.

All the best
David
