### ISSUE TITLE
How can I extract paralogs and orthologs seperately from Orthofinder output?

### ISSUE THREAD

**Issue by dxkyq917** [davidemms/OrthoFinder#211]
Hi, I am using Orthofinder and got an extensive output with orthologs and paralogs arranged in different orthogroups. My question is how can I extract the paralogs and orthologs seperately from the orthologs.csv output file?

**Comment by davidemms** [comment]
Hi

The orthologues are explicitly written out, the paralogues can be inferred since they are genes in the same orthogroup but which are not orthologues. It's done this way since writing out all paralogues could potentially consume large amounts of disk space.

The genes that are orthologues of each other are in the orthologues directory (eg. ExampleDataset/Results_Oct25/Orthologues_Oct25/Orthologues/) sorted per species and referenced to the orthogroup they come from. If you just want orthologues this is the place to go. If you want an explicit list of paralogues too then you'll need to identify the genes that are in the same orthogroup (e.g. ExampleDataset/Results_Oct25/Orthogroups.csv) but are not orthologues.

All the best
David

**Comment by LovellHAGSC** [comment]
Hi David,  
A follow up question. I want to classify blast hits within a polyploid as orthologs vs. paralogs. The Results_xx/Orthologues_xx/Orthologues/ directory contains only between-species orthologues. So, if you expand all combinations of orthologues, you find that there are really never any within-genome paralogs. This clearly isn't right — for sure I shouldn't use those files to infer within-genome orthologs. 

I guess, by some logic, self-hits are the only true orthologs within a genome, so all non-self blast hits would be paralogous. But, I could see holes in this argument. 

Do you have any advice on how to pull orthologs/paralogs from within-genome blast results?
Thanks,
John

**Comment by davidemms** [comment]
Hi John

As you say, all hits within a genome will be paralogs with the exception of the self-self hits. I'd also agree that self-self pairs are 'orthologs' in the limiting case of zero divergence time. So in terms of blast hits all non self-self hits within a genome are paralogs, and if you wanted to you could call the self-self hits 'orthologs' if it made sense to the analysis you want to perform.

All the best
David
