### ISSUE TITLE
Run hangs at multiple sequence alignment step

### ISSUE THREAD

**Issue by qsantana** [davidemms/OrthoFinder#231]
Hi David,

Thanks for the great program.

I am running OrthoFinder on a dataset of 20 proteomes. Previously, I ran OrthoFinder using the default options other than using BLAST instead of diamond. That ran to completion. I am now trying to use MAFFT instead of dendroblast and it hangs close to completion of the multiple sequence alignment step. In the WorkingDirectory/Alignment_ids I find that there is the expected number of alignment files (7515). I have this problem using both the binary (v2.2.7) and the python version (v2.3.2)

**Command**
 
./orthofinder.py -b ../../../orthofinder/OrthoFinder/Results_Dec11/WorkingDirectory/ -M msa -A mafft -a 20

OrthoFinder version 2.3.2 Copyright (C) 2014 David Emms

2018-12-12 09:55:40 : Starting OrthoFinder
176 thread(s) for highly parallel tasks (BLAST searches etc.)
20 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "mafft /home/quentin/new_gene_gain_loss/orthofinder/OrthoFinder/Results_Dec11/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "FastTree /home/quentin/new_gene_gain_loss/orthofinder/OrthoFinder/Results_Dec11/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Using previously calculated BLAST results in /home/quentin/new_gene_gain_loss/orthofinder/OrthoFinder/Results_Dec11/WorkingDirectory/

Running OrthoFinder algorithm
-----------------------------
2018-12-12 09:55:45 : Initial processing of each species
...
2018-12-12 09:59:46 : Connected putatitive homologs
2018-12-12 10:00:06 : Written final scores for species 17 to graph file
...
2018-12-12 10:01:25 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /home/quentin/new_gene_gain_loss/orthofinder/OrthoFinder/Results_Dec11/WorkingDirectory/OrthoFinder/Results_Dec12/Orthogroups/Orthogroups.tsv
   /home/quentin/new_gene_gain_loss/orthofinder/OrthoFinder/Results_Dec11/WorkingDirectory/OrthoFinder/Results_Dec12/Orthogroups/Orthogroups.txt (OrthoMCL format)
   /home/quentin/new_gene_gain_loss/orthofinder/OrthoFinder/Results_Dec11/WorkingDirectory/OrthoFinder/Results_Dec12/Orthogroups/Orthogroups_UnassignedGenes.tsv
Sequences for orthogroups:
   /home/quentin/new_gene_gain_loss/orthofinder/OrthoFinder/Results_Dec11/WorkingDirectory/OrthoFinder/Results_Dec12/Orthogroup_Sequences/

2018-12-12 10:01:51 : Done orthogroups

Analysing Orthogroups
=====================
2018-12-12 10:01:53 : Starting MSA/Trees
Species tree: Using 7515 orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2018-12-12 10:02:10 : Done 0 of 7515
2018-12-12 10:04:03 : Done 1000 of 7515
2018-12-12 10:06:02 : Done 2000 of 7515
2018-12-12 10:07:54 : Done 3000 of 7515
2018-12-12 10:09:35 : Done 4000 of 7515
2018-12-12 10:11:19 : Done 5000 of 7515
2018-12-12 10:12:55 : Done 6000 of 7515
**2018-12-12 10:14:33 : Done 7000 of 7515**

**Comment by davidemms** [comment]
Hi 

Is it possible that just one of the multiple sequence alignments was still being run? If so it will finish eventually. Often the largest orthogroup, OG0000000, takes considerably longer than the rest. It's always the first to be started so as to mitigate against this. It could be more likely here because the orthogroups are being parallelised over 176 threads in this case (an so the remainder will finish more quickly). If this is the case, then it will finish but could take longer. You'll be able to see it's running using 'top', or another way of looking at what processes are running. The alignment file will also be empty until it has finished (I think). 

There's also the possibility of avoiding this using ideas (particularly 14th Sep) in this thread: https://github.com/davidemms/OrthoFinder/issues/199. It provides a way of getting OrthoFinder to use more cores for the largest alignments by making use of the config file. You'd be free to chose how many.

I can see that in general it may be a good idea to implement something like this permanently in OrthoFinder. If I can think of a way of deciding how and when more threads should be used for a particular alignment then I'll put something in. Things that the algorithm would need to consider are:
- Number of threads in total available to the algorithm
- Proportional size of an orthogroup relative to the other orthogroups
- How effective within alignment parallelisation is compared to across alignment parallelisation.


All the best
David
