### ISSUE TITLE
Wrong search for orthology groups

### ISSUE THREAD

**Issue by DNKonanov** [davidemms/OrthoFinder#234]
We use the representation of many genomes in the form of a graph. Groups of orthology are defined as nodes, and edges are drawn between nodes located sequentially in at least one genome. In the image, you can see an example of a graph.
In the analysis, we found a bug in which the same genes are found as different orthologs (a vertical row of green nodes in the image). Interestingly, these problems arise for genes located between two specific genes. The blasting shows that these are the same genes. (224 is bp length of a gene)
Do you know this problem and is it solvable?
![bug1](https://user-images.githubusercontent.com/10104922/50449871-17e33f00-093b-11e9-8ba1-08de984b5b09.png)

**Comment by davidemms** [comment]
Hi Dmitry

Just to check I understand, I think you're saying that you have three genes, from three different species that you believe are orthologues but have not been put in the same orthogroup by OrthoFinder. Is that correct, or is it something else? I'll try and answer that question, but let me know if it was something else.

If that's the case, then I think the issue is just that no orthogroup inference method, including OrthoFinder, is 100% accurate. OrthoFinder is the most accurate method available, about 83% on the orthobench test set and about 90% on randomly selected orthogroups. Unfortunately, this means that you will find genes that have been incorrectly dealt with.

In terms of solvability, it depends if you're interested in individual genes or on a genome-wide scale. On a genome-wide scale this will be very hard. Improvements that you make to solve one problem (genes left out of orthogroups) will often result in errors in other places (extra genes put in orthogroups in which they don't belong). For individual genes, the results can be checked manually by inspecting gene trees and fixing errors by hand.

Hope this helps
David
