### ISSUE TITLE
issues with the Example

### ISSUE THREAD

**Issue by zhangrengang** [davidemms/OrthoFinder#244]
I have tested the Example with OrthoFinder 2.3.1. First, I run
```
./orthofinder -f ExampleData -S diamond -t 8 -M msa -T iqtree
```
I found some of the gene tree node in "Gene_Duplication_Events/Duplications.tsv" should be not agreed with the gene tree in "Resolved_Gene_Trees/". For example as below, the gene tree node seemd to be "n3" for the duplicate as shown on the tree.
```
$ less Gene_Duplication_Events/Duplications.tsv | grep STRIDE
OG0000001       N2      n2      1.0     Non-Terminal: STRIDE    Mycoplasma_gallisepticum_gi|31541260|gb|AAP56562.1|, Mycoplasma_genitalium_gi|1046010|gb|AAC71532.1|       Mycoplasma_gallisepticum_gi|31541382|gb|AAP56683.1|, Mycoplasma_genitalium_gi|3844907|gb|AAC71551.1|
$ nw_display Resolved_Gene_Trees/OG0000001_tree.txt
                    /------+ Mycoplasma gallisepticum gi|31541260|gb|AAP56562.1|
          /------+ n5
          |          \--------------+ Mycoplasma genitalium gi|1046010|gb|AAC71532.1|
  /----+ n3
  |       |       /--------+ Mycoplasma gallisepticum gi|31541382|gb|AAP56683.1|
  |       \----+ n6
 /+ n1        \-------+ Mycoplasma genitalium gi|3844907|gb|AAC71551.1|
 ||
 |\------------------+ Mycoplasma genitalium gi|3844927|gb|AAC71569.1|
=+ n0
 |/------+ Mycoplasma hyopneumoniae gi|144227478|gb|AAZ44221.2|
 ||
 \+ n2/-------+ Mycoplasma agalactiae gi|290752414|emb|CBH40385.1|
  |   |
  \---+ n4/----+ Mycoplasma agalactiae gi|290752490|emb|CBH40462.1|
      |   |
      \---+/n7 Mycoplasma agalactiae gi|290752766|emb|CBH40741.1|
          ||
          \+/n8-+ Mycoplasma agalactiae gi|290752269|emb|CBH40240.1|
           \+ n9
            \----+ Mycoplasma agalactiae gi|290752270|emb|CBH40241.1|

 |-----|----|-----|-----|-----
 0   0.5    1   1.5     2
 substitutions/site

```

I have also tested another command:
```
./orthofinder -f ExampleData -S diamond -t 8
```
but get a different species tree as shown below. Which tree should I trust?

The species tree from the first command:
```
                                 /-----------------------+ Mycoplasma hyopneumoniae
 /-------------------------------+
 |                               \---------------------+ Mycoplasma agalactiae
=+
 |                               /----------------------+ Mycoplasma genitalium
 \-------------------------------+
                                 \------------------+ Mycoplasma gallisepticum

 |---------------|---------------|----------------|-------
 0             0.5               1              1.5
 substitutions/site
```
and the second command:
```
 /-----------+ Mycoplasma hyopneumoniae
 |
=+                               /-----------------------+ Mycoplasma genitalium
 |           /-------------------+ 0.947955
 \-----------+ 1                 \---------------------+ Mycoplasma gallisepticum
             |
             \-----------------------+ Mycoplasma agalactiae

 |------------|------------|------------|------------|----
 0         0.25          0.5         0.75            1
 substitutions/site

```

**Comment by davidemms** [comment]
Hi

Thanks for posting this. There was an issue with the labelling of the gene tree nodes/duplications file. This has recently been fixed in the master branch on github.

With the species tree question, you'll notice that they are the same tree topology (i.e. the unrooted trees are the same) but that a different root has been chosen in the two cases. The reason for this is that tree inference methods always return an unrooted tree. However, OrthoFinder attempts to help the user out by automatically searching for the best root for the species tree. It does this by looking for gene duplication events, since they imply a time direction in the gene trees. This is described in our paper [STRIDE](https://academic.oup.com/mbe/article/34/12/3267/4259048). 

The reason for the differences here is that there are very few gene duplication events in the Mycoplasma used in the Example--in fact they have tiny genomes and this is why they are used in the example dataset. However, because there are few gene duplication events, it is hard to work out where the root should go, hence the difference options you see here. However, remember that with any other method you would just get the unrooted tree and would have to decide where the root goes yourself anyway. 

The Mycoplasma are a bit of a pathalogical case, they only have ~300 genes each. In general, species will have a lot more genes and a lot more gene duplication events and so this problem is a lot less likely to occur. 

If you do find the root is in the wrong place on a real analysis you can re-root the tree yourself and ask OrthoFinder to use that one instead. 

All the best
David
