### ISSUE TITLE
problem with SingleCopyOrthogroups

### ISSUE THREAD

**Issue by icruz1989** [davidemms/OrthoFinder#246]
Hello, I have run Orthofinder successfully. However, I am a little bit concern about my results. I have to say that I am very new at this.  When I look out the file SingleCopyOrthogroups.txt I just found 78 orthogroups, and since my point of view, I do not know if they are very few or what?

These are the overall statistics 

Number of genes 464039
Number of genes in orthogroups  398925
Number of unassigned genes	65114
Percentage of genes in orthogroups	86.0
Percentage of unassigned genes  14.0
Number of orthogroups   26588
Number of species-specific orthogroups  597
Number of genes in species-specific orthogroups 2888
Percentage of genes in species-specific orthogroups     0.6
Mean orthogroup size    15.0
Median orthogroup size  13.0
G50 (assigned genes)    22
G50 (all genes) 18
O50 (assigned genes)    5348
O50 (all genes) 6973
Number of orthogroups with all species present  8292
Number of single-copy orthogroups	78
Date    2019-02-25

I want to run CAFE, but I do not know if the Species Tree that was constructed with only 78 single-copy Orthogoups is enough. 

I used the option -msa (MAFFT and FastTree). 

Thanks

**Comment by davidemms** [comment]
Hi Ivan

For an orthogroup to be single copy, you'll need the gene not to have been duplicated or lost at any point in time, in any lineage, since the last common ancestor of your species. As you increase the number of species this actually becomes quite rare, so I think 78 is probably reasonable. In fact, some methods over-estimate the number of single-copy orthogroups by failing to identify many gene duplication events. 

The best thing to do if you're unsure about the tree would be to look at the support values for the species tree. When using the "-m MSA" option there is a file in the results directory: MultipleSequenceAlignments/SpeciesTreeAlignment.fa. This is the MSA used to infer the species tree. As bootstrap values aren't required by OrthoFinder it doesn't run any bootstraps by default as it would be too slow for most purposes. 

I'd recommend running something like IQTREE on this file with the standard 1000 bootstraps then you will be able to get a good idea of how reliable the tree is from these 78 orthogroups. E.g. 
"iqtree -s MultipleSequenceAlignments/SpeciesTreeAlignment.fa -m TEST -bb 1000 -nt 16".

Let me know if any of this is unclear.

All the best
David

**Comment by SWei2333** [comment]
Hi,
I apologize for asking this question here. I have read other inquiries about the number of Single_Copy_Orthologue_Sequences. However, I would like to ask, I have only 387 Single_Copy_Orthologue_Sequences, and my species are from 19 different groups within the same suborder. If I want to run CAFE, is this number acceptable, or do I need to relax my criteria to increase the count?
