### ISSUE TITLE
Trouble understanding tree support and gene duplications

### ISSUE THREAD

**Issue by keirwefferling** [davidemms/OrthoFinder#247]
Hi David (and/or anyone who knows the answer to my questions),

I've managed to run Orthofinder on a 51-taxon dataset (ferns!), but am having trouble understanding the output. I don't see any indication of support values on the species tree or species with gene duplications tree. Should I be seeing support values, given that I ran the analysis using the default DendroBLAST? If so, where do I find these values? I'm thinking to rerun the analysis using MSA + IQTree, but first want to get a grasp on what I currently have.

In my SpeciesTree_Gene_Duplications_0.5_Support tree I think I am seeing the number of orthogroups that underwent gene duplications (e.g., 6383 gene duplications at node 0, N0_6383?), but am not sure how to think about these numbers. Are these the number of gene trees that underwent duplication at this bipartition... with at least 50% support? 

[SpeciesTree_Gene_Duplications_0.5_Support.tre.pdf](https://github.com/davidemms/OrthoFinder/files/2915493/SpeciesTree_Gene_Duplications_0.5_Support.tre.pdf)

Finally, why are there no net gene losses shown? Are these node values ever negative? I see that some of my nodes show 0 duplications (?).

Thank you!
— Keir

**Comment by keirwefferling** [comment]
**Update:** 
I finally found the species tree with support values! It was in the results folder before I reran with a rerooted species tree... makes sense. These support values reflect the proportion of input gene trees showing that bipartition out of all gene trees used in the final tree? Are the input trees the gene trees of orthogroups with all species present?

[SpeciesTree_rooted.tre.pdf](https://github.com/davidemms/OrthoFinder/files/2922370/SpeciesTree_rooted.tre.pdf)

I still am confused by the gene duplication numbers I see in the SpeciesTree_Gene_Duplications_0.5_Support.tre.pdf both at the nodes and the tips, and don't quite know how to find out how many input genes were used in these analyses, nor how realistic these numbers are. Thank you!

**Comment by davidemms** [comment]
Hi Keir

In answer to your questions: 

- The support values for the species tree are here: **Species_Tree/SpeciesTree_rooted.txt** (I think you found that one already)
- The numbers in **Gene_Duplication_Events/SpeciesTree_Gene_Duplications_0.5_Support.txt** are the number of gene duplications that occurred on each branch of the species tree (including terminal branches) for which both copies of the duplicated gene were retained in at least 50% of the descendant species. They can be cross-referenced to the **Gene_Duplication_Events/Duplications.tsv** file which lists the orthogroups in which each of the (e.g. 6383) gene duplication events occurred, the 6383 branches on the gene trees where each of these duplication can be seen, the support value (proportion of descendant species in which both copies are retained) and the list of the genes descended from each duplication.
- What you said for the species tree support values in your second post is exactly right: "the proportion of input gene trees showing that bipartition out of all gene trees used in the final tree".

So the numbers from the gene duplication events is the total from the complete set of gene trees. Check out the Gene_Duplication_Events/Duplications.tsv file to get an idea of how realistic the numbers are. Specifically, try looking at some examples of the nodes in the gene trees where this table says the duplications occurred. That should give you an idea of the level of evidence at different support values.

Basically, a gene duplication event has occurred for every case in the table as evidenced by multiple copies of the gene in at least one species. The only thing that could be in doubt is the placement of individual duplications. If a tree the branching order in a gene tree is incorrect, then the duplication could be recorded on a branch different to the one on which it actually occurred. The 'support' value is good to look at here. As duplicated genes are often subsequently lost in some lineages, 50% retention is already quite good evidence for the location of the gene duplication event.

EDIT: With some of the recent releases of OrthoFinder, the node labels in the gene trees don't match the Duplications.tsv file as they were mistakenly relabelled. If this is the case for your dataset, you can rerun this step using the "-ft" option with the latest version of the code on github (rather than the latest release, 2.3.1)

All the best
David
