### ISSUE TITLE
Are MSAs generated from all orthogroups or only orthogroups with all species present?

### ISSUE THREAD

**Issue by AFisherCSULB** [davidemms/OrthoFinder#252]
Dear David Emms, 

I'm really enjoying using OrthoFinder2- thank you for developing such a wonderful program! 

As we're picking apart the results, I'm unclear about which set of files the MSAs are drawn from. In my results there are 28,316 orthogroups and 6,136 trees with all species present that are used by STAG. There were 587 orthogroups included in the MSA with at least 56% of species with single-copy genes. I read in your previous answers to issues and see in this alignment that some of the species have gaps, which means that there was more than one sequence present for that species. Can having all gaps in the alignment also mean that there was no sequence assembled for that species?  Are the MSAs constructed from the 28,316 orthogroups (with missing data for some species and potentially multiple sequences) or are they constructed from the 6,136 orthogroups (with all species present and potentially multiple sequences)? 

Thank you very much for your help in clarifying this point!  
Best, Amanda Fisher

**Comment by davidemms** [comment]
Hi Amanda

Just to clarify for other people reading this thread: I think we're talking about running OrthoFinder with two different options here. Firstly the default and secondly with MSAs, that's right isn't it?

In the default version there are no MSAs and STAG is used to infer the species tree using the 6,136 tree with all species present. In the second case, the MSA option is used. In that case OrthoFinder infers gene trees from MSAs and also creates a concatenated MSA in order to infer the species tree. For this it uses all orthogroups meeting a threshold for the number of species which have exactly one gene in the orthogroup. The remaining species can have either zero genes or more than one gene in the orthogroup and the corresponding columns in the MSA for these species have gaps. 

The 587 orthogroups could come from any of the 28,316 (i.e. not just from the 6,136 with all species present). They will be the 587 orthogroups with at least 56% of the species having exactly one gene. Basically, orthofinder has adjusted the percentage cut-off so as balance having as high a percentage as possible while simultaneously getting enough orthogroups. I realise now that it would be helpful for the user to know which orthogroups have been used so I've just added a new results file **Species_Tree/Orthogroups_for_concatenated_alignment.txt** that lists them. 

Are you observing that one species in the concatenated alignment is entirely gaps? I hadn't thought of that occurring but I guess it could if that species was never single copy in the selected orthogroups. If that's the case then I'm guessing it causes a crash or error? If so then I'll look at fixing that.

All the best 
David

**Comment by AFisherCSULB** [comment]
Dear David,  Thank you for your thoughtful response. Yes, I meant running OrthoFinder with the MSA option in my previous email. I appreciate you adding the new output file and clarifying where these trees can be drawn from. We haven't observed that any species in the concatenated alignment is entirely gaps- luckily our assemblies seem to be better than that!  Thank you again. 
Best, Amanda Fisher

**Comment by davidemms** [comment]
That's great, thanks.

David
