### ISSUE TITLE
concatenated sequences for species tree

### ISSUE THREAD

**Issue by supanthee** [davidemms/OrthoFinder#262]
Hi David,

Is there any way I can extract the concatenated sequences of used for MSA during species tree generation in orthofinder?

Would be happy to hear back.
Thanks
Suresh

**Comment by Neato-Nick** [comment]
Orthofinder doesn't use concatenated sequences to generate the species tree, it uses [STAG](https://www.biorxiv.org/content/early/2018/02/19/267914.full.pdf). 

Regardless, it does output the Alignments for each orthogroup in the folder Orthologues/Alignments/.

**Comment by davidemms** [comment]
Hi Suresh

The concatenated alignment is in `MultipleSequenceAlignments/SpeciesTreeAlignment.fa`. Additionally, the list of orthogroups used for this concatenated alignment is given in `Species_Tree/Orthogroups_for_concatenated_alignment.txt` and if you want to see the individual alignments corresponding to each of these orthogroups they are also in the directory `MultipleSequenceAlignments/`. These are all available if you use the `-M msa` option rather than the default.

All the best
David

**Comment by supanthee** [comment]
Hi David,
You saved me. 
Thanks alot.
Suresh
