### ISSUE TITLE
orthogroup sequences with diverse lengths

### ISSUE THREAD

**Issue by baoxingsong** [davidemms/OrthoFinder#272]
Dear David,
I am a heavy user of OrthoFinder now.

I have a couple of questions would like to ask you.
1, I am working on plants with large genome size. Do you have any suggestions which transcript to use for each gene, please?

2,  By checking the multiple sequence alignment under `Alignments` folder, the sequences belonging to the same group have very diverse length. For some alignments, I could find only very few columns have no `-`. Is there any parameter that could help to only group those sequences with similar length together, please?

Best wishes,
Baoxing

**Comment by davidemms** [comment]
Hi Baoxing

1. Use the protein primary transcript fasta file if using proteomes from Phytozome, otherwise select the longest transcript variant for each gene. This should reduce the runtime considerably and probably will also help with accuracy.

2. There's no parameter to adjust this, OrthoFinder has put them together because it believes they belong in the same orthogroup. You can check the gene tree for an orthogroup as the definitive method of determining if the sequences are in the correct orthogroup.

All the best
David
