### ISSUE TITLE
Highly similar proteins in different orthogroups

### ISSUE THREAD

**Issue by caonetto** [davidemms/OrthoFinder#277]
I ran orthofinder on 50 genomes of the same species, I looked into the Orthogroup.GeneCount.tsv file to extract orthogroups that were unique to a subset of strains. For some reason proteins that are 99% similar and with the same annotation in reference genome are not being clustered and appear as unique in the subset of strains. I looked into the proteins in all the proteomes and they are clearly present in many species and have high similarity after a blastp run. Any idea why this proteins are not being clustered together in the same orthogroup? Is there a way to tune the sensitivity in orthofinder?
Thanks.

**Comment by davidemms** [comment]
Hi

I can only really hypothesise: OrthoFinder was designed using the idea of a set of species whose relationships can be more or less described by a tree. I wonder whether these ideas don't hold for a set of strains from a single species, since admixture between sub-populations would produces relationships which aren't tree-like?

The only tunable parameter is MCL's inflation parameter which can be adjusted at the OrthoFinder command line with the '-I' argument. In general I wouldn't recommend adjusting it but it's possible that it may help you. 

All the best
David
