### ISSUE TITLE
different species tree results from orthofinder and STAG

### ISSUE THREAD

**Issue by fayweili** [davidemms/OrthoFinder#278]
I'm using the msa option (mafft + fasttree) in orthofinder to generate gene trees and species tree. But when I ran STAG (no astral) later on the gene tree folder I got different results, most notably on the branch supports. The branch supports from orthofinder are all "1", but those from STAG are much lower. 

What might cause the discrepancy? Thanks!!

**Comment by davidemms** [comment]
Hi

Two different methods are used. The MSA option uses a concatenated MSA of single-copy orthologs for tree inference, this is a standard approach. STAG uses a greedy consensus tree using estimates of the species tree from a far larger class of orthogroups (all orthogroups with all species present), it is described here: https://doi.org/10.1101/267914. 

STAG will almost always produce lower support values (since the supports values are the proportion of trees supporting each bipartition, and individual gene trees often differ from the species tree), but the STAG species tree is generally of similar accuracy to the concatenation method. These results of the accuracy tests are also shown in the paper.

All the best
David
