### ISSUE TITLE
FastTree illegal characters

### ISSUE THREAD

**Issue by SHetherington** [davidemms/OrthoFinder#28]
Hi David,
I had a problem running the; trees_for_orthogroups.py script.
The alignment stage worked and I received alignments for all orthogroups in /Alignments. However, quite a lot of the tree output files in /Trees were blank. After some searching I found that some of my species names had symbols which FastTree classes as illegal such as brackets so all the trees with those species in had not run. After finding this out it was easily fixed but I was wondering if there would be any chance you could add a check for illegal characters into the pipeline to stop this from happening.
Cheers

**Comment by davidemms** [comment]
The characters ( ) , : are all replaced by _ if they appear in the name for a sequences since they are used in the newick tree format and so are truncated/not allowed by FastTree or other tree inference programs. FastTree truncates the sequence name at these characters which can lead to sequences having the same name and consequently an error message.
