### ISSUE TITLE
Official docker?

### ISSUE THREAD

**Issue by MrTomRod** [davidemms/OrthoFinder#280]
Hi!

Have you considered making an official docker image?
I made a Docker container base on the outdated [cmonjeau/orthofinder](https://cloud.docker.com/repository/docker/cmonjeau/orthofinder) (Monjeaud Cyril <Cyril.Monjeaud@irisa.fr>)

Here's my build of the newest version: [troder/orthofinder](https://cloud.docker.com/repository/docker/troder/orthofinder)

Here's the Dockerfile: https://github.com/MrTomRod/Orthofinder-Dockerfile

**Comment by davidemms** [comment]
Hi

Thanks for doing this! Yes, I think an official Docker image could be something I'll look into in the next few months. 

In terms of gauging the need for a Docker image, what problem does having one solve/make easier for someone wanting to use OrthoFinder?

Thanks
David

**Comment by TheBigFatTony** [comment]
just the normal advantages of docker: the image contains all dependencies: no need to install MCL, diamond, the correct version of python/numpy or fasttree.

with docker, one only has to have docker installed - that's it. (there are alternatives to docker: singularity, podman, etc.)

the overhead is minimal because the daemon talks directly to the kernel.

**Comment by MrTomRod** [comment]
just the normal advantages of docker: the image contains all dependencies: no need to install MCL, diamond, the correct version of python/numpy or fasttree.

with docker, one only has to have docker installed - that's it. (there are alternatives to docker: singularity, podman, etc.)

the overhead is minimal because the daemon talks directly to the kernel.

**Comment by davidemms** [comment]
Hi Thomas

I'm just revisiting this as I'm writing a series of tutorials for OrthoFinder and am listing ways people can get OrthoFinder. They're not online yet, but I've thanked you in the post and will try and use what you've already done to provide an official docker image.

All the best
David

**Comment by davidemms** [comment]
Hi Thomas

Thanks again for your work and encouragement on this, I've now created an up-to-date and rationalised docker image based on the one you provided and will continue to maintain it from here. If you're able to point people towards it that'd be great. Also, if you have any advice on any of the changes I've made then please let me know, I've tried to cut down the packages it installs to the minimum while still maintaining full functionality.  

**Official OrthoFinder docker: [davidemms/orthofinder](https://hub.docker.com/repository/docker/davidemms/orthofinder)**

All the best
David

**Comment by MrTomRod** [comment]
Fantastic! I'll remove my repositories. Pretty sure people will find your docker image if you mention it on the OrthoFinder github page.

**Comment by MrTomRod** [comment]
Hey David

The docker image is still on version `2.3.11`. Could you please update it?

**Comment by davidemms** [comment]
Hi, thanks for reminding me, it's now been updated. 

However, current advice remains **not to use Docker** for OrthoFinder because of the very large performance penalty. 
- On Linux the recommended setup is to download and run the latest Release package here: https://github.com/davidemms/OrthoFinder/releases
- On Windows the recommended setup is to use the Linux subsystem for Windows and continue as for Linux
- On Mac the recommendation is to use bioconda

More details here: https://davidemms.github.io/orthofinder_tutorials/alternative-ways-of-getting-OrthoFinder.html

All the best
David

**Comment by MrTomRod** [comment]
Thanks for the hint, but currently, for me, it performs fast enough and docker is so convenient.
