### ISSUE TITLE
def ProcessesNewFasta only accepts uppercase amino acid sequences.

### ISSUE THREAD

**Issue by cErikson** [davidemms/OrthoFinder#285]
The ProcessesNewFasta fails QC if the ammio acid sequences are lowercase. Some sources like XENBASE use only lowercase for the fastas.

**Comment by davidemms** [comment]
Hi Christian

I've submitted a change so that these sequences are no longer rejected. I was a little apprehensive in case these sequences cause problems with any of the tree inference and alignment tools that OrthoFinder calls but with BLAST, DIAMOND, MAFFT, FastTree it appears to be fine. I might have to revisit this if problems arise but the change should probably be able to stay in the code.

All the best
David
