### ISSUE TITLE
mafft/dvtditr 

### ISSUE THREAD

**Issue by PlantDr430** [davidemms/OrthoFinder#287]
Hello, 

I am running a previous version (2.2.6) as I completed a previous run a while back and want to be consistent with those runs versus upgrading to a new version at the moment. I have recently completed runs with this version all the way to reconciled gene trees with the BlastP flag (took a while, but was able to complete). However, I decided to add 40 more genomes to my run so I started a completely new run (did not use previous blast results) with Diamond instead so I have a total of around 130 fungal proteomes.

The orthogroups were definitely found a lot faster but I am unsure if the program is stuck. 

Currently, on my screen it shows that I completed 31000 of 31291 "Inferring remaining multiple sequence alignments and gene trees", but doesn't show that I completed the last 291.  However, if I go into the Orthologues/WorkingDirectory/Alignment_ids directory I have 31425 alingment files. Also, in the Orthologues/WorkingDirectory/Trees_ids directory I have 25049 tree files. Although, these were completed a week ago. I have currently been running mafft/dvtditr -W 0.00001 -E 0.0 -s  0.0 -C 0 -t 0 -fF -l 2.7 -z 5..... for the past week. This is only using one core, even though I was running orthofinder with with -t 24 and -a 24 and is using a lot of memory. 

I am wondering if it is common for mafft/dvtditr to be running this long (given that I have 130 fungal proteomes). 

Thanks

**Comment by davidemms** [comment]
Hi Stephen

Yes, this can happen. OrthoFinder parallelises over the orthogroups rather than parallelising each individual orthogroup since this is generally the more efficient approach. It also starts the largest first as this will generally take the most time. What has almost certainly happened is that one of the orthogroups is taking disproportionately longer than all the rest and so what you're seeing is it finishing that one off while all the other tasks that were running in parallel with it have now finished. If possible, the best advice is to allow it to finish, which it will, if you are able to allow it the time. If it comes to it you can kill that mafft process and OrthoFinder will carry on without it, but it means sacrificing the tree for that orthogroup and all the orthologs within that tree!

Hope this helps,
David

**Comment by PlantDr430** [comment]
Alright, that's what I thought, I will allow it to finish. Thanks for the clarification.

**Comment by PlantDr430** [comment]
Hello @Edouard94,

This was from a while ago. I believe I just let it finish (likely took another couple of days or so). I haven't looked at the OrthoFinder code in a while so I am not sure what parameters MAFFT is running or if there is an OrthoFinder flag to set the MAFFT parameter to `--retree 1` (which is the fastest setting for MAFFT, but less accurate). 

I am not sure of your particular use case, but if you are just after orthogroups you can also stop OrthoFinder just after the orthogroup finding step and not compute the MSAs or Phylogenetic trees.
