### ISSUE TITLE
Collapsing isoforms for finding single-copy orthologs?

### ISSUE THREAD

**Issue by apredeus** [davidemms/OrthoFinder#320]
Hello, and sorry if this is a bit off-topic here. 

I've ran OrthoFinder on 28 very diverse species, trying to reproduce the analysis done in Figure 2 of this article https://www.nature.com/articles/s41559-017-0389-y. For each species I've downloaded proteins from NCBI. 

The analysis ran very smoothly and makes sense. However, no single-copy orthologs were identified at all. My hypothesis is this is because for many species predicted proteome is that of translated isoforms - so quite a few genes have more than 1 protein in the dataset. For example, Homo sapiens protein set from NCBI contains 112k proteins, which is obviously too many. 

What's a good way to handle this? Of course, I can map each downloaded proteome in some approximate way to a genome, and then use some sort of selection process to only keep one isoform per gene. Are there more established ways? Is there a database that follows "one protein per gene" approach? 

Thank you for all suggestions!

**Comment by davidemms** [comment]
Hi

Good question, I wrote a tutorial recently which covers this: [Running an example OrthoFinder analysis](https://davidemms.github.io/orthofinder_tutorials/running-an-example-orthofinder-analysis.html).

The summary is that it is best to keep one isoform per gene and the tutorial gives a way of doing that.

All the best
David

**Comment by apredeus** [comment]
Thank you very much! This is extremely helpful.

**Comment by ndrubins** [comment]
Hi davidemms,

I'm curious if you had other ideas in mind regarding the discussion above than selecting a single isoform per gene? It's hard to find a rule for selecting a single isoform that will not be arbitrary at all when applied to the entire proteome (although many phylogenetic tools/analysis use longest isoform as that rule).

A simple start would be to apply OrthoFinder to all isoforms. Then for each gene which has isoforms in multiple orthogroups, count how many isoforms it has in each orthogroup so that we get a distribution of the number of isoforms per each orthogroup. With that it is possible to exclude left-outliers in that distribution - isoforms that deviate from the majority of that gene's isoforms WRT orthogroup assignment.

Eventually entire orthogroups will be eliminated by this process, which are probably the less reliable one. 

It's obviously only realistic for genes for which that signal (i.e., left-outliers) is strong enough. For example, for genes with a small number of isoforms (e.g., 2-3) this is not applicable. But maybe other rules can be applied to these. For example, keeping the isoform which orthogroup has the higher number of genes from that species and genes in total.

Thoughts?

Thanks a lot
