### ISSUE TITLE
find ortholog between two species

### ISSUE THREAD

**Issue by LiuKe98** [davidemms/OrthoFinder#326]
Hello everyone,
      I want to get all the orthologous genes between two species for dN/dS analysis. But I have no idea how to do that. Can you give me some suggestions?
Thanks in advance,

**Comment by davidemms** [comment]
Hi

To get orthologs: Download the fasta files of the amino acid sequences of the protein coding genes for the species you are interested in, place them in a directory and then run orthofinder on that directory. One of the results is a table for each pair of species giving all the orthologs between those species. There are a series of tutorials here: https://davidemms.github.io/menu/tutorials.html

However, ff you want to do dN/dS analysis then you will probably need the coding DNA sequences for your genes too. Sometimes it is easy to get fasta files of the amino acid sequences and coding DNA sequences with corresponding IDs between the two files, if so then use these. A failsafe alternative is to get the coding DNA sequences and translate them to get amino acid sequences so that you have a pair of files with corresponding IDs.

All the best
David
