### ISSUE TITLE
Over estimation of duplications events

### ISSUE THREAD

**Issue by JC-therea** [davidemms/OrthoFinder#330]
Dear Dr. Emms,

Recently I am ussing OrthoFinder to find duplication events. I ran OrthoFinder with the following command:

python2.7 orthofinder.py -a 5 -M msa -f Yeast_proteins 

This makes a normal OrthoFinder output. However taking a look to the duplicaiton events (in OrthoFinder/Results/Gene_Duplication_Events) I saw some strange events like the following:

 ![image](https://user-images.githubusercontent.com/43994737/72079382-1775d600-32fb-11ea-853c-528219822123.png)

rna4009 and rna4012 are duplicated. This means that rna4009 comes from rna4005 and rna4012 from rna4009? I think that this can be solved with some home made script but there is something more problematic. 

I wanted to see the alignment of the sequences to see how they can match and this is the result:

![Screenshot from 2020-01-09 16-25-38](https://user-images.githubusercontent.com/43994737/72080308-d979b180-32fc-11ea-831d-2bbb3d0fe15b.png)

As you can see rna4009 and rna4012 match quite well with rna4005 and both look like different parts of the same protein. When I blast rna4009 to rna4012 no matches were detected. Probably this happens with more proteins but I have several groups with thousand of proteins and I can not check them all manually. My question is, which part can be doing this and how can I fix it? I mean do you think this is produced by the searcher, the aligner or the program for the tree inference?   

Kinds regards
JC

**Comment by davidemms** [comment]
Hi JC

This looks like it's behaving as intended, I think perhaps there's some confusion over what OrthoFinder is doing. But firstly, to identify gene duplication events reliably including those that are specific to just one species you will need to provide a single representative transcript per gene. What you might have here is multiple sequences per gene?  This is the cause of the second line from the file you have included an image of. You may be able to download a file of ongest transcript variants or you may have to parse the fasta file first and use the "gene=" text that is in your file to identify which sequences are from the same gene so that you only provide one (typically the longest). 

What OrthoFinder does is to infer the gene tree and then analyse the gene tree to identify speciation events and gene duplication events. If there is a node in the gene tree with two descendant genes from the same species then this is identified as a gene duplication event. Similarly  Have a look at the tutorial:
https://davidemms.github.io/orthofinder_tutorials/diving-into-the-results.html

and the description of the results files:
https://github.com/davidemms/OrthoFinder#what-orthofinder-provides
(particuarly the description of the file Duplications.tsv)

If you provide multiple transcripts per gene then this will affect things slightly. It looks like OrthoFinder has effectively identified for you that rna4009 and rna4012 are two halves of the same gene using the gene tree (and implicitly the other sequences as context, as you've been able to show with the MSA). Of course you will have no blast hit for  rna4009 and rna4012 as they have virtually no overlap.

For the first line from the duplications file that you provide, this also looks correct: there is an actual duplication here plus some confusion from the two sequences from the gene YLR157W.

All the best
David

**Comment by JC-therea** [comment]
Hi David, 

I already did the filtering for each gene. Looking in IGV the positions of the proteins that I showed you  they are located in different positions over the same chromosome, normally by some thousand of nucleotides. Probably this proteins were produced by partial duplication of one original gene (like YLR156W). So I think this is not the problem.

YLR157W-A (Also called YLR157W-D)
https://www.yeastgenome.org/locus/S000028677/sequence

YLR157W-B (Also called YLR157W-E)
https://www.yeastgenome.org/locus/S000028678

**Comment by davidemms** [comment]
Hi JC

I think perhaps I'm misunderstanding what you are asking because these results look correct to me and I'm struggling to understand what the query is. 

From what you've presented, it looks like there was an ancestral sequence, looking somewhat like YLR156W that duplicated and gave rise to two copies YLR157W-A & YLR157W-B. One of these lost a large portion of the first half of the gene and the other lost a large portion of the second half of the gene, giving the situation seen with the BLAST results you show and what can be seen in IGV. Based on its analysis of the gene tree (in the Resolved_Gene_Trees directory) OrthoFinder has reported the duplication event in the second line of the duplications file you've shown. This is the function it is meant to perform.

It's not that rna4009 comes from rna4005, that's a misreading of the results file. The results file says there was a gene duplication event and these two copies gave rise to rna4009 and rna4012.

All the best
David

**Comment by JC-therea** [comment]
Hi David,

Firstly, thank you for your patience in explaining some outputs of your software that I couldn't understand.

Secondly, I would want to know if I understand it well. First, there was a gene duplication that gave rise to YLR156W and 4 more genes (YLR159W, YLR161W, YLR157W-A and YLR157W-B). Then, there was another gene duplication event that rises YLR157W-A and YLR157W-B? Does this mean that YLR157W-A and YLR157W-B were involved in 2 duplication events?

Thank you for your help
JC

**Comment by davidemms** [comment]
Hi JC

Yes, that's more or less correct. But I think that might have been some additional duplications involving these genes on some other lines of the Duplications.tsv file, that aren't shown on the image above though? 

If I make some guesses about additional duplications fromt he file, I would say: There was a gene duplication that gave rise to two ancestral genes. One of these was inherited with no further duplications and became YLR156W. My guess is that there was a duplication giving rise to ancestral gene X (the ancestor of YLR159W & YLR161W) and ancestral gene Y (ancestor of YLR157W-A & YLR157W-B). Then there was the second of the duplications shown in the image above, where gene X duplicated to give YLR157W-A and YLR157W-B. And presumably a fourth duplication giving rise to YLR159W and YLR161W, although you'd have to confirm this. So, you'll have to check the duplications file and the tree, but my guess is that there were at least 3 duplications leading to YLR157W-A and YLR157W-B.

This is all easiest to see by looking at the orthogroup resolved gene tree (using a tree viewersuch as Dendroscope) that is referenced in the first column of the Duplications.tsv file.

All the best
David

**Comment by JC-therea** [comment]
Hi David,

This is the Orthogroup (printed with R and the package ape):

![OG0004988 tree](https://user-images.githubusercontent.com/43994737/72333270-cdef0780-36bb-11ea-9ace-afb1cb6c1466.png)

The Duplications.tsv file only include two lines for the orthogroup OG0004988. My thoughts are that as YLR156W, YLR159W and YLR161W are identical it is difficult to say the right order of duplications. Here as you said is easy to see that YLR157W-A and YLR157W-B come from a gene "X". Knowing this you will say that only 2 duplications are related to this orthogroup? If not you would say that the number of duplication events would be the number of genes related - 1?

In my current project, I have to be as accurate as possible with the number of gene duplications so it is an important question for me.

Thank you for your time.
JC

**Comment by davidemms** [comment]
Hi

Yes, I think you're right about it being hard to say the order in that case. I can only give my opinion on how you should quantify the number of duplications if it is of particular importance to your project, I think in the end it will be up to you how you interpret the data provided. Number of genes minus one sounds like a reasonable approach, assuming you also factor in speciation events too.

All the best
David

**Comment by JC-therea** [comment]
Hi,

I agree with you. Thank you for your time in this threat.

Best
JC
