### ISSUE TITLE
dlcpar requirement :: orthofinder tested using dlcpar_search

### ISSUE THREAD

**Issue by EricDeveaud** [davidemms/OrthoFinder#332]
Hello, 

according #314 dlcpar is no longer a dependency of OrthoFinder, however test_orthofinder.py still test OrthoFinder using dlcpar.

```
python /mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/tests/../orthofinder/orthofinder.py -R dlcpar -f /mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/tests/Input/ExampleDataset_renamed/ -s /mount/gensoft2/src/OrthoFinder/OrthoFinder-2.3.8/tests/Input/RootedSpeciesTree2_extra_brackets.txt
```

that lead to 
```
Test can run "dlcpar_search --version" - failed

stdout:

stderr:
/bin/sh: dlcpar_search: command not found

ERROR: Cannot run dlcpar_search
Please check DLCpar is installed and that the executables are in the system path
```

furthermore orthofinder.py accept -R option while help does not display it.
in scripts_of/__main__.py  ProcessArgs contains 

```
elif arg == "-R" or arg == "--recon_method":
            choices = ['of_recon', 'dlcpar', 'dlcpar_convergedsearch', 'only_overlap']
            switch_used = arg
            if len(args) == 0:
                print("Missing option for command line argument %s\n" % arg)
                util.Fail()
            arg = args.pop(0)
            if arg in choices:
                options.recon_method = arg
            else:
                print("Invalid argument for option %s: %s" % (switch_used, arg))
                print("Valid options are: {%s}\n" % (", ".join(choices)))
                util.Fail()
```

regards

Eric

**Comment by davidemms** [comment]
Hi Eric

You're correct that dlcpar is no longer a dependency. I'm afraid I haven't updated the tests recently, for example to remove the test of dlcpar. DLCpar is both less accurate and far far slower than the method implemented for inferring orthologs from gene trees. For this reason it is intentional that the help page doesn't list a "-R" option as this is not something intended for anyone to use. Since it is working functionality I haven't removed it, partly as it was helpful for performing the testing that was done in the paper. 

All the best
David
