### ISSUE TITLE
paralogs

### ISSUE THREAD

**Issue by lfaino** [davidemms/OrthoFinder#333]
Dear Developer,
is there a way to extrapolate Paralogs from a species used in the analysis?

cheers
Luigi

**Comment by davidemms** [comment]
Hi Luigi

Is it within-species paralogs you would like? And how far back in time would you like to go? The second question is because the answer will depend on how far back you want to go. Sometimes people want just the paralogs that diverged more recently than the last speciation affecting that lineage (in-paralogs) whereas it's also possible to trace all paralogs since the origin of an entire clade of species or even going right back to the origin of life.

All the best
David

**Comment by lfaino** [comment]
Hi @davidemms,
it is within species and as far back i can go. I would check a very old possible duplication

Cheers
Luigi

**Comment by davidemms** [comment]
Well, OrthoFinder will identify othologs/paralogs going back to the last common ancestor of all the species you provide it with. So the further back in time the last common ancestor of your input species the further back in time the paralogs will be. 

Your paralogs will be any all pairs of genes from your species in the Duplications.tsv file such that one gene is in column "Genes 1" and the other gene is in column "Genes 2". It will also tell you where on the species tree the duplication event occurred. But that's only if you really want to use OrthoFinder.....

Really, BLAST is a better tool to solve your problem of identifying paralogs. OrthoFinder exists to solve the problem, "Of all the homologs, which genes are orthologs and which genes are paralogs". Where you're looking within a species this isn't a problem--all homologous sequences are paralogs! So a simple all-v-all search within the species will solve the problem, right back as far in time as it is statistically possible to identify homology. The only exception where OrthoFinder will be more useful is if you want to identify the time that the duplications occurred, or see the tree relating the sequences. In that case the OrthoFinder results from the duplications table I described about will tell you that.

All the best
David
