### ISSUE TITLE
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure

### ISSUE THREAD

**Issue by Hoberti** [davidemms/OrthoFinder#334]
Dear David,

I am trying to run Orthofinder, and I had several failed and it seems that this is the same error that issue ·159 that was corrected by email correspondence

Would you be able to help me?
Thank you.
Hector

Best outgroup(s) for species tree
---------------------------------
2020-01-24 17:19:43 : Starting STRIDE
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1681, in main
  File "scripts_of/__main__.py", line 1507, in GetOrthologues
  File "scripts_of/orthologues.py", line 961, in OrthologuesWorkflow
  File "scripts_of/stride.py", line 509, in GetRoot
  File "scripts_of/tree.py", line 221, in __init__
  File "scripts_of/newick.py", line 216, in read_newick
scripts_of.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
[11674] Failed to execute script orthofinder

**Comment by davidemms** [comment]
Hi

Which version of OrthoFinder are you using?

Thanks
David

**Comment by Hoberti** [comment]
Hi David,

I am using version 2.3.8

Thanks,

Hèctor

**Comment by davidemms** [comment]
Hi Hector

It looks like the tree inference failed for your species tree. I've not seen this before so I'm not sure why this would've happened--there also wouldn't be any way for OrthoFinder to be able to recover from this.

There may be some more information in the whole output OrthoFinder produced. Would you be able to send me the input files you used and the command so that I can reproduce this issue please?

Many thanks
David

**Comment by davidemms** [comment]
Hi Hèctor

If you're not able to provide the full dataset, would you be able to check if the file "WorkingDirectory/SpeciesTree_unrooted_ids.txt" exists and if it does, check if it's a valid newick file.

Many thanks
David

**Comment by davidemms** [comment]
Hi Hèctor

Sorry, I missed your previous emails, I'm looking into the data now.

Thanks
David

**Comment by davidemms** [comment]
It looks like for this dataset OrthoFinder was able to create a reasonably long MSA for the species tree, about 2.9 million columns. I'm monitoring FastTree while its running on this MSA and it is using ~13GB so I wonder if it crashed on the machine you were using because of the high RAM usage? I've run OrthoFinder on the input data you provided on a machine with high RAM and it ran fine and completed. 

If this is what happened I'll look to see if I can report if such an error occurs. The problem is that a number of the programs output to stderr even under normal operation and so it's hard to tell what is actually an error. I'll see if something based on the error codes is effective. This way errors produced by any programs called by OrthoFinder could be displayed to the user, which should help in seeing what went wrong.

All the best
David

**Comment by Hoberti** [comment]
Dear David,

Thank you so mucho for you response. I run the same command with only three
files of the data set and it run perfectly, so it could be that the RAM
usage was the problem. I will try to run it anyway in a high RAM computer
just in case to be sure that this was the real problem and I will let you
know.

I also receive the out files that you send it to me, so thanks you again
for this.

All the best,

Héctor
