### ISSUE TITLE
print newline as '\n' intead of '^M'

### ISSUE THREAD

**Issue by ersgupta** [davidemms/OrthoFinder#336]
Hi,

It seems the output files for Orthofinder use dos end of line characters. It makes it bit tricky to process the files (specially the files in Orthogroups folder: Orthogroups.txt and Orthgroups.tsv, I have not checked other files). Looking at the code it seems that csv.writer commands uses the default "lineterminator", would it possible for you to explicitly terminate the lines with '\n'?

Thanks

Regards
Saurabh

**Comment by davidemms** [comment]
Hi Saurabh

I remember looking into this in the past and I had thought I'd confirmed that OthoFinder was using the correct solution. If you believe you've identified an issue could you provide some clear steps so I can reproduce it:

- Operating system
- ascii characters you are finding at the end of your lines in the results file
- attach an example file
- a simple script demonstrating the difficulty processing the file (or steps to perform with some common software which manifests this problem, if that's easier). What should the script do, what occurs instead?

Many thanks
David

**Comment by ersgupta** [comment]
Hi David,

Sure, here is the info:
- Orthofinder version: 2.3.8
- Operating system: Ubuntu 14.04
- Ascii character found at end of line: ```^M```
- Example attached (for now, I change the dos formatted files using dos2unix) [Orthogroups_UnassignedGenes.tsv.gz](https://github.com/davidemms/OrthoFinder/files/4140648/Orthogroups_UnassignedGenes.tsv.gz)
- I try to process the output using sed by replacing <tab> with nothing. For instance, I want to obtain a two-column file of Orthogroups_UnassignedGenes.tsv by substituting all trailing <tab>s and substituting other multiple <tab>s with single <tab> using ```sed 's/\t\t*$//' Orthogroups_UnassignedGenes.tsv | sed 's/\t\t*/\t/'```. Due to ```^M``` character between ```"\t"``` and end of line ```"$"```, the first sed fails.

Not a python expert, but it seems this can be fixed by explicitly specifying ```lineterminator="\t"``` in ```csv.writer()```. (Maybe there are other better alternatives)

Hope this helps. Please let me know if you need any other information.

Regards
Saurabh

**Comment by davidemms** [comment]
Hi Saurabh

I've checked this out, and there has been no change in behaviour here from OrthoFinder. I used the default from the csv library since the CRLF line ending  is mandated by the CSV MIME spec: <https://tools.ietf.org/html/rfc4180#page-2>. I had assumed this also applied to TSV too, although now that I look it isn't as rigid: <https://www.iana.org/assignments/media-types/text/tab-separated-values>.

I've not know this to cause any problems over the last few years for any users and so wouldn't want to change this now and potentially create a number of new issues for users. For your regex I would just do:

```
sed 's/\r$//; s/\t\t*$// ; s/\t\t*/\t/' Orthogroups_UnassignedGenes.tsv > Unassigned_2_cols.tsv
```

All the best
David

**Comment by ersgupta** [comment]
Thanks David. For now I solve it by using ```dos2unix```, but good to know that "CRLF" is mandated by CSV MIME spec.
