### ISSUE TITLE
2 singlecopy genes found;construct phylogeny tree

### ISSUE THREAD

**Issue by LiuKe98** [davidemms/OrthoFinder#338]
Hello everyone,
    I  want to construct a phylogeny tree from 16 metazoan species using single-copy genes generated by orthofinder. But when I look out the file SingleCopyOrthogroups.txt, I just found 2 orthogroups. How should I do to achieve the phylogny tree?
Thanks in advance,

**Comment by davidemms** [comment]
Hi

Use the option, "-M msa -fg PREVIOUS_RESULTS_DIRECTORY". It will start from your already inferred orthogroups from the previous run but it will get OrthoFinder to select orthogroups that are single-copy in most species and then for each of these orthogroups use only the genes from those species that are single-copy to construct a concatenated MSA. This is what most studies do to infer a phylogeny, but OrthoFinder will do it automatically. It will use this to infer a species tree:
```
Species_Tree/SpeciesTree_rooted.txt
```

It will also produce two files to tell you the data used:
```
Species_Tree/Orthogroups_for_concatenated_alignment.txt
MultipleSequenceAlignments/SpeciesTreeAlignment.fa
```

All the best
David

**Comment by LiuKe98** [comment]
Dear David,
     Thanks for you quick reply. That helped me a lot! 
     But I have a question. Would you mind elaborating on "orthogroups that are single-copy in most species"?  How many species did the most species equal to? 
All the best

**Comment by davidemms** [comment]
Hi

The method used is described in the [STAG paper](https://www.biorxiv.org/content/10.1101/267914v1), Supplementary Figure 2. Basically, it starts by asking how many orthogroups are single copy in all species, n0. It then iteratively reduces the lower limit for number of species (that are single copy in each orthogroup) by 1. If the proportional increase in the number of orthogroups is greater than double the proportional decrease in the lower limit for single-copy species in the orthogroup then it continues for another iteration. 

The reason for this methodology is to try and increase the amount of data for species tree inference while keeping a relatively good lower limit on the minimum number of species in any of the orthogroups used. You will get a message from OrthoFinder telling you what cut-off was selected by this method, e.g. for the Example Dataset:

> Species tree: Using 246 orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup

All the best
David

**Comment by LiuKe98** [comment]
Dear David,
Thanks a million for your reply.
I run the command "-M msa -fg PREVIOUS_RESULTS_DIRECTORY" using orthofinder version 2.2.7. And I got the message:
     Using 456 orthogroups with minimum of 56.2% of species having single-copy genes in any 
     orthogroup. 
In addition, there are many files such as SpeciesTree_rooted.txt and SpeciesTreeAlignment.fa in the results,but no Orthogroups_for_concatenated_alignment.txt. Is SpeciesTreeAlignment.fa a concatenated alignment file for single-copy genes from 456 orthogroups selected by orthofinder? can I run RAxML to construct a species tree using the file  Alignments/SpeciesTreeAlignment.fa? 
All the best

**Comment by davidemms** [comment]
Hi

I think the Orthogroups_for_concatenated_alignment.txt was introduced in a later release, v2.2.7 is a year and a half old now and there have been a number of improvements since then. Yes, SpeciesTreeAlignment.fa is the concatenated alignment file from the 456 orthogroups, with gap characters in the corresponding columns for species that didn't have one gene in each particular orthogroup. And yes, you can run RAxML on this to construct a species tree. IQTREE is also a faster alternative that has similar accuracy. With either method, remember to root the tree on the outgroup after you've inferred it.

All the best
David

**Comment by LiuKe98** [comment]
Dear David,
Thanks a million for your reply and suggestions. I updated OrthoFinder to the latest version and run the command again. And now I have got the Orthogroups_for_concatenated_alignment.txt file from the process. Then I will construct a species tree using the SpeciesTreeAlignment.fa by running RaxML or IQTREE.
Thank you very much for your help!
All the best
LiuKe

**Comment by jeffkimbrel** [comment]
Just to add to this (already closed) issue, my orthofinder v2.3.11 run produced zero single-copy orthogroups in all species, but did not create a `Orthogroups_for_concatenated_alignment.txt` file. 

Do you advise relaxing settings somehow so that at least a few orthogroups are found in all species? I only have 153 species, but these are MAGs from a diverse soil environment. They are all >50% complete, but the fact that they are not all mostly complete might be making issues for identifying a common ortholog.

Let me know if I should open a new issue. Thanks.

**Comment by LiuKe98** [comment]
Dear David，
 If I want to present a super alignment matrix by myself like the file SpeciesTreeAlignment.fa for 456 orthogroups generated by OrthoFinder, should I extract all sequences and align them for each orthogroups and then trim these alignmnets and remove the multiple copy genes from 456 alignmnet files and concatenate all alignment files into one super matrix? Or do I just need to extract only the genes from those species that are single-copy for alignment, trimming and concatenation thesa super matrix for phylogeby?
LiuKe

**Comment by davidemms** [comment]
I've posted the answer here: https://github.com/davidemms/OrthoFinder/issues/352

Thanks
David
