### ISSUE TITLE
Allowing for multiple inflation values

### ISSUE THREAD

**Issue by DRL** [davidemms/OrthoFinder#34]
Hi,

would it be possible to change the command line argument -I to accept multiple (comma-separated) Inflation-values?

cheers, 

dom

**Comment by davidemms** [comment]
Hi Dom

I'm curious to know what you intended goal is when adjusting the inflation value? I added the option to alter it after a user request but I'm **strongly discouraging** its use. My impression is that in some cases people want 'smaller orthogroups', but an orthogroup has a precise definition and so there's no well-defined way that they can be made smaller--if there were lots of duplications in the orthogroup (i.e. since the last common ancestor) then there will be lots of genes! In fact, the OrthoFinder algorithm should hopefully be relatively resistant to changes in the MCL inflation value.

I'd suggest that depending on what your intended goal is there may be better ways of achieving it. What is it you'd like to achieve?

Thanks for your interest,

David
