### ISSUE TITLE
species order in SpeciesTreeAlignment.fa

### ISSUE THREAD

**Issue by Edison2021** [davidemms/OrthoFinder#353]
Hi David
I just found the species order in each OG alignment is not consistent with that in SpeciesTreeAlignment.fa. Is it normal?

Best
Edison

**Comment by davidemms** [comment]
Hi Edison

Yes, the species aren't in any particular order in the OG alignments.

All the best
David

**Comment by Edison2021** [comment]
Hi David
Are species order in all OG alignment the same? 

Best
Edison

**Comment by davidemms** [comment]
Hi Edison

Can I confirm which files you're asking about, is it the ones in 'MultipleSequenceAlignments/'? There is no intentional ordering of these sequences, I don't know if they come out in a particular order in some (or all cases). The intention is that sequence description line should be used

All the best
David

**Comment by Edison2021** [comment]
Hi David
In the MultipleSequenceAlignments/, there is a alignment of SpeciesTreeAlignment.fa. I am not sure how does the orthofinder generate this concatenated alignment. 
I suppose that: 1) mafft aligns individual OG sequences; 2) reorder OG alignments to make each file have same species order and 3) concatenate the reordered OG alignments. Are these steps the same as orhotfinder does?

Best
Edison

**Comment by davidemms** [comment]
Well in effect, yes, it does something like that. It uses uses the fasta ID line in each OG alignment to work out which sequence is from which species, so there's no need to order them to match them up.

Yes, if you use the "-M msa" command then it will use SpeciesTreeAlignment.fa for the species tree. There is also an option to provide the rooted species tree yourself using "-s species_tree_filename", in which case this will be used instead of OrthoFinder inferring it.

All the best
David
