### ISSUE TITLE
Running Orthofinder with multiple individuals per species

### ISSUE THREAD

**Issue by davidecarlson** [davidemms/OrthoFinder#369]
Hi All,
I'm working with some transcriptome data (converted to predicted proteome data with TransDecoder), and in some cases I have  transcriptomes from multiple individuals per species.

I'm wondering if it's sensible (or even possible) to use data from multiple individuals from the same species and have Orthofinder not treat them as different "species"?  Or would it be better to choose a single exemplar transcriptome per species and work with that?

Any thoughts?

Thanks!
Dave

**Comment by davidemms** [comment]
Hi Dave

Sorry, this one slipped my mind. There isn't any way to tell OrthoFinder to treat some individuals as being from the same species, I can't think of any particular changes I'd make in order to do this really. In principle OrthoFinder should just handle data like that automatically and so you could just try giving it everything. Of course this could be computationally expensive if you have lots of these individuals and so exemplar transcriptomes might be useful in this case.

Have you tried either of these approaches? How did you get on?

All the best
David
