### ISSUE TITLE
Orthofinder stop after Connected putatitive homologs

### ISSUE THREAD

**Issue by Lcornet** [davidemms/OrthoFinder#377]
# Running OrthoFinder-2.3.3 in pyenv 2.7.9

Hi, i have a problem running orthofinder, it stop after the Connected putatitive homologs.

I compute the blast myself for >300 fungi genomes (all refsqe fungi).  
OF takes < 1 cpus and do nothing.

Did I miss something ? a problem of RAM ?

Thanks,
Luc

## Log 

    [lcornet@node01 Fungi-dataset]$ tail OF.o1007505
    2020-04-24 10:56:34 : Initial processing of species 144 complete
    2020-04-24 11:08:00 : Initial processing of species 168 complete
    2020-04-24 11:14:50 : Initial processing of species 193 complete
    2020-04-24 11:28:26 : Initial processing of species 204 complete
    2020-04-24 11:37:29 : Initial processing of species 239 complete
    2020-04-24 11:48:33 : Initial processing of species 251 complete
    2020-04-24 11:59:23 : Initial processing of species 278 complete
    2020-04-24 12:06:27 : Initial processing of species 296 complete
    2020-04-24 15:54:34 : Initial processing of species 310 complete
    2020-04-24 16:57:22 : Connected putatitive homologs

## array blast

    #!/bin/bash
    #$ -S /bin/bash
    #$ -V
    #$ -cwd

    #$ -t 1-101124
    #$ -tc 250

    export BMD_BLAST_BINDIR=/media/vol1/apps/ncbi-blast-2.7.1+/bin/
    JOB=`sed -n "${SGE_TASK_ID}p" diamond.cmds`

    $JOB

    [lcornet@node01 WorkingDirectory]$ head diamond.cmds
    diamond blastp -d diamondDBSpecies0.dmnd -q Species0.fa -o Blast0_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species1.fa -o Blast1_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species2.fa -o Blast2_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species3.fa -o Blast3_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species4.fa -o Blast4_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species5.fa -o Blast5_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species6.fa -o Blast6_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species7.fa -o Blast7_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species8.fa -o Blast8_0.txt --more-sensitive -p 1 --quiet -e 0.001
    diamond blastp -d diamondDBSpecies0.dmnd -q Species9.fa -o Blast9_0.txt --more-sensitive -p 1 --quiet -e 0.001

##  Orthofinder run

    pyenv local 2.7.9

    /media/vol1/apps/OrthoFinder-2.3.3_source/orthofinder.py -t 40 -a 40 -b OrthoFinder/Results_Apr19/WorkingDirectory/

**Comment by davidemms** [comment]
Hi 

Is there a line "Initial processing of species 193 complete" for each of your species or only some of them?

It looks like your computer probably ran out of RAM while processing your BLAST results and killed the worker processes that OrthoFinder had started. Forty parallel threads for the high RAM tasks can be very demanding, try with a smaller value for -a, ideally "-a 1" and keep an eye on the RAM usage if you are able to. The '-a' parameter doesn't have much effect on overall runtime, I put it in there because some users asked about parallelising some additional steps that we're parallelised before, but I think it's usefulness can be over-estimated.

I will look to see if it's possible for OrthoFinder to detect if this happens so that it can print out an informative error message.

All the best
David
