### ISSUE TITLE
use of longest transcripts

### ISSUE THREAD

**Issue by mjfi2sb3** [davidemms/OrthoFinder#38]
Hi,

why is it best to use the longest transcript for Orthofinder analysis?

here is where you recommend this https://github.com/davidemms/OrthoFinder/blob/d86154429ea5ca5977b0b24df9ddfb248edc20cd/README.md#performing-your-own-orthofinder-analysis

Best,
/SB

**Comment by davidemms** [comment]
Hi 

That's a good question. It's not too important by I think there are two advantages: 

1. Genetic relationships. You're trying to work out how genes are related to one another. If there are two transcript variants for the same gene then they will likely share most of the same exons--otherwise they wouldn't be variants of the same gene! Thus their relationships to other genes in other species will most likely be the same. So you might as well just use one of them to work out what the genetic relationships are (orthologues, paralogues) and the longest transcript variant is the best one to use since it contains the most information. 

2. Speed. For example, Arabidopsis has 35,000 sequences in the Athaliana_167_TAIR10.protein.fa file and 27,000 sequences in the Athaliana_167_TAIR10.protein_primaryTranscriptOnly.fa file. If this is representative of the species in your analysis then it would take approximately (35/27)^2 = 1.68 times as long to run if you used all transcript variants.

All the best
David
