### ISSUE TITLE
The content of SingleCopyOrthogroups.txt is empty

### ISSUE THREAD

**Issue by fantasticair** [davidemms/OrthoFinder#385]
Hi David
I run the OrthoFinder (version 2.2.6) using the protein of 15 species, but in my result the content of SingleCopyOrthogroups.txt is empty, there is no single copy gene. Fortunately, we can get SpeciesTree_rooted.txt file, I want to know if this tree file is constructed with single copy genes, if the contained single copy genes should be the best hit in each species, how can I find them？
All the best
fantasticair

**Comment by fantasticair** [comment]
I want to know the sequences of `Results_May07/Orthologues_May07/Alignments/SpeciesTreeAlignment.fa` file are composed of specific protein sequences in every species?

**Comment by davidemms** [comment]
Hi fantasticair

The orthogroups used to construct this alignment are listed in the file, "Species_Tree/Orthogroups_for_concatenated_alignment.txt". You may need to update to a newer version in order to get this file, I'm note sure if it existed in version 2.2.6. 

The concatenated alignment is constructed from the single-copy genes from the species in each of these orthogroups that are single-copy. If a species is not single-copy in a particular orthogroup (i.e. the gene is missing or is multicopy) then that species has gap characters for that portion of the concatenated alignment.

All the best 
David

**Comment by fantasticair** [comment]
Hi,
Thanks for your reply,  I have updated  OrthoFinder (version 2.3.12) and get the file `Species_Tree/Orthogroups_for_concatenated_alignment.txt`, but in the document of `Single_Copy_Orthologue_Sequences` is empty, the genes in all species are multicopy. In the `Orthogroups_for_concatenated_alignment.txt` file include 1085 `OG` gene families, I know these `OG` concatenates the `MultipleSequenceAlignments/SpeciesTreeAlignment.fa`, however, what puzzles me is that such as `MultipleSequenceAlignments/OG0006433.fa` file has some similar sequences in a species, can you tell me which sequence is used to concatenates `MultipleSequenceAlignments/SpeciesTreeAlignment.fa`?
All the best
fantasticair

**Comment by davidemms** [comment]
The sequences used from OG0006433.fa are those that and single-copy in that orthogroup. The species that don't have a single-copy gene in that orthogroup are replace by gap characters instead.

All the best
David
