### ISSUE TITLE
Pre-computed blast results

### ISSUE THREAD

**Issue by Tdanis** [davidemms/OrthoFinder#387]
Hello again, I am trying to in implement Orthofinder in almost 40 species and due to the limited computational power, I would like to run Blast separately, before Orthofinder. In order to achieve Blast-all-vs-all I am preparing a file witch consists of the 40 species and I am running Blast this file against the copy of it. 
So, according the manual if someone run Blast separately has to follow the instructions to succeed an Orthofinder run and prepare 4 files,

• a FASTA file for each species
• a BLAST results file for each species pair
• SequenceIDs.txt
• SpeciesIDs.txt

But how can I prepare all these files for Orthofinder inputs from one single output (mega blast output), in order to avoid almost 40 separate blast runs? 

Thank you

**Comment by davidemms** [comment]
Hi 

In order to get OrthoFinder to prepare these files for you follow you can use the '-op' option (meaning 'only prepare'): <https://github.com/davidemms/OrthoFinder#running-blast-searches-separately--op-option>

However, I don't think your suggested workflow is optimal. Would you like to tell me the computational limitations you have and I can suggest the best way to proceed?

All the best
David

**Comment by Tdanis** [comment]
Yes of course , my proteome data-set in 40 species and ~ 1102499 proteins. My options are 
1) run blast in 7 machines with 20 cores and 150 memory and after that Orthofinder
2) run Orthofinder workflow in from start to end in one machine with 20 cores and 150 memory

So this is the reason that in my opinion blast searches must be implemented separately

Yes after -op option Orthofinder printed 4 blastp commands. But these commands are not the correct one because every dataset (2 in total) already contains all the proteins in order to succeed blast-all-vs-all searches.

If I run -op in a folder with every species proteome in separate fasta file , Orthofinder prints almost 40 blastp commands in order to accomplish blast-all-vs-all. And I want to avoid this with these “massive” mega-proteome files and blastp between these two.

**Comment by davidemms** [comment]
Hi

Yes, it could be useful to distribute the searches across those computers then. A few things before getting started on that. Have you considered using DIAMOND instead of BLAST? It's about 50x faster than diamond and is the default in OrthoFinder now, I never use BLAST anymore. It may then be fast enough to then run it on one machine or you might still want to use diamond but still split it up. It's probably also best to update to the latest version of OrthoFinder as there have been some performance improvements in recent releases. 

To distribute it across different machines:
1. Create the directory of fasta files, one for each species.
2. Run orthofinder with "-op" on this directory, this will print the 1600 commands you need to run.
3. Copy from the "WorkingDirectory" all the "Species*.fa" and "diamondDBSpecies*.dmnd" files (or "BlastSpecies*" files) to each computer.
4. Split up and run the 1600 commands in whichever way you want across the computers.
5. Copy the all results files ("Blast0_1.txt.gz" etc) back to the "WorkingDirectory" on the computer you want to run OrthoFinder on
6. Run orthofinder on the Results directory created in step 2: `orthofinder -b Results_May13/ -t 20 -a 10`

All the best
David

**Comment by Tdanis** [comment]
Thank you very much for the solution,  it was really helpful.
