### ISSUE TITLE
possibility to run Orthogroup analysis (-f) under various levels of stringency?

### ISSUE THREAD

**Issue by Thijmen18** [davidemms/OrthoFinder#400]
Dear all,

For a small dataset I would like to run various orthogroup analysis (-f) to see how my data behaves under various levels of stringency. Which genes will drop out orthogroups first, which ones are very stable, etc.

However, based on the manual I cannot change the overall stringency of the analysis only where the analysis stops in the pipeline. Is that true or am I missing something?

Thanks in advance!

**Comment by davidemms** [comment]
Hi

Yes, that's largely true. Rather than having some kind of stringency setting, OrthoFinder tries to estimate as best it can what genes are in the same orthogroup for each of the genes in the analysis. You can adjust the inflation parameter used by MCL, which is used by OrthoFidner to try get a global consensus of the individual estimates. This is done using "-I" parameter. I generally don't recommend this but it may be what you're looking for.

All the best
David

**Comment by Thijmen18** [comment]
Hi David,

Thanks for this. I really only want to explore my dataset, so the suggestion is helpful I think. To start from the “orthofinder starting point”, where can I find which inflation parameter is used by Orthofinder?

Thanks again,

Thijmen

**Comment by davidemms** [comment]
Hi Thijmen

All the OrthoFinder options are in the help page, just run `orthofinder -h`.

All the best
David
