### ISSUE TITLE
Monitoring the progress of orthofinder 

### ISSUE THREAD

**Issue by Tdanis** [davidemms/OrthoFinder#401]
Hello again, I am new user of orthofinder and I would like to know how to chech the progress of the software.

My command is :

orthofinder -S blast -M msa -T raxml-ng -b WorkingDirectory  -f  Proteomes -t 20 -a 10

currently is at this stage ...
..........
Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
 

And It 's been running for 22 days

Thank you

**Comment by Tdanis** [comment]
Hi , I checked the Orthogroups.GeneCount.tsv, but I dint manage to understand completely the info that contain. So, I counted the Tree_ids and are 1044 , the tsv contains 52992 rows , so  52992 orthogroups? And the rest trees are 52992-1044? 
The Total is 3494.


I am going to attach the tsv file, if you could help would be a great change in order to obtain more concrete opinion about Orthofinder.

[Orthogroups.GeneCount.tsv.tar.gz](https://github.com/davidemms/OrthoFinder/files/4763337/Orthogroups.GeneCount.tsv.tar.gz)

**Comment by davidemms** [comment]
Hi

The Orthogroups Gene Count file is the number of genes per species in each orthogroup. The total column gives the total number from all species in that orthogroup. See the README page for details.

If you go down through the table you'll see that orthogroups OG0000000 - OG0023799 have 4 or more genes so that's 24,800 orthogroups in total that you'll have to infer trees for of which approximately 1,044 have been completed.

All the best
David

**Comment by Tdanis** [comment]
Thank you again, I appreciate your  help.

Thodoris

**Comment by YuJiang0121** [comment]
Hi Thodoris，
May I ask how many species you analyze? How long did you spend in this step when analyzing this task？
Thank you again, I appreciate your help.
Yujiang
