### ISSUE TITLE
Problem in running FastTree and checking system path

### ISSUE THREAD

**Issue by Anki426** [davidemms/OrthoFinder#404]
Hi,

I have downloaded and installed FastTree in the folder "OrthoFinder". 
But when I run orthofinder for my protein files along with -M msa argument, there is an error that FastTree can't be found.

Attached is the screenshot of the terminal.

![Screenshot from 2020-06-13 23-48-47](https://user-images.githubusercontent.com/66776124/84576683-445f7500-add4-11ea-916c-e0e350c5e4f4.png)

I would be grateful if you could help me resolving this issue.

**Comment by davidemms** [comment]
Hi

I think that your current directory probably isn't in the system path. Try putting FastTree in a directory that is in the system path or adding the its directory to the system path.

All the best 
David

**Comment by Anki426** [comment]
> Hi
> 
> I think that your current directory probably isn't in the system path. Try putting FastTree in a directory that is in the system path or adding the its directory to the system path.
> 
> All the best
> David

**Comment by Anki426** [comment]
Thank you. As I am totally new to programming, I would be grateful if you could tell me how do I check my system path. Is there any command for that? 
Do I have to make any changes in the config.json file of OrthoFinder?

Will appreciate your response.


Ankita

**Comment by davidemms** [comment]
Hi Ankita

The list of directories in your system path are stored in the PATH variable. You can check what directories are in your system path using:
```
echo $PATH
```

When you try to call a program, the system will search through these directories in order to try and find it. You can change the system path like this:
```
export PATH=/usr/local/bin:/usr/sbin
```
However, in practice you are more likely to want to just add some directory to the system path (and keep the ones that are already there) and so you will do this:
```
export PATH=$PATH:/path/to/new/directory
```

So the best way to setup FastTree is to copy it to a directory already in your system path (if you have root privileges) or otherwise put it in a directory and add that directory to the system path (if you don't have root access).  Once you've done that, check that typing `FastTree` makes FastTree run. After you've checked this works then you can run OrthoFinder and it should be able to find FastTree. You don't need to edit the config.json file.

All the best
David
