### ISSUE TITLE
Question: Reconsiling gene trees with species tree without upstream analysis

### ISSUE THREAD

**Issue by alanbeavan** [davidemms/OrthoFinder#405]
Hi there,

Apologies if this question has been previously asked.

I am looking to perform just the reconsiliation of gene trees with a species tree labeled "(f) Hybrid overlap + DLC analysis of rooted gene trees to infer orthologs and gene duplication events" in your 2019 genome biology paper. 

The issue is that I am looking to reconsile rooted gene trees that have been made using iqtree on specific gene sets that I am interested in which don't necessarily represent "orthogroups". I also have a species tree to reconsile them with. Is there a way to perform only this step of the orthofinder pipeline using a set of gene trees and a species tree?

I have so far tried to trick orthofinder into thinking it has done the upstream analysis by creating a Gene_Trees, Orthogroup_Sequences and Orthogroups directory with files representing the genes I have used for each of my trees. When I run orthofinder with the -ft option, I get an error "ERROR: cannot find files from OrthoFinder run in directory:". The directories it is looking in include the directories I have created.

Best regards and thanks,
Alan

**Comment by davidemms** [comment]
Hi Alan

Yes, this is possible. You'll currently have to download Release 2.3.7 to do this (the source code version). With the trees for the ExampleDataset as an example:
```
mkdir output_dir
python ~/Release-2.3.7/source/OrthoFinder_source/orthofinder/scripts/resolve.py -r Species_Tree/SpeciesTree_rooted_node_labels.txt -n 32 -s second_dash Resolved_Gene_Trees/ output_dir
```

You can do this with non-OrthoFinder trees as well, the script just needs to be able to convert from the gene name to the species name, it includes a number of ways of doing this. Calling `resolve.py -h` will list the arguments for the script. Options for mapping to species are to split the gene name on one of:
```
[-s {dot,dash,second_dash,3rd_dash,hyphen}]
```
in order to give the species name.

For the Example data set this work like this. Species tree:
```
(Mycoplasma_hyopneumoniae:0.238425,((Mycoplasma_genitalium:0.455318,Mycoplasma_gallisepticum:0.412971)N2:0.378992,Mycoplasma_agalactiae:0.452282)N1:0.238425)N0;
```
Example gene name "Mycoplasma_agalactiae_gi|290752384|emb|CBH40355.1|". So splitting at second dash gives the species name.

All the best
David

**Comment by lilvyan** [comment]
I have the same requirements, but I have encountered obstacles in using script in 2.5.4 .
python3 OrthoFinder/scripts_of/resolve.py -h
Traceback (most recent call last):
  File "/home/lilvyan/OrthoFinder/scripts_of/resolve.py", line 7, in <module>
    from . import parallel_task_manager
ImportError: attempted relative import with no known parent package
I change the code "." to "home.lilvyan.OrthoFinder.scripts_of" or remove "from ." but get No module named 'package'
Is there anyone can give suggestion?
