### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by TonyMannion** [davidemms/OrthoFinder#407]
Hi,

I am having a similar issue... 

tonymannion@DESKTOP-DEQB4ST:/mnt/c/Users/antho/Desktop$ ./OrthoFinder/orthofinder -fg EHS/OrthoFinder/Results_Jun21/ -M msa

OrthoFinder version 2.3.12 Copyright (C) 2014 David Emms

2020-06-21 19:43:01 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mafft /mnt/c/Users/antho/Desktop/EHS/OrthoFinder/Results_Jun21/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "FastTree /mnt/c/Users/antho/Desktop/EHS/OrthoFinder/Results_Jun21/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok

Analysing Orthogroups
=====================
2020-06-21 19:43:04 : Starting MSA/Trees
Species tree: Using 1187 orthogroups with minimum of 96.4% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2020-06-21 19:44:50 : Done 0 of 1187
2020-06-21 19:46:13 : Done 100 of 1187
2020-06-21 19:47:30 : Done 200 of 1187
2020-06-21 19:48:51 : Done 300 of 1187
2020-06-21 19:50:02 : Done 400 of 1187
2020-06-21 19:51:10 : Done 500 of 1187
2020-06-21 19:52:16 : Done 600 of 1187
2020-06-21 19:53:24 : Done 700 of 1187
2020-06-21 19:54:24 : Done 800 of 1187
2020-06-21 19:55:23 : Done 900 of 1187
2020-06-21 19:56:27 : Done 1000 of 1187
2020-06-21 19:57:36 : Done 1100 of 1187
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1754, in main
  File "scripts_of/__main__.py", line 1511, in GetOrthologues
  File "scripts_of/orthologues.py", line 905, in OrthologuesWorkflow
  File "scripts_of/trees_msa.py", line 357, in DoTrees
  File "scripts_of/trees_msa.py", line 222, in CreateConcatenatedAlignment
  File "scripts_of/trees_msa.py", line 214, in ReadAlignment
  File "scripts_of/trees_msa.py", line 189, in __init__
IndexError: list index out of range
[25583] Failed to execute script orthofinder

One of the alignments in the Alignments_ids folder is blank (no data).  Is there any fix to this problem?

Thanks!
Tony

_Originally posted by @TonyMannion in https://github.com/davidemms/OrthoFinder/issues/220#issuecomment-647211466_

**Comment by davidemms** [comment]
Hi Tony

**Apologies, I missed the bit about the empty alignment file so you can skip past the first bit**

It looks like the most likely cause it that one of the MSA failed, I've not seen this before. Could you do the following in the OrthoFinder results directory
```
ls -lSc WorkingDirectory/Alignments_ids/ | tail
```
This will sort the MSA by size and print out the 10 smallest. Are any of the files empty? There is probably an empty file for an orthogroup which is also listed in `Species_Tree/Orthogroups_for_concatenated_alignment.txt`. Would you be able to attach the corresponding file from `WorkingDirectory/Sequences_ids/`. I think there is probably something wrong with the sequences in this file that has caused mafft to fail to produce the MSA, but currently I can't think what that might be.

In the meantime, I will edit the code so that it can skip over such problem alignments. It's probably also worth correcting whatever problem there was in the original sequence file so that you can successfully get a tree for that orthogroup.

All the best
David

**Comment by manniona** [comment]
Many thanks!

**Comment by davidemms** [comment]
Sorry, I hadn't planned to close the issue at this point. Do you happen to have the file from Sequences_ids/? I'm curious to know what made it fail and if there's anythiny I could do to prevent it.

Many thanks
David

**Comment by TonyMannion** [comment]
The alignments for OG0000364 did not have data.  I attached the corresponding file from Sequences_ids (I had to rename the file as .txt file because I could not upload .fa file)

[OG0000364.txt](https://github.com/davidemms/OrthoFinder/files/4831805/OG0000364.txt)

Thanks!

**Comment by davidemms** [comment]
Hi Tony

That's strange, I tried aligning the sequences and it ran without any problem. What happens if you run the command on your computer?
```
mafft --localpair --maxiterate 1000 --anysymbol OG0000364.txt > OG0000364.aln.fa
```
I can't see anything wrong with the sequences in the input file either so if it also runs fine on your computer it might just be wroth running the OrthoFinder command again.

All the best
David

**Comment by manniona** [comment]
I was able to complete a successful run on a different computer.  Thanks for looking into this!

**Comment by davidemms** [comment]
That's great, thanks for letting me know!
