### ISSUE TITLE
Question for interpreting *__v__*.tsv files

### ISSUE THREAD

**Issue by gpreising** [davidemms/OrthoFinder#409]
Hi David, 

I have a naive question about the OrthoFinder output in the /Orthologues/ directory, specifically the files in the form species1__v__species2.tsv. I assumed each row of this file would be its own unique orthogroup, but there are multiple rows with the same orthogroup value that have different genes in the species1 and species2 columns.

What does it mean for multiple sets of genes to belong to the same orthogroup? Can rows with the same orthogroup be collapsed into each other? 

Thanks, 

Gabe

**Comment by davidemms** [comment]
Hi Gabe

This part of the README file should be helpful: https://github.com/davidemms/OrthoFinder#orthogroups-orthologs--paralogs
Also the tutorial on interpretting the results: https://davidemms.github.io/orthofinder_tutorials/exploring-orthofinders-results.html

Basically, an orthogroup can contain many distinct sets of orthologs because there could have been gene duplication events within the orthogroup since its origin (at the last common ancestor of the species in your analysis) but before species 1 and species 2 diverged. Each of those duplicates could give rise to a separate set of orthologs.

All the best
David
