### ISSUE TITLE
Incorrect estimated species trees / user-specified option

### ISSUE THREAD

**Issue by RvV1979** [davidemms/OrthoFinder#41]
I ran Orthofinder on a set of species for which the phylogenetic tree is relatively certain. But the two alternative species trees that are estimated by OrthoFinder are both completely off the mark: There are two extremely closely related species in the data set and they are never sisters in the estimated trees. In addition, the true root node is never selected as such. This renders the orthogue assessments basically useless. 

Species tree estimation requires thorough phylogenetic analysis and usually this has already been done before. I strongly recommend allowing for a user-specified species tree (perhaps with polytomies in case some nodes are uncertain) and use that as a guide tree instead of estimating the tree based on blast clustering results.

**Comment by davidemms** [comment]
I'm sorry you had such problems with the orthologue inference. I'd recently developed an option for the user to provide a species tree to use and have now uploaded it. This is available in release version 1.1.2. I'll be able to add information to the manual on how to use this next week but as you already have an example of a species tree used by OrthoFinder you might be able to work it out anyway. By the way, with the new version (1.1.2) you have the option of restarting your analysis from the gene trees. This is the best thing to do since using a different species tree won't change anything prior to this point this. 

I appreciate that options such as these are very useful, however, this orthologue inference functionality is very new and so it'll still take a bit of time to add some of these extra options that give more advanced control.

All the best
David

**Comment by davidemms** [comment]
A description of the new functionality has been added to the OrthoFinder manual.

**Comment by RvV1979** [comment]
Thanks!
Op wo 30 nov. 2016 om 17:01 schreef davidemms <notifications@github.com>
