### ISSUE TITLE
Question about the performance of orthofinder and raxml-ng speed

### ISSUE THREAD

**Issue by Tdanis** [davidemms/OrthoFinder#413]
Hello again,

I have already run orthofinder for my analysis and its seems that something goes wrong. I have got 38 proteomes and now the analysis is in Raxml stage (raxml-ng). Orthofinder is been running for 41 days until now.

my command is :

##############
OrthoFinder2.3.12/orthofinder -S blast -M msa -T raxml-ng -b /previous_results/WorkingDirectory \
-f /Proteomes -t 20 -a 10
##############

the number of orthogroups from Orthogroups/Orthogroups.GeneCount.tsv file are ~24.400 and the number of Tree ids that have been done by now are 1136.

So, my question is how many it will take this analysis? could we run raxml-ng separately in order to speed up this part? 

If you want more information do not hesitate to ask me.

Thank you again for your support.

Thodoris

**Comment by davidemms** [comment]
Hi Thodoris

I've never run OrthoFinder with raxml-ng myself because I've always assumed raxml would be far too slow. Raxml will be running as fast as it can and so running it outside of OrthoFinder won't change that. 

If you've done 1136 trees then as a rough guess I'd say you're probably between 1/3 and 1/2 through. The first 1000 trees will take the longest as they are the largest (and starting them first ensures the best load balancing).

All the best
David
