### ISSUE TITLE
Error when estimating species tree with msa + IQTREE 

### ISSUE THREAD

**Issue by charlesfoster** [davidemms/OrthoFinder#416]
Dear David,

Thanks for the great tool.

I originally ran OrthoFinder with no issues with the following command:

`orthofinder -S mmseqs -t 8 -f /path/to/results/ 1>Orthofinder_Progress.txt 2>Orthofinder_STDERR.txt`

However, when I tried to re-run the analysis with IQTREE (as a comparison with the default dendroblast), it failed with an error after ~12 hours. The command I used was:

`orthofinder -S mmseqs -t 8 -fg /path/to/results_directory -M msa -A mafft -T iqtree`

The error message in Orthofinder_Progress.txt was: 
 
>OrthoFinder version 2.3.12 Copyright (C) 2014 David Emms
>
>2020-07-02 18:58:16 : Starting OrthoFinder
>8 thread(s) for highly parallel tasks (BLAST searches etc.)
>1 thread(s) for OrthoFinder algorithm
>
>Checking required programs are installed
>----------------------------------------
>Test can run "mafft /path/to/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
>Test can run "iqtree" - ok
>
>Analysing Orthogroups
>=====================
>2020-07-02 18:58:22 : Starting MSA/Trees
>Species tree: Using 5591 orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup
>
>Inferring multiple sequence alignments for species tree
>-------------------------------------------------------
>2020-07-02 19:53:03 : Done 1000 of 5591
>2020-07-02 19:05:27 : Done 0 of 5591
>2020-07-02 22:19:18 : Done 4000 of 5591
>2020-07-02 23:16:46 : Done 5000 of 5591
>2020-07-02 21:24:09 : Done 3000 of 5591
>2020-07-02 20:40:09 : Done 2000 of 5591
>
>Inferring remaining multiple sequence alignments and gene trees
>---------------------------------------------------------------
>2020-07-03 05:00:53 : Done 21000 of 43094
>2020-07-03 05:03:52 : Done 36000 of 43094
>2020-07-03 05:04:42 : Done 41000 of 43094
>2020-07-03 04:47:54 : Done 3000 of 43094
>2020-07-03 04:49:16 : Done 4000 of 43094
>2020-07-03 04:49:59 : Done 5000 of 43094
>2020-07-03 04:51:48 : Done 7000 of 43094
>2020-07-03 04:52:47 : Done 8000 of 43094
>2020-07-03 04:55:02 : Done 13000 of 43094
>2020-07-03 04:55:19 : Done 14000 of 43094
>2020-07-03 04:58:28 : Done 15000 of 43094
>2020-07-03 05:02:21 : Done 32000 of 43094
>2020-07-03 05:02:27 : Done 33000 of 43094
>2020-07-03 05:03:15 : Done 35000 of 43094
>2020-07-03 05:04:05 : Done 38000 of 43094
>2020-07-03 05:04:29 : Done 39000 of 43094
>2020-07-03 05:05:30 : Done 43000 of 43094
>2020-07-03 04:45:18 : Done 1000 of 43094
>2020-07-03 04:45:48 : Done 2000 of 43094
>2020-07-03 04:50:31 : Done 6000 of 43094
>2020-07-03 04:53:46 : Done 10000 of 43094
>2020-07-03 04:54:41 : Done 12000 of 43094
>2020-07-03 04:59:19 : Done 16000 of 43094
>2020-07-03 05:03:09 : Done 34000 of 43094
>2020-07-03 05:03:59 : Done 37000 of 43094
>2020-07-03 04:53:24 : Done 9000 of 43094
>2020-07-03 04:54:19 : Done 11000 of 43094
>2020-07-03 05:01:09 : Done 22000 of 43094
>2020-07-03 05:01:22 : Done 23000 of 43094
>2020-07-03 05:01:49 : Done 27000 of 43094
>2020-07-03 05:01:55 : Done 28000 of 43094
>2020-07-03 04:59:52 : Done 18000 of 43094
>2020-07-03 05:00:38 : Done 20000 of 43094
>2020-07-03 05:04:36 : Done 40000 of 43094
>2020-07-03 05:04:49 : Done 42000 of 43094
>2020-07-02 23:53:01 : Done 0 of 43094
>2020-07-03 04:59:35 : Done 17000 of 43094
>2020-07-03 05:00:09 : Done 19000 of 43094
>2020-07-03 05:01:29 : Done 24000 of 43094
>2020-07-03 05:01:35 : Done 25000 of 43094
>2020-07-03 05:01:42 : Done 26000 of 43094
>2020-07-03 05:02:01 : Done 29000 of 43094
>2020-07-03 05:02:07 : Done 30000 of 43094
>2020-07-03 05:02:14 : Done 31000 of 43094
>ERROR: Species tree inference failed
>ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

However, the STDERR file is empty - no other error messages to check. I looked at Log.txt in the Results directory, and I can see that:

>2020-07-02 18:58:17 : Started OrthoFinder version 2.3.12
>Command Line: orthofinder -S mmseqs -t 8 -fg /path/to/results_directory -M msa -A mafft -T iqtree
>
>WorkingDirectory_Base:  /path/to/results_directory/WorkingDirectory/
>FN_Orthogroups: /path/to/results_directory/WorkingDirectory/clusters_OrthoFinder_I1.5.txt_id_pairs.txt
>
>Species used:
>0: Species1.fa
>1: Species2.fa
>2: Species3.fa
>3: Species4.fa
>4: Species5.fa
>5: Species6.fa
>6: Species7.fa
>7: Species8.fa
>
>
>ERROR: An error occurred
>ERROR: Species tree inference failed

Do you have any idea of what might went wrong? Could it have run out of RAM? I requested 16GB and 100% of that was used.

Thanks,
Charles

edit: apologies for the way the output has pasted here
edit2: fixed up the commands

**Comment by davidemms** [comment]
Hi Charles

Yes, I think it's likely that it ran out of RAM. IQTREE can use a lot of RAM up just for a single tree, I've not really attempted any large analyses with IQTREE because of that. If you wanted to use IQTREE then you might need to get an idea for how much RAM it requires. You could try running it on the largest MSA, "WorkingDirectory/Alignments_ids/OG0000000.fa", and monitor how much RAM it's using after an hour maybe. If you wanted to run 8 in parallel ("-t 8" in the options) then 8 times this amount of RAM would probably be a safe upper limit. It could be that you require a few hundred GB, but that's just a guess.

In terms of checking what happened, you could also look at WorkingDirectory/Trees_ids/ and see which trees were & weren't successful. Also, the IQTREE .log files in WorkingDirectory/Alignments_ids/ may give some clues as to why IQTREE failed (if the log file is incomplete then it will have crashed or been terminated because of RAM). In fact, I think the log file say how much RAM is required first for the ModelFinder and then for the tree inference.  So this may contain the information you need about RAM usage, as long as it got to this stage before running out of RAM.

E.g. this small example tree requires 2MB for the ModelFinder and 0MB for the tree inference: [OG0000003.log](https://github.com/davidemms/OrthoFinder/files/4868774/OG0000003.log)


All the best
David

**Comment by charlesfoster** [comment]
Hi David, 

Thanks for the prompt reply, and for managing to parse the commands I used despite the near incoherent original post of mine - I've updated it for clarity. I've clarified now that I originally ran Orthofinder with no issues when using the original dendroblast-based pipeline. I'm hoping to use IQTREE for comparison, just to see if the support in the species tree changes.

The progress file has the following: "Species tree: Using **5591** orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup". However, when I check WorkingDirectory/Trees_ids/ there are **5618** trees. In WorkingDirectory/Alignments_ids/, there are **5635** alignments. The last file to be modified is , and it ends with this error:

`ERROR: Cannot write to file /path/to/Results_May20/../Results_Jul02/WorkingDirectory/Alignments_ids/SpeciesTree.model.gz`

Checking OG0000000.log, I can see that the last part printed is:

>Create initial parsimony tree by phylogenetic likelihood library (PLL)... 63.352 seconds
>Perform fast likelihood tree search using LG+I+G model...
>Estimate model parameters (epsilon = 5.000)

So, I'm guessing this is where it ran out of RAM and died. There's a huge number of genes in this orthogroup. I'll try running the analysis again with a huge RAM allocation (lucky the cluster is decent). If that fails, I guess I'll try raxml or fasttree.

Thanks again,
Charles

**Comment by davidemms** [comment]
Hi Charles

If it's only the species tree you want to run IQTREE on rather than all the gene trees then that is far easier. There will already be the concatenated MSA in teh results directory from your first analysis: 
```
MultipleSequenceAlignments/SpeciesTreeAlignment.fa
```

You just need to run IQTREE on this!

If the topology of the resulting species tree is different from before and you decide you want to use this one in your analysis instead then you can repeat the ortholog inference step using this new species tree (after you have rooted it!). Just run
```
orthofinder -ft PREVIOUS_RESULTS_DIR -s new_species_tree.tre
```

All the best
David

**Comment by davidemms** [comment]
**Correction to the above comment.** The analysis you need to run first is:
```
orthofinder -t 8 -fg /path/to/results_directory -M msa
```
(the important option here is the '-M msa')

This will do the alignment with MAFFT and the trees with FastTree. Then you can follow the suggestion in the previous post to do your species tree with IQTREE.

I think this is a really useful workflow, I will try and highlight this option somewhere.

Thanks
David

**Comment by charlesfoster** [comment]
Thank you for the useful tips! I'll be sure to try it out soon.

Cheers,
Charles
