### ISSUE TITLE
Adding species with the -b option creates new nested working directory.

### ISSUE THREAD

**Issue by ryandward** [davidemms/OrthoFinder#417]
According to the wiki, I should be able to use the `-b` switch to add new species by pointing OrthoFinder to a previously computed working directory.

The problem is that the output then becomes deeply nested into that file structure. For instance:

`orthofinder -1 -b Orthofinder/Results_Jul03/WorkingDirectory` processes results, and places them into a new directory:
`Orthofinder/Results_Jul03/WorkingDirectory/OrthoFinder/Results_Jul03/WorkingDirectory`

Is there a switch I can use to prevent this nesting?

**Comment by davidemms** [comment]
Hi 

If you're adding to a previous analysis then you won't be able to use a completely different output directory since OrthoFinder needs to be able to keep track of the previous files. You can have the new directory alongside the previous results directory though:
```
orthofinder -b ExampleData/OrthoFinder/Results_Jul07/ -f new_proteomes
```
Will create the directory alongside the previous one: `ExampleData/OrthoFinder/Results_Jul07_1/`

You can also name it to help remember which results directory is which:
```
orthofinder -b ExampleData/OrthoFinder/Results_Jul07/ -f new_proteomes -n Extended_Analysis
```
gives  `ExampleData/OrthoFinder/Results_Extended_Analysis/`

All the best
David
