### ISSUE TITLE
Failed to execute script orthofinder

### ISSUE THREAD

**Issue by Tdanis** [davidemms/OrthoFinder#419]
Hello , 

I am trying to run this command OrthoFinder2.3.12/orthofinder -S blast -b /previous/Blast_results -f /new/Proteome -t 20 -og

and I have already commented the some species in SpeciesIDs.txt , and the error that prints out is ,

*********************

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1690, in main
  File "scripts_of/__main__.py", line 1394, in ProcessPreviousFiles
TypeError: cannot concatenate 'str' and 'list' objects
[10274] Failed to execute script orthofinder

*********************

Could you help me please?

**Comment by davidemms** [comment]
Hi

Thanks for reporting this. The problem is that the Species*fa files are missing from your "/previous/Blast_results" directory. Unfortunately there's a bug in the code so the error message didn't get reported properly. The required files are:

```
Blast0_0.txt.gz
Blast0_1.txt.gz
etc....
Blast3_3.txt.gz
SequenceIDs.txt
Species0.fa
Species1.fa
Species2.fa
Species3.fa
SpeciesIDs.txt
```

I'll fix the error messaging in the next release.

All the best
David

**Comment by Tdanis** [comment]
Thank you very very much.
