### ISSUE TITLE
Not removing Species

### ISSUE THREAD

**Issue by Tdanis** [davidemms/OrthoFinder#420]
Hello again, after the previous issue now I am facing another error.

My command is this:
/mnt/big/Orthology/OrthoFinder2.3.12/orthofinder -S blast -b /previous/Blast_results -f /new/Proteome -t 20 -og

So into the previous blast results exists the SpeciesIDs.txt , in which I commented some species.

##########
29:species.fa
**#30:species.fa**
31:species.fa
########

and after blast, the file is the same , with the new species appended at the end of the file.

But still into the new Workingdirectory there are Blast resulst between the new species and the commended. 

Is this wrong? because the comment is useful in order to gain computantional time from previous blast results.

**Comment by davidemms** [comment]
Hi 

Yes, that's the intended behaviour. The problem is that a user could comment a species X out while adding a species Y and then do another analysis commenting X back in while adding a species Z. In that case the X-Y results would be required. Because of this I opted for the behaviour you've noted even though in some cases the computational cost would be higher.

All the best
David
