### ISSUE TITLE
What is the duplication support value in Duplication.tsv?

### ISSUE THREAD

**Issue by GGSonoda** [davidemms/OrthoFinder#422]
Dear David

I have been using Orthofinder for the orthologues inference and genetic duplication identification on toxin evolution, but I came across a doubt about the genetic duplication identification methodology. The output "Duplication.tsv" has a column containing support values ranging from 0 to 1. I was not able to find detailed information for how such value is calculated. I understand it has something to do with the proportion of expected and observed taxa which descend from a given node, but how such values are inferred? I am wondering what would be its biological meaning and if this could be used as a confidence measure of the duplication event. This would really help us to understand the molecular processes  behind the toxins sequence evolution in our taxonomic group.
Thanks in advance,
Gabriel Sonoda, Undergrad student from University of São Paulo

**Comment by davidemms** [comment]
Hi Gabriel

It is the proportion of species for which both copies of the duplicate are present compared to the expected number given the node in the species tree that the duplication event has been mapped to. 

Yes, I would say that in general It could be used as a confidence measure but it's important to remember that it's value could be lower than 1 in many (most?) cases simply because of subsequent gene loss rather than low confidence. Once you have two copies of a gene then you should be fairly certain a gene duplication event has occurred, but there could be uncertainty concerning on which branch of the species tree it occurred. Once the value is above 50% I would guess that in most circumstances you would be reasonably confident in it.

All the best
David
