### ISSUE TITLE
orthofinder -ft run ends before completion, no error messages are shown

### ISSUE THREAD

**Issue by assafwww** [davidemms/OrthoFinder#424]
Hi David,

I'm trying to use the Orthofinder.2.3.12 conda version, with -ft option (the exact steps are detailed below).
The Orthofinder run completed after ~1min with no error messages, and the standard output/error doesn't indicate any errors: "Done OF Orthologues... Writing results files... results:.... citation...".
Yet I can see that in the "Orthologues" directory that the species pairs csv files have only 0-5 lines (usually I see around 5,000-15,000 lines), and no rooted/reconciled trees are created. 

**the details:**
**1)** based on previous orthogroups data created with the same  Orthofinder.2.3.12 conda version, I successfully ran orthofinder fasttree option:

`orthofinder -fg "$blastDir/OrthoFinder/Results1" -t 54 -a 54 -M msa -s $speciesTree`

this apparently gave the correct output, which was saved in "$blastDir/OrthoFinder/Results2".

**2)** Then based on the ""$blastDir/OrthoFinder/Results2/WorkingDirectory/Alignments_ids" output of stage 2, I created new gene trees based on iqtree.
The new trees are standard newick trees with the same names as before, e.g. "OG0006921_tree_id.txt"

**3)** The new trees were saved in "$blastDir/OrthoFinder/Results1/WorkingDirectory/Trees_ids", and the older "WorkingDirectory" was renamed to "WorkingDirectory-old"
the file "$blastDir/OrthoFinder/Results1/Log.txt"  was edited this file to point to the path of the new trees

`orthofinder -a 20 -t 20 -ft ""$blastDir/OrthoFinder/Results1" -s "$species_tree"`

**another note:**
I tried to repeat this by using the fasttree "Trees_ids" directory from stage 1, but got the same issue, so I assume it's not a problem with my input trees data of stage2.

thanks in advance,
Assaf

**Comment by davidemms** [comment]
Hi Assaf

As I understand it you would like to trick OrthoFinder into inferring orthologs from trees you've inferred externally using IQTREE? I think the simplest way to do this that should probably work is just to replace the Trees_ids/ directory with the iqtree versions of the trees with the same filenames as in the original Trees_ids/ directory. Then run OrthoFinder with `-ft OrthoFinder/Results_dir`. I wouldn't suggest editing the log file.

All the best
David

**Comment by assafwww** [comment]
Hi David,
yes, I ran Iqtree externally on a gird. 
From what i see, Orthofinder reads the Log.txt file, and tries to locate the lines: "WorkingDirectory_Base:", "FN_Orthogroups:" ,"WorkingDirectory_Trees:", yet the directory used in the first run above (-fg Results1) doesn't include trees building and therefore the line "WorkingDirectory_Trees:" is missing, so it fails without adding this line. Yet after adding the line,  it's difficult to understand what goes wrong since the run ends with no complains.
Assaf

**Comment by davidemms** [comment]
Hi Assaf

I can't provide any assistance if you're editing the Log.txt file as that isn't supported functionality & no promises are made about OrthoFinder's behaviour if it is edited. My suggestion for using a different set of trees would be to try replacing the trees in the $blastDir/OrthoFinder/Results2/WorkingDirectory/Trees_ids/ and not make changes to the Log.txt file or directory names.

All the best
David

**Comment by assafwww** [comment]
thanks David,

based on your recommendation, I just replaced the Tree_ids directory created previously (in "Results2" directory)
by the new one (the iqtree trees directory), without touching anything else, and then called `orthofinder -ft $blastDir/OrthoFinder/Results2 -a 20 -t 20 -s $specieTree`.
Orthofinder completed successfully and I think gave the expected data tables results in directories:

```
Comparative_Genomics_Statistics
Gene_Duplication_Events
Orthologues
Phylogenetically_Misplaced_Genes
Putative_Xenologs
Resolved_Gene_Trees
Species_Tree
WorkingDirectory
```

One directory seems missing, "Gene_Trees". I think it should be created in the new run since it includes rooted trees that could not be created by iqtree. 
Another thing is that based on the cpus usage, and the order of files created, the program did not work in parallel, but still the total runtime was ~2h, which is reasonable.

thanks a lot,
Assaf

**Comment by davidemms** [comment]
Hi Assaf

Yes that's right, manually changing the Tree_ids/ directory isn't part of OrthoFinder's workflow so it doesn't know to create a new Gene_Trees/ directory. 

The step is currently serial. The parallelisation of this step is complex since the gene tree files are orthogonal to the orthologs files and also it doesn't contribute a large amount to the run time. I have investigated parallelisation and might be able to develop something in the future.

All the best
David

**Comment by davidemms** [comment]
There's a script in the tools directory, "OrthoFinder/tools/convert_orthofinder_tree_ids.py", which will replace the IDs with sequence names for the files you created and put in "Trees_ids/":
1. Download the "OrthoFinder_source.tar.gz" package from the releases page: <https://github.com/davidemms/OrthoFinder/releases>, extract the files.
2. `cd OrthoFinder_source`
3. Run the script with option "-h" to see the help file: `python tools/convert_orthofinder_tree_ids.py -h`
4. Run it on your files `python tools/convert_orthofinder_tree_ids.py /PATH/TO/FILES/Trees_ids/ /PATH/TO/FILES/SequenceIDs.txt /PATH/TO/FILES/SpeciesIDs.txt`

**Comment by assafwww** [comment]
thanks a lot, the reason I'm asking this is that the trees in the Resolved_Gene_Trees directory do not include branch support values, while the trees in Tree_ids are unrooted, and both types of information are helpful for me.
Which brings me to ask: are the structure of the input unrooted trees the same as that of the output rooted trees, except for the rooting operation, or that some additional structure manipulations are made (e.g., by  DLCpar)?

thanks again,
Assaf

**Comment by davidemms** [comment]
Hi Assaf

Sorry for the delay in replying, no the topology can be different, and often will be. Here's the process:

1. Trees_ids: unrooted gene trees direct from the tree inference program
2. Gene_Trees: these trees rooted and with the IDs replaced
3. Resolved_Gene_Trees: these trees with some topological rearrangements made to make them more parsimonious accoriding the the hybrid species-overlap/DLC algorithm implemented in OrthoFinder and with node labels instead of support values.

There are scripts in version 2.3.7 of OrthoFinder (sorry about the requirement for a specific version) which will 1) replace the IDs with gene names and 2) root the trees for you from Trees_ids.

1. **Replace gene IDs**: tools/convert_orthofinder_tree_ids.py takes a gene tree with IDs (I think a single one rather than a directory) the SequenceIDs.txt file and the SpeciesIDs.txt file and replaces the IDs with the species and gene names.

2. **Root gene trees**: scripts/resolve.py will take a rooted species tree and a directory of gene trees. It'll write out a file called FILENAME_rooted.txt for each file (it'll also do the resolved trees to but you can ignore them)

All the best
David
