### ISSUE TITLE
No trees for OG < 4 sequences

### ISSUE THREAD

**Issue by abretaud** [davidemms/OrthoFinder#433]
Hi,
I have run OrthoFinder on a set of ~20 proteomes, and got 30556 orthogroups. My problem is that I only find 18714 trees in the `Gene_Trees` directory, and looking at `Orthogroups/Orthogroups.tsv`, those 18714 groups are the ones with more than 3 sequences.
Is there a specific reason why there are no trees generated for the smaller groups? Is there a way to get them? I tried to rerun with `-fg -M msa`, but didn't get more trees.

I launched orthofinder (2.4.0) like this: `orthofinder -t 20 -S diamond -f data`

**Comment by davidemms** [comment]
Hi

That's the expected behaviour. It's because the smallest non-trivial unrooted tree requires 4 sequence, consequently most tree inference algorithms will not infer a tree with fewer than 4 sequences either. 

If you wanted to try and get trees you could try the MSA files for the groups with 3 sequences in different tree inference programs and see if any will infer trees for you, I don't know off the top of my head if any do or not.

All the best
David

**Comment by abretaud** [comment]
Ok it makes sense, I suspected something like this. Thanks for the answer :)
