### ISSUE TITLE
Diamond Blast taking too long

### ISSUE THREAD

**Issue by MCH74** [davidemms/OrthoFinder#441]
Hi,
I'm running OrthoFinder v2.3.12 on ten proteomes, using 20 cores. All 100 blast files, Blast<x>_<y>.txt.gz, have been produced but no additional output has been produced for several days.
Strangely, 4 diamond blast process are running in duplicate, whereby one of each is in sleep status and the other is actively running. These processes are 1v1, 6v6, 8v8 and 9v9.
I've restarted the whole job in parallel and it is again stalling in the same place.
Any ideas?
Thanks,
Mark

**Comment by davidemms** [comment]
Hi Mark

I think that DIAMOND creates the files at the start and then populates them at the end so the first thing to check is if any of them are empty (`ls -lct`). Possibly the final ones have been started but not finished yet. I suspect the pairs of processes is just how diamond manages the work. 

How many sequences are there for each species (run `grep -c Species*fa` in the WorkingDirectory)? It is best to select the transcript variant for each gene if this is possible which will usually mean you have between 5000 and 30000 sequences per species. As well as number of sequences affecting the time, the self-self searches could well take longer because you're guaranteed that each sequences will have at least one full length alignment to infer. 

So I think it's just a matter of leaving it to finish, or reducing the number of sequences if that's excessive. A runtime of a few days for a single species-species diamond run does sound unexpected though, each Blast_.txt.gz should only take a few minutes normally. What did the `ls -lct` command tell you about the distribution of completion times of each of the non-empty Blast_.txt.gz files? You should expect them to come in at fairly regular intervals.

All the best
David

**Comment by MCH74** [comment]
Hi David,

Thanks for your comments and tips.
I did remove all isoforms from the proteome files beforehand which then contained between 13k and 18k sequences.
I have since repeated the process with the latest orthofinder version 2.4.0. Again, almost all blast files were created and apparently completed within a few minutes. However, 6 single species files are still empty, and the diamond processes have been running for nearly 24 hrs.
The original run has been running for 4 days, with 4 blast files still empty.
Maybe I just need to be patient?

Thanks,
Mark

**Comment by davidemms** [comment]
Hi Mark

I think there's something odd going on which is causing it to take a long time, but just waiting for it to finish is probably the easiest and that's probably what I'd chose to do.

Other options would include:
* You could try and run these commands yourself outside orthofinder (with more parallel threads e.g. run one at a time with '-p 20'). Then copy these files into the orthofinder WorkingDirectory and use the orthofinder '-b' option to run from the completed blast files.
* It could be that there are certain sequences or families of sequences that are causing the problems and so you could investigate what these are. Are there sequences in these species that are unexpectedly long? Or repetitive? You could try cutting the files into chunks and investigating if a particular chunk of the file is the one that takes a really long time and in that way identify the sequences that are responsible.

All the best
David

**Comment by MCH74** [comment]
Hi David,

I have checked the files and see that I had a systematic error in the generation of the original fasta files. After correcting them it should work.

Thank you for your time,
Mark
