### ISSUE TITLE
dealing with isoforms

### ISSUE THREAD

**Issue by krishnam** [davidemms/OrthoFinder#443]
Hi David,
In transcriptomic studies it is common to take longest isoform and proceed for analysis ie., each gene represented by one single protein.
At proteome level, do we have to cluster the proteins (and take longest protein of that gene) before attempting orthofinder - is there any known advantage of doing it ? In otherwords how does presence of multiple proteins (isoforms) from same gene level affect the analysis, especially in computing Single Copy Orthologs amongst species, especially when proteins (from same gene) are more or less similar. 
I see other similar programs (proteinortho) do consider if the sequences are from isoforms or not.

**Comment by davidemms** [comment]
Hi

Yes, I would take the longest isoform for a number of reasons:
* All the gene duplication events identified will be true duplicates rather than different transcript variants
* Orthologs will be calculated at the gene level, which is the correct approach.
*You will correctly identify single copy orthologs
* The time saving is large when using just the longest transcript variants

All the best
David
