### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by rsk222** [davidemms/OrthoFinder#45]
Hello,
Sorry for what is surely a very basic question. I am trying to install OrthoFinder on a Mac running Sierra and have only managed to get as far as trying to test if I can run the program. When I enter OrthoFinder-1.1.4/orthofinder -h, I get an error message saying "cannot execute binary file." Is there anything I can do about this, or is this just due to the fact that I am running a mac and not linux?
Thank you!

**Comment by mthon** [comment]
You probably need the _source.tar.gz version.  the other one is precompiled for linux.

**Comment by rsk222** [comment]
Thanks for your reply! I suspected that something like this was occurring based on what I could find from Googling, but the instructions made it seem like the file would run on either Linux or Mac so I wanted to see if it was something I was doing wrong.

**Comment by dieunelderilus** [comment]
Hello
Did you solved   this problem ? I am facing a similar problem, but the proposed solution here just not solving  my issue. I am trying to install Orthofinder on my mac (sierra) .  I downloaded  and unzipped the “OrthoFinder-2.0.0.tar.gz”  file. When I run “OrthoFinder-2.0.0/orthofinder –h” I get an error message saying  "cannot execute binary file”. When I try the source_tar.gz version (OrthoFinder-2.0.0_source.tar.gz, I can’t run ‘OrthoFinder-2.0.0_source/orthofinder  -h’ because Orthofinder is not a script but  a  directory with a lot of python scripts inside. Please, is this  a  common problem ?  what is the better alternative  to get orthofinder running in my Mac ?
Thank you in advance for your assistance 

Dieunel

**Comment by davidemms** [comment]
Hi

You can run the source code version like a normal python script:
`python OrthoFinder-2.0.0_source/orthofinder/orthofinder.py -h`

All the best
David

**Comment by Imaweirdo1293** [comment]
I have a similar question.  I'm trying to play a game I bought and it doesn't work because it says DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_5_0': The specified module could not be found.  It also had some instructions of where to go so I did it.  I double clicked on FirebaseCppApp-6_5_0 and it said I had to choose and application to open it with.  I chose Terminal and when I opened it up, it said -bash cannot execute binary file and a couple other things.  I know his might be the wrong website to post this on but I need help.
