### ISSUE TITLE
Does orthoFinder care about uneven protein lengths?

### ISSUE THREAD

**Issue by soungalo** [davidemms/OrthoFinder#464]
Hello,

While QA-ing results of an orthoFinder run, I noticed that in some cases proteins of rather different lengths are clustered within the same orthogroup. This happens for example when the sequence of one protein is contained within the sequence of another ([here is an example](https://www.ebi.ac.uk/Tools/services/web/toolresult.ebi?jobId=emboss_needle-I20201006-084144-0757-59301870-p1m)).
To assess the frequency of such cases, I calculated for each orthogroup the ratio between the longest and shortest sequences. I found that out of 26,644 orthogroups, 4,946 (~18%) had a max/min ratio > 1.5.
As far as I understand, orthoFinder does not take the difference between protein lengths into account when clustering since it uses (normalized) bit scores generated by DIAMOND/BLAST. Since these alignment software don't care about unaligned regions when calculating the bit score, they simply have no effect on orthoFinder. Am I correct about that? Maybe there is some other mechanism that considers uneven protein lengths? How will this affect the MSA step?
In general, I'm not sure if this should be considered a problem, but I think that it is a bit strange to call a 500-aa and a 300-aa proteins orthologs, especially in closely related species.

I would appreciate hearing your thoughts on this - would you say there is an issue here? If so, can you help me think of solutions or workarounds? I thought about applying another normalization to bit scores that would account for the difference in length. Something like:
`B' = B * min(qlen,slen)/max(qlen,slen)`
where B' is the normalized score, B is the bit score, qlen is the query length and slen is the subject length.
Also found [this paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0625-x) which suggests some interesting metrics that may be relevant.
Does this make sense to you? and is there an easy way to apply this without modifying OrthoFinder code?

Thanks a lot!

**Comment by davidemms** [comment]
Hi Lior

OrthoFinder is concerned with orthology and phylogenetic relationships between genes. Orthologs may tend to have length ratios less than 1.5 as you suggest, or they may not. That is an empirical question that you would have to assess, it sounds like an assumption which might not be true in general. The way to tell for certain is to construct the gene tree and examine that. 

Ultimately, a pair of genes are orthologs **if and only if** they diverged from a single gene in their last common ancestor. For each pair of genes that OrthoFinder says are orthologs you can check the gene tree it analysed to see the evidence it has. I think the only thing which should convince you otherwise is if you infer yourself a better gene tree which says differently. If the sequences are 300-aa or 500-aa isn't really important. 

All the best
David
