### ISSUE TITLE
Restarting Orthofinder with a subset of orthogroups after blast search

### ISSUE THREAD

**Issue by MEleonoraRossi** [davidemms/OrthoFinder#465]
Dear David,

I would like to restart Orthofinder from the -fg option, but with a smaller subset of the orthogroups that it found. I made a folder containing all the OGs with at least 50% of species present. I put this folder into the results folder that the software gave me and the working directory but I get an error  "ERROR: cannot find files from OrthoFinder run in the directory:
   /ar/ana/Eleonora/aa_to_use/OrthoFinder/Results_Jun18/OrthogroupsAtLeast50Species/" 
My question is, there is a way to trick orthofinder to look into that directory and use only the subset? 

Thank you very much for your help

**Comment by davidemms** [comment]
Hi 

I can see the utility of this, but at the moment there isn't an functionality to do it. 

I've had a play around though and I think it can be achieved by editing the file `WorkingDirectory/clusters_OrthoFinder_I1.5.txt_id_pairs.txt`:

- delete the line for each orthogroup you don't want, keeping count of how many you delete, amking sure you delete all lines if the orthogroup is on multiple lines.
- On the penultimate line of the file subtract however many orthogroups you removed from the left most number (OrthoFinder examines this as a sanity check).

E.g. if you deleted 10 orthogroups and the file ends like this:
```
1134      3_670 $
)
```
then edit it so that it reads
```
1124      3_670 $
)
```

It's a bit of a hack, but it'll do what you want. Note that any resulting files will now refer to orthogroups with recalculated numbers according to their position in the file (counting from 0), not the now no longer correct orthogroup numbering given by the numbers on the left hand side in the clusters_OrthoFinder_I1.5.txt_id_pairs.txt file.

If you need to see them, the translations from the sequence IDs OtherFinder uses to the sequence names are in `WorkingDirectory/SequenceIDs.txt`. However, it may be easier to use the left hand numbers in the clusters_OrthoFinder_I1.5.txt_id_pairs.txt file, which refer to the original orthogroup numbers.

All the best
David

**Comment by davidemms** [comment]
I've just answered a related issue and thought that the workaround I suggest at the end could potentially be appropriate for your case too: https://github.com/davidemms/OrthoFinder/issues/467#issuecomment-707242844
