### ISSUE TITLE
Different orthogroups results generated from orthofinder

### ISSUE THREAD

**Issue by LiuKe98** [davidemms/OrthoFinder#471]
Hello everyone,
I'm using Orthofinder to find the single copy orthogroups for positive selection analysis. I had got the results from 5 species proteome.  But later I found one gene named hoxb5 was not annotated in one geome. Then I add it and run orthofinder again. As I expected, there would be one different orthogroups in two results. But the orthogroups numbers and gene numbers in many orthogroups and Singlecopy gene orthogroup numbers are  all slightly different  from previous results. For example, I found that two single copy orthogrops were clustered in the second run.  Do you know why?
Thanks a million!
LiuKe

**Comment by davidemms** [comment]
Hi LiuKe

This is expected behaviour, it largely results from the Markov clustering step (using MCL). This is effectively a local-global algorithm on the graph of all genes that is used to determine orthogroup membership and small changes such as new genes can have knock-on effects.

The best thing to do is to always use the orthogroups determined using gene trees which is available in the latest release of OrthoFinder. I.e. Use `Phylogenetic_Hierarchical_Orthogroups/N0.tsv` instead of `Orthogroups/Orthogroups.tsv` since the gene trees are a more accurate & reliable method of determining how the genes are related.

All the best
David

**Comment by LiuKe98** [comment]
Dear David

Thanks for your reply. That is really helpful.

Thanks a million!   
LiuKe
