### ISSUE TITLE
"same species" proteomes in a larger taxon set

### ISSUE THREAD

**Issue by dandaman** [davidemms/OrthoFinder#48]
Hi David,

first of all thank you for your continued effort into this excellent tool!

I need to infer gene families for a larger taxon set that also comprises several taxonomically dispersed cases where I have proteomes from two/three isolates/strains of one species (e.g. maize B73/PH207). I am worrying that they might end up in a lot of "lineage specific" clusters like I observed in my last run when I accidentally included two different annotation versions of the same species. Is this a behavior you'd expect? If so is there any means to circumvent/improve it?

Best,
Daniel

**Comment by davidemms** [comment]
Hi Daniel

I would suggest just trying it. I'd hope that you wouldn't get too many lineage specific clusters, at least not more than you would get 'orphan genes' if you only had one species in the lineage rather than a cluster of species. 

I think the clustering is to be expected to some extent although I would be interested to know if you observe such clusters but had reason to believe that they should be part of other larger orthogroups instead.

All the best
David

**Comment by dandaman** [comment]
Hi David,

thanks for the quick response - I'll let you know how it turned out.

Best,
Daniel

**Comment by davidemms** [comment]
Hi Daniel

I'd be quite interested to know how this turned out if you got round to trying it? Were there cases were you got lineage-specific clusters when, in fact, the genes in these clusters were actually orthologues of genes in other separate clusters? I plan to do some work at a later point which would look at any issues that users are experiencing with splintered or merged orthogroups and so it'd be interesting to know if this use-case led to problems like that?

All the best
David
