### ISSUE TITLE
[Question] Order of the sequences in each `Single_Copy_Orthologue_Sequences` file

### ISSUE THREAD

**Issue by matrs** [davidemms/OrthoFinder#481]
For each file inside `Single_Copy_Orthologue_Sequences`, are the sequences ordered as  the source/input files? , I'm referring to  the order of the input files seen in the `Log.txt` file: 

```terminal
Species used: 
0: GCF_000153905.1_ASM15390v1_genomic.faa
1: GCF_000157975.1_ASM15797v1_genomic.faa
2: GCF_000484655.1_ASM48465v1_genomic.faa
.....
```

Checking with a quick line in the terminal seems to say that it's the case, but is this guaranteed for all `Single_Copy_Orthologue_Sequences` files?

**Comment by davidemms** [comment]
Hi

If they are then I think it's by chance, it's not something intentional and so could potentially change.

(Full details: Every sequence in orthofinder is given an id e.g. "5_1784" where 5 is the ID for the species and 1784 is the ID for the sequence within the species. These strings are put in a set and so their order depends on the order python iterates through this set. I don't know what method it uses to determine this. If it's alphabetical then 13_ might come before 2_.)

All the best
David

**Comment by matrs** [comment]
Thank you very much for your response, I just wanted to avoid writing some code, but now I know I have to write it.
