### ISSUE TITLE
Variation in Duplications.tsv (between runs with 1 fewer species)

### ISSUE THREAD

**Issue by peanut-buddy** [davidemms/OrthoFinder#484]
Hello!

I ran OrthoFinder on a set of 33 species. Following this, I removed one very distantly related species and re-ran the analysis. I used annotated genes to identify orthogroups of interest and am analyzing the same orthogroups as before in the second run.

I noticed, unexpectedly, that one of the annotated genes was absent from Duplications.tsv, so I compared the output between runs. The output for Duplications.tsv was different, though the species I removed was previously not in this orthogroup. I compared the orthogroups using Orthogroups.txt and identified in both runs, the annotated gene and many of the same genes I recovered previously. I am unsure why the annotated gene and many others from the orthogroup were not present in the second run of Duplications.tsv, as they were previously. Is this variation to be expected?

Thank you for your guidance, I greatly appreciate it!

**Comment by davidemms** [comment]
Hi

Was the species you removed the outgroup species? The orthogroups are defined at the phylogenetic level corresponding to the last common ancestor (LCA) of your species so if removing the species has changed the LCA then you should expect your orthogroups to be different.

Regardless of this, if you wanted to investigate your specific duplication event I'd suggest looking at the gene tree referenced in the Duplications.tsv file. You can compare the tree from before and after to see what the differences are. 

Are genes in one tree and not the other? If so you can shoes the genes you should be present in the tree and re-infer a new tree.

Are the differences due to one of the trees selecting a different topology for the genes? If this is the case you can analyse the two trees and see which one you trust the most, and potentially infer a tree yourself for these genes to clarify the situation.

All the best
David

**Comment by peanut-buddy** [comment]
Thank you for your response! To answer your first question, the genes are in one tree but not the other so I could re-infer the tree. Thank you for clarifying this for me. I appreciate your time!
