### ISSUE TITLE
Can orthofinder use user defined outgroup when infer Species Tree?

### ISSUE THREAD

**Issue by uyghbo** [davidemms/OrthoFinder#489]
Hi, davidemms
When I was running orthofinder I got a rooted species tree which i thought the outgroup inferred by STRIDE was unexpected . So I wander if Orthofinder can use user defined outgroup when infer Species Tree?

And I also found that sometimes the Species_Tree dir got a Potential_Rooted_Species_Trees dir while sometimes not. How did this happen？Can Orthofinder result Potential_Rooted_Species_Trees dir every time？I think this dir was very useful and can get my expected rooted Species Tree.

All the best
uyghbo

**Comment by davidemms** [comment]
Hi uyghbo

Sometimes there is not enough data to correctly root the species tree. You can provide your own rooted species tree to OrthoFinder in newick format using "-s SPECIES_TREE_FILE" if you do this, you only need to re-run the last step, which is very quick, so the full command will look like this:
```-ft PREVIOUS_RESULTS_DIR -s SPECIES_TREE_FILE```

Because you can provide the species tree yourself that means you can use one in the Potential_Rooted_Species_Trees directory or set the outgroup yourself on an existing tree (e.g. using Dendroscope). The Potential_Rooted_Species_Trees is only generated if OrthoFinder thinks there are multiple trees that are all equally probable.

All the best
David
