### ISSUE TITLE
Too many orthogroups?

### ISSUE THREAD

**Issue by ViriatoII** [davidemms/OrthoFinder#495]
Hello,

When using Whole Proteomes, is there a normal proportion of orthogroups (HOGs) in relation to the proteome sizes? 

Each of my proteomes has 30-50k proteins but my final N0 orthogroups are 46k. Half of these HOGs only have genes in 1-3 species, which I was not expecting since it's species from the same familly ( _Brassicaceae_ ). I'm putting here two boxplots of the distribution of the Gene n° per HOG per species.

For all HOGs (46 thousand):
![new_genes_per_HOG_per_species](https://user-images.githubusercontent.com/25958099/104839417-4ab15480-58c1-11eb-9b80-851bee1b0213.png)

For only HOGs with > 3 species present (26 thousand):
![new_genes_per_HOG_per_species_filtered_more_than3](https://user-images.githubusercontent.com/25958099/104839546-138f7300-58c2-11eb-9206-47e5795c5366.png)

My Orthofinder used blast, -M msa and already a superclustering -I of 1.3. 

The inputs proteomes have been created with automatic genome annotation, which could generate some trash genes that create unique HOGs, but I was very careful with my method: I used the same protein evidences to annotate all species, filtered out proteins with low annotation quality, controlled for good BUSCO scores.

Is all of this normal? Maybe still many input trash genes?

Kind regards,
Ricardo

**Comment by davidemms** [comment]
Hi Ricardo

I think this sounds quite normal. I think perhaps looking at what percentage of genes from each species are in a HOG N0 would be informative. And also what proportion of genes from each species are in an orthogroup (N0.tsv again) with 100% of species present, 75% of species present & which with 50%. I think this might be useful because it answers the question, are genes being put in complete orthogroups. It also addresses whether the patterns you are seeing could be due to gene duplication and loss events.

All the best
David

**Comment by ViriatoII** [comment]
Thanks!  There were some species specific HOGs, especially in more distant species and in species with low quality/high heterozygosity assemblies.
