### ISSUE TITLE
Feature request: sequence files of Hierarchical Orthogroups

### ISSUE THREAD

**Issue by RyanPendavingh** [davidemms/OrthoFinder#503]
Hi David,

I was wondering if you could add the sequence files of the Hierarchical Orthogroups to the output of OrthoFinder.

Thank you

**Comment by davidemms** [comment]
Hi 

Thanks for asking about this, I've got it planned for an upcoming release. The plan would be for a script that would create for you, on request, all the sequence files for a specified set of Hierarchical Orthogroups e.g. the N5 orthogroups. It would be 'on request' because the number of files and amount of disk space could cause problems for a lot of users if they were created automatically at every single level. The script would also work with the alignment files if required too. Does this sound like an ok solution? I should be able to submit the a version of the script to github next week, so you'd be able to try it out then.

All the best
David

**Comment by RyanPendavingh** [comment]
That would be awsome! Will you be adding the statistics of the HOGs as well in the upcoming release?

**Comment by davidemms** [comment]
Hi Ryan

If you pull the latest version of the code from the master branch there is a script called `tools/create_files_for_hogs.py` that will create the FASTA files. I'll have to look into the statistics later.

Best wishes
David

**Comment by HENdavid** [comment]
Hi David,

I find this option very useful but not sure how to run it. Do you mind to guide a bit, what is the command and parameters to run the script create_files_for_hogs.py?

**Comment by davidemms** [comment]
Hi

Call it with the option "-h" and it will print its helpfile which describes the parameters.

Best wishes
David
