### ISSUE TITLE
incongruence between single copy genes number and species tree gene number

### ISSUE THREAD

**Issue by lisy87** [davidemms/OrthoFinder#504]
Hello 
I ran an Orthofinder analysis using the 2.5.2 version with 83 samples belonging to different species (3-2 samples by species). I got all the correct output from this analysis, but I noted an incongruence between the number of single-copy genes reported in Statistics_Overall.tsv  (414) and the orthogroups number in Orthogroups_for_concatenated_alignment.txt (1402) from Species_Tree folder. I used the -M msa option. This is not my first time with Orthofinder using this option, but before I worked with fewer samples, and always the numbers matched. It's the first time that I have some like that.
What does this mean?
What could have happened?
What behavior should I follow with these results? 

Thanks in advance,
Lisy

**Comment by davidemms** [comment]
Hi Lisy

This is to be expected, for MSA species tree inference OrthoFinder doesn't only use single-copy orthogroups (since they can be rare or non-existent in larger analyses). The method is described here: https://github.com/davidemms/OrthoFinder#species-tree-inference

Briefly, OrthoFinder can use orthogroups for species tree inference which are either not present or multicopy in some species. It does this by using gaps in the MSA for those particular species from that particular orthogroup.

All the best
David
