### ISSUE TITLE
Summarizing the result of orthofinder

### ISSUE THREAD

**Issue by TaehyungKwon** [davidemms/OrthoFinder#511]
Hi David,

It has been a pleasure to use this well-made program of yours. I really appreciate it.
In the meantime, I faced some problems in summarizing the result of OF. I ran it to identify "core orthologous gene set" that exists in all species, using many genomes with large taxonomic diversity. 
**Problem 1)** My primary goal is to generate the Figure 3d and 3e of 2019 Orthofinder article.
![image](https://user-images.githubusercontent.com/42432162/108303408-19979e80-7163-11eb-8525-666453bdad05.png)
However. I couldn't get any statistics about orthologous genes (or orthogroups) present across all species. You've mentioned that the stout shows the number I want: "When it is run, OrthoFinder outputs how many orthogroups it has identified with all species present. E.g. for the example dataset: 269 trees had all species present and will be used by STAG to infer the species tree". Is there any other way to manually curate the N0.txt file to calculate these statistics and get the core-ortholog set?

**Problem 2)** I used the STAG + STRIDE method to generate species tree. However, even "SpeciesTree_rooted.txt" does not have node support value from STAG. I guess this could be related to the empty directory "Single_Copy_Orthologue_Sequences". Could you kindly explain what happened here?

Thanks,
Taehyung

**Comment by davidemms** [comment]
Hi Taehyung

The script `OrthoFinder/tools/orthogroup_gene_count.py` will take the N0.txt file and produce a file with the number of genes in each species in each orthogroup. Using Excel or Python you can analyse this file to identify the rows (i.e. orthogroups) with greater than zero genes in each species.

For the support values in "SpeciesTree_rooted.txt", if you look in "Comparative_Genomics_Statistics/Statistics_Overall.tsv" how many orthogroups does it say had all species present? It requires at least 100 orthogroups in order to be able to get support values. If it has greater than 100 such orthogroups, could you email me the "SpeciesTree_rooted.txt" file and, if you have it, the output that orthofinder printed to screen.

All the best
David

**Comment by TaehyungKwon** [comment]
Thank you for the response, David.
About the support values, although the species tree used 153 OGs with a minimum of 22% of the species, the number of OGs with all species present is 77. I guess I have to run -m msa to generate the bootstrap value. I really appreciate your clarification on the problem. Have a good day!

Thanks,
Taehyung

**Comment by davidemms** [comment]
Hi Taehyung

If the species tree used "153 OGs with a minimum of 22% of the species" then it sounds like you used the "-M msa" option rather than STAG? If that's the case and if you used the default (fasttree) then I would expect there to be support values in the tree. I would recommend looking at the text file for the species tree with a text editor to confirm there really aren't any support values. 

If you did use the MSA option then there will be a file `MultipleSequenceAlignments/SpeciesTreeAlignment.fa` that was used for the species tree. As such, it's possible to run this with your favourite tree inference program to create a species tree with bootstrap support values.

Best wishes
David

**Comment by TaehyungKwon** [comment]
Dear David,

I apologize for not giving a clear explanation for that. I used STAG for the initial run, but I could not get any support value in "SpeciesTree_rooted.txt". Thus, I ran another run with MAFFT + Fasttree, which gave me a log saying "153 OGs with a minimum of 22% of the species". However, since I have too many genes, MSA does not seem to be the best fit for me.
Aside from the second run, there were only 77 OGs with all species present in the initial run. According to your answer, I guess there is no more thing for me to get support values using DendroBLAST+STAG option. Is that right?

Thanks,
Taehyung

**Comment by davidemms** [comment]
Hi Taehyung

With the default option if there are fewer than 100 orthogroups with all species present then it will print a message to screen, "Using fallback species tree inference method". In this case there isn't enough data for STAG to infer support values. If you only had 77 then this is likely what has happened.

If you use the v2.5.2 of OrthoFinder there are significant performance enhancements which means that the MSA method is about as fast as the default so you might be able to use this for species tree inference, you will then be able to get support values. You can start this from your existing results using "-fg PREVIOUS_RESULTS_DIR/ -M msa".

Best wishes 
David

**Comment by TaehyungKwon** [comment]
Thank you, David.
I will follow your advice. I appreciate it.
