### ISSUE TITLE
Running OrthoFinder on datasets with partial sequences

### ISSUE THREAD

**Issue by vragh** [davidemms/OrthoFinder#514]
Hi David,

Thank you for maintaining this awesome tool (and having written it in the first place).

I have a couple of transcriptomes that were assembled _de novo_ with `Trinity` (plus `TransDecoder` for the peptide prediction) and they have quite a lot of 3'/5'-partial/internal sequences in there. I'd like to scan these transcriptomes for orthologs to a sequence of interest.

I get the impression that the tool can handle isoforms just fine (they'd just be terminal duplications on the tree).

But how robust is `OrthoFinder` to the occurrence of **partial sequences** in the data set(s)? Would the HOGs produced by `OrthoFinder` be "unreliable" in this case? Would it make sense to use the (now deprecated but still available) orthogroups data for this purpose instead?

**Comment by davidemms** [comment]
Hi

I think it should generally work pretty well. Hits are corrected for sequence length so if you get a shorter hit to a partial sequence this is accounted for in the initial clustering stage. Then for the tree building I find that partial sequences usually get placed in pretty much the right place, at least for MSA trees. As such, I'd recommend using the `-M msa` option. I think the HOGs should then be pretty good.

Best wishes 
David

**Comment by vragh** [comment]
Hi David,

Thank you for the prompt feedback.

I have a couple of follow up questions (if I may).

1. Are the pairwise orthologs in the `Orthologues/` directory raw RBHs, or are they the (corrected) RBNHs? If they're corrected, are the corrections for sequence length only or also for phylogenetic distance?
2. I have a bit of a unique situation where I am using a "reference" proteome (_D. melanogaster_, actually) to fish out orthologs (from the _de novo_ transcriptomes I mentioned in the OP). The problem is that D. melanogaster does not have particular protein I am interested in, and I've transplanted a substitute for this (an ortholog from _D. plexippus_) into the _D. melanogaster_ proteome for the `OrthoFinder` run. Is this a bad thing to have attempted? In what ways would the orthogroup(s) prediction(s) be affected?
3. I also have a very uneven distribution of species across the phylogenetic tree (e.g., many arthropods, a few cnidarians and chordates). You did mention it's best to break up long branches by sampling intermediate species, but I'm not entirely sure if this is possible in my case. I presume `OrthoFinder` is fairly robust to this anyway? (I did some testing, and it certainly seems to as far as I can tell.)

I would be **super grateful** for your inputs. I do realize that I've also asked questions here that could potentially be well outside the scope of a simple (or even a long) comment, so it's entirely alright if I don't get a response here. (I am just grateful that you put in all this work to make this amazing tool possible, and available to the community!!)

**Comment by davidemms** [comment]
1. No, gene trees are used to identify orthologs. This is the correct method to use, RBH is an heuristic method that misses a large number of orthologs. The 2019 paper gives full details.
2. In general, yes. If *D. plexippus* is closer to *D. melanogaster* than any of your other species are to *D. melanogaster* then it'll probably work. The best thing to do would be to just include *D. plexippus* in your analysis too.
3. If you have intermediate species that's best but it's fairly robust all the same. It all comes down to identifying homologs. It's easier if there are intermediate species. I ran a test with a set of species similar to the tutorials once with just the 6 species and once with 80 species, including 21 dispersed between *H. sapiens* and *D. melanogaster*  (I wouldn't recommend this many, but it was a dataset I already had results for). With the 80 species dataset OrthoFinder was able to identify 9509 genes in *H. sapiens* which had orthologs in *D. melanogaster* whereas with the 6 species dataset it only identified 9243 such genes. So that's 2.9% more with the higher species sampling. Not massive, but if you have the computational resources and you want to chase those last few percentage points of accuracy then adding more species can help.

One way to improve on (3) if you don't have extra species is to use DIAMOND in ultra_sensitive mode. This is available with the latest version of OrthoFinder with the option "-S diamond_ultra_sens".

Best wishes
David
