### ISSUE TITLE
Trimmed/untrimmed MSAs in MultipleSequenceAlignments

### ISSUE THREAD

**Issue by darencard** [davidemms/OrthoFinder#515]
I found some older issues that discuss this (e.g., #199 ) and think I know the answer, but I wanted to confirm to be absolutely sure, so as to not disrupt downstream analyses. Are the FASTA MSA alignments in the MultipleSequenceAlignments directory raw and untrimmed, as in what would come directly from e.g. MAFFT? I'm looking at some and seeing gaps represented in most species, which suggests to me that these are the raw alignments before the missing data filtering is performed. Is my deduction correct?

Also, in case context matters or is useful for others, my goal is to use these MSAs to try to extract 4-fold degenerate sites. I am running OrthoFinder with CDS sequences for this reason. My idea is to use a well annotated species (e.g., Mouse in the vertebrate world) as the target to trim away any gaps based on this species in the MSA, which should provide the original CDS alignment based on the target. This is why having the untrimmed, raw MSAs is important. Then it should be simple to do easy things like extract 3rd codon positions, for example. I still need to find an option to infer the 4-fold degenerate sites from a multi-FASTA MSA, as this is usually inferred from whole genome alignments. If anyone has a tool for this, I would love to hear about it.

Thanks in advance for the help.
Daren Card

**Comment by davidemms** [comment]
Hi 

As of v2.5.1 the alignments are (very lightly) trimmed. The criteria for trimming are
1. A column can be trimmed if if is >90% gaps
2. No MSA will be trimmed to below 500 AA
3. At least 75% of the original AAs must be preserved

If any of these criteria aren't met then amount of trimming is reduced until they all are. The result is that a large proportion of the MSAs are never trimmed, but the especially bloated ones are (since these contribute disproportionately to the runtime but don't meaningfully improve the accuracy of those particular trees). 

You can turn this option off using the option "-z".

All the best
David

**Comment by darencard** [comment]
Thank you, David, for confirming these details! That is very helpful. One (low priority) feature request might be to preserve the original, untrimmed MSAs in the output. It costs some disk space, but might be better than having to do a separate analysis to recover those files. Either way, thanks for the help and I will close this issue.

**Comment by davidemms** [comment]
Agreed, that sounds like a useful feature.
