### ISSUE TITLE
Sequences missing from Phylogenetic_Hierarchical_Orthogroups files

### ISSUE THREAD

**Issue by fionasavory** [davidemms/OrthoFinder#519]
Hi David, 

I have detected an issue with a recent analysis using version 2.5.2 (conda installation). There seem to be a small number of sequences which are present in the ....Orthogroups/Orthogroups.tsv file, but which are absent in the ....Phylogenetic_Hierarchical_Orthogroups/Nx.tsv files.  For example, the missing sequences for a given proteome range from <0.02% to almost 1% in the N0.tsv file.  Do you have any idea what could be causing this?

Could you also please explain how/why orthogroups can be further split into hierarchical orthogroups in the node 0 file? I can of course understand this for other nodes in the species tree, but am struggling to grasp why at node 0 the inferred hierarchical orthogroups are not split into distinct orthogroups.

Any help would be much appreciated!

Fiona

**Comment by davidemms** [comment]
Hi Fiona

I think this may be to do with them not being in an orthogroup with any sequences according to the gene tree. First, check the "Resolved_Gene_Trees" that one of the sequences is in. Is the node immediately above the gene reported to be a gene duplication event at the N0 level in the Duplications.tsv file? If not, would you be able to send me an example gene name together with the tree from Resolved_Gene_Trees/ and I'll take a look.

In terms of the splitting, it's because the clustering approach traditionally used by all methods for orthogroup inference is not great, and will often make mistakes. For this reason, OrthoFinder analyses these clusters using the gene trees, like it does for orthologs, and will often find cases where the original groups from Orthogroups/Orthogroups.tsv actually need to be split into separate orthogroups. In OrthoFinder version 3 the Orthogroups/Orthogroups.tsv file will be deprecated. You should use the N0.tsv file as the most accurate delineation of the orthogroups.

All the best
David

**Comment by fionasavory** [comment]
Hi David, thanks for your reply and for the Orthogroups.tsv vs N0.tsv explanation. There does not seem to be a duplication detected at that node so I will send you the file.

Best wishes, Fiona

**Comment by davidemms** [comment]
Hi Fiona

I think we resolved this by email, but please let me know there's anything still unaddressed.

Thanks
David
