### ISSUE TITLE
Orthofinder still running after job killed.

### ISSUE THREAD

**Issue by nrobgithub** [davidemms/OrthoFinder#527]
I am running Orthofinder and when it gets to:

Calculating gene distances
Killed

It is killed without any input. I figured this may be a RAM issue as this is a large amount of taxa however from other issues it seems Orthofinder would indicate this. More interesting is that if I use top to inspect running processes Orthofinder is still running, using 95% CPU and not a lot of memory. If I do not kill this process it will run indefinitely.

Edit: I should mention this is using the source code as well as -fg (path to results folder with groups) and -t 30 options, I did not use -a and left it default.

**Comment by davidemms** [comment]
Hi

It sounds like it is most likely a RAM issue, it may be that together the processes were using too much RAM so one of them was killed. In the current release the default for '-a' has been increased to 1/4 of t i.e. 7 in your case. I would suggest one of two options:

1. Explicitly set '-a 1' and run again
2. Run using "-M msa" without setting -a (& make sure you're using the latest version of OrthoFinder)

I'd probably recommend option 2 since the latest improvements mean that MSA based trees are now about as fast and sometimes faster than the default distance based trees. This method also have lower RAM requirements.

All the best
David

**Comment by nrobgithub** [comment]
Thanks David!

Unfortunately the same problem occurs with the -M msa method. This machine has 128GB of RAM. I will see if moving this job to the cluster and giving it 500GB or so helps this issue.

Best,

**Comment by davidemms** [comment]
Would you be able to paste the whole output, it might give a clue as to what the problem is.

Thanks
