### ISSUE TITLE
Inflation parameter when using nucleotides

### ISSUE THREAD

**Issue by macmanes** [davidemms/OrthoFinder#547]
David, 

Noticing some potentially unexpected behavior with the inflation parameter with using the `-d` nucleotides option.. I am using Orthofinder 2.5.2 and the following command (but changing `- I` to the set value). 

```
orthofinder -d -I 1.5 -f working/ -og -t 24 -a 24
```

I am seeing very little difference in the orthogroup stats when using inflation parameters between 1.5 (the default) and 12. The "clumpiness" of the resultant orthogroups is very similar which makes me wonder if the `-I` parameter is being parsed properly.  Here are some stats:

### Inflation = 1.5

```
Number of species	4
Number of genes	308465
Number of genes in orthogroups	272320
Number of unassigned genes	36145
Percentage of genes in orthogroups	88.3
Percentage of unassigned genes	11.7
Number of orthogroups	73780
Number of species-specific orthogroups	3430
Number of genes in species-specific orthogroups	8762
Percentage of genes in species-specific orthogroups	2.8
Mean orthogroup size	3.7
Median orthogroup size	3.0
G50 (assigned genes)	4
G50 (all genes)	4
O50 (assigned genes)	24317
O50 (all genes)	28835
Number of orthogroups with all species present	31652
Number of single-copy orthogroups	19156
```

### Inflation = 6

```
Number of species	4
Number of genes	308465
Number of genes in orthogroups	266915
Number of unassigned genes	41550
Percentage of genes in orthogroups	86.5
Percentage of unassigned genes	13.5
Number of orthogroups	86674
Number of species-specific orthogroups	7456
Number of genes in species-specific orthogroups	18732
Percentage of genes in species-specific orthogroups	6.1
Mean orthogroup size	3.1
Median orthogroup size	3.0
G50 (assigned genes)	3
G50 (all genes)	3
O50 (assigned genes)	30560
O50 (all genes)	37485
Number of orthogroups with all species present	26484
Number of single-copy orthogroups	20432
```

### Inflation = 12

```
Number of species	4
Number of genes	308465
Number of genes in orthogroups	262609
Number of unassigned genes	45856
Percentage of genes in orthogroups	85.1
Percentage of unassigned genes	14.9
Number of orthogroups	88185
Number of species-specific orthogroups	8486
Number of genes in species-specific orthogroups	20389
Percentage of genes in species-specific orthogroups	6.6
Mean orthogroup size	3.0
Median orthogroup size	3.0
G50 (assigned genes)	3
G50 (all genes)	3
O50 (assigned genes)	31739
O50 (all genes)	39382
Number of orthogroups with all species present	24449
Number of single-copy orthogroups	19759
```

The 'clumpiness' of the assembly does change in the predicted way, but very little so. Prior, to the implementation of the `-d` parameter, I had been using a modified version of orthofinder for nucleotides and this resulted in a MUCH less clumpy orthogroup assignment (using `-I 4`). I understand that in addition to new functionality, the algorithm has changed and this might explain the difference in results.  For instance using Orthofinder 2.3.9 (modified to accept nts, I=4)  I get this.

```
Number of species	4
Number of genes	295791
Number of genes in orthogroups	248
Number of unassigned genes	295543
Percentage of genes in orthogroups	0.1
Percentage of unassigned genes	99.9
Number of orthogroups	114
Number of species-specific orthogroups	12
Number of genes in species-specific orthogroups	25
Percentage of genes in species-specific orthogroups	0.0
Mean orthogroup size	2.2
Median orthogroup size	2.0
G50 (assigned genes)	2
G50 (all genes)	1
O50 (assigned genes)	52
O50 (all genes)	147762
Number of orthogroups with all species present	2
Number of single-copy orthogroups	2
```

**Comment by davidemms** [comment]
Hi

From your output it looks pretty certain that the inflation parameter is being passed correctly to MCL. The '-I' option affects nothing else in the code, and as your output shows the number of clusters increases monotonically with the inflation parameter.

I haven't done any extensive analysis with the inflation combined with nucleotide input but it does appear from your results that the clusters are a lot more robust to variations in this parameter. I'm not sure what's caused the difference between this and your modified version, I don't think there'd been any variation in the algorithm. The only change since the initial release is in the identification of species specific orthogroups, it could be that these are the clusters you are obtaining with the new version.

It's always possible to test out what MCL is doing, the input graph files is in the OrthoFinder WorkingDirectory so you can try using this as input to MCL directly and see what affect this has on the number of clusters it produces with two or more genes.

Best wishes
David
