### ISSUE TITLE
HOGs for Comparative Genomics?

### ISSUE THREAD

**Issue by janetxinli** [davidemms/OrthoFinder#560]
Hi there,

I am using OrthoFinder v2.5.2 to identify orthogroups between several fungal strains. I'm a bit confused about how the new phylogenetic hierarchical orthogroups data fits in with the rest of OrthoFinder's output data, and was wondering if I could get some clarification.

I have been comparing HOGs in `Phylogenetic_Hierarchical_Orthogroups/N0.tsv`, and have noticed that the files in the `Comparative_Genomics_Statistics` subdirectory still summarize regular OGs (i.e. those in `Orthogroups/Orthogroups.tsv`). My understanding is that the new HOGs are to be used in replacement of regular OGs because they are more accurate. Is this correct? For example, should I be identifying single copy hierarchical orthogroups from `N0.tsv` rather than using the `Orthogroups/Orthogroups_SingleCopyOrthologues.txt` file?

Thank you!

**Comment by ViriatoII** [comment]
We've addressed that in this issue:  https://github.com/davidemms/OrthoFinder/issues/367

The HOGs differ from the OGs, yes. Sometimes a big OG had several subtrees, each reflecting the phylogeny independently, which probably means the gene duplicated before the species divergence (Paralogy instead of homology). 


Cheers,
Ricardo

**Comment by davidemms** [comment]
Hi @janetxinli

Sorry, the statistics haven't been updated yet to reflect the data in the HOGs files. They will be for version 3. 

Best wishes
David

**Comment by janetxinli** [comment]
Thank you!
