### ISSUE TITLE
Strange error about  OrthoFinder!

### ISSUE THREAD

**Issue by lllllzz** [davidemms/OrthoFinder#569]
I want to build an evolutionary tree with orthofinder, but the following error occurred during runing.

ERROR: external program called by OrthoFinder returned an error code: -9

Command: diamond blastp -d /public-dss/protein_dir/OrthoFinder/Results_May26/WorkingDirectory/diamondDBSpecies30 -q /public-dss/protein_dir/OrthoFinder/Results_May26/WorkingDirectory/Species10.fa -o /public-dss/protein_dir/OrthoFinder/Results_May26/WorkingDirectory/Blast10_30.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

**Comment by davidemms** [comment]
Hi

DIAMOND has returned an error. Most likely there is a problem with one of your input files, either the one given the ID 10 or 20 in the Log.txt file in the Results directory that OrthoFinder created. You can run the command yourself to see what the problem is, if you remove the "--quiet" command from the end it will give you more details. The 'diamond' executable is in the orthofinder 'bin' directory, you may have to specify the full path to this diamond executable in order to run the command.

Best wishes
David

**Comment by lllllzz** [comment]
Hi David,
Thanks for your reply.
I will try again to solve the problem.
Best,
lllllzz

**Comment by davidemms** [comment]
Hi lllllzz

Did you manage to solve this problem? If not, please feel free to reopen this issue and update it with any new info.

Thanks
David
