### ISSUE TITLE
RaxML substitution model and bootstraps?

### ISSUE THREAD

**Issue by ViriatoII** [davidemms/OrthoFinder#575]
Hey,

Quick one: Which substitution model is given to RaxML? Is it possible to change this?

I suspect you use General Time Reversible (GTR) model, but there are alternatives. 

Finally, how does it obtain bootstrap values?

Kind regards,
Ricardo

**Comment by davidemms** [comment]
Hi Ricardo

You can see the command line for RAxML in the "config.json" file and edit it as required.

If you are using the default MSA method then it will use FastTree rather than RAxML. That gives SH support values. If you want to use a custom method such as RAxML just specify the options you want, such as requesting bootstraps, in the config.json file. Be careful with expensive methods like RAxML though, they take a very long time, I'd suggest testing it on a small dataset first.

All the best
David

**Comment by ViriatoII** [comment]
Thanks! :)
