### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by lningyawen** [davidemms/OrthoFinder#581]
Hi David,
              I encountered a problem when I run orthofinder in server cluster. The error message reported is as follows: 
ERROR: The system limits on the number of files a process can open is too low. For 51 species OrthoFinder needs to be able to open at least r=2701 files. Please increase the limit and restart OrthoFinder
1. Check the hard and soft limits on the number of open files for your system:
    $ ulimit -Hn
    $ ulimit -Sn
2. If hard limit, h > r already, then you just need to increase the soft limit:
    $ ulimit -n 2701
3. Alternatively, if h < r then you need to edit the file '/etc/security/limits.conf', this requires root privileges. To increase the limit to 2701 for user  called 'emms' add the lines:
    emms hard nofile 2701
    emms soft nofile 2701
    (edit these lines to match your username)
4. Check the limit has now been updated (if you changed the hard limit you'll need to open a new session and confirm it's updated):
    $ ulimit -Sn
5. Once the limit is updated restart OrthoFinder with the original command

For full details see: https://github.com/davidemms/OrthoFinder/issues/384

ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

I found this problem is same as described in the https://github.com/davidemms/OrthoFinder/issues/384. It is about system limits. 
              However, I used these two commands `ulimit -Hn` and `ulimit -Sn` to check my quota and got the same result: 81920. This number is much larger than 2701. And I also checkd the '/etc/security/limits.conf' , got the results: 
`
soft            nofile          81920
hard            nofile          81920
`

It doesn't seem to be about ulimit, so I'd like to ask what I should do to fix this problem. Any help will be much appreciated, Thanks.

Yawen

**Comment by davidemms** [comment]
Hi Yawen

I think it is almost certainly that the server will not allow you to open the 2701 files. There may be other ways that your particular system imposes the limit, iI would suggest seeing if your server administrator is able to help. 

The test OrthoFinder runs is to try to open that many files at once and if an error occurs then to report the message you have seen. If you need to do any testing of the setup on the server then a simple script that tries to open a user-specified number of files on the server should reproduce the problem. You would then also be able to see the specific error message produced by the server, which might help you identify where the problem lies.

Best wishes
David

**Comment by lningyawen** [comment]
Hi David:

I have solved this problem, which was due to qsub. I check the number of files that can be opened in the script submitted by qsub.

#!/bin/bash
#PBS -N ortho
#PBS -l nodes=1:ppn=30
ulimit -n > ulimit.out

I found that the number of open files was only 1024. So I added `ulimit -n 4096` in the qsub script. And it worked.
Thanks again for your help!

Best wishes
Yawen

**Comment by davidemms** [comment]
Thanks, that should be helpful for other users having the same issue.
