### ISSUE TITLE
ERROR: Not enough species to infer species tree

### ISSUE THREAD

**Issue by agathat** [davidemms/OrthoFinder#59]
Hi,

I am running Orthofinder with default paremeters on a set of three bacterial proteomes. The software runs with no obvious errors until the 'Inferring gene and species trees' section where it exits and errors after completing 160 of 162 trees. It gives the error: Not enough species to infer species trees. I realise that this is because I do not have at least 4 input samples.

Is there any way to get orthologs for less than four input samples?

Thank you,
Agatha

**Comment by davidemms** [comment]
Hi

Obviously, you need 4 species to be able to infer a meaningful species tree. However, do you know which of the three species diverged first? If so you could write a file with the correctly rooted species tree e.g. for the example dataset it might look like this  
[SpeciesTree_user.txt](https://github.com/davidemms/OrthoFinder/files/875659/SpeciesTree_user.txt). (This file says that of the 3 species, Mycoplasma_agalactiae diverged first. Just replace these species names with your own)


Then call orthofinder using something like this:
`orthofinder -ft ExampleDataset3Species/Results_Mar28/Orthologues_Mar28/ -s ExampleDataset3Species/SpeciesTree_user.txt`
"-ft": restart from the gene tree (it will have done all 162 gene trees but it only prints out round numbers) 
"-s": use a user-supplied rooted species tree
(you can call orthofinder -h to see the description for these arguments)

I will look at extending OrthoFinder so that it will automatically work even if you only have 3 species.

All the best 
David

**Comment by davidemms** [comment]
... and as there are only 3 different rooted species trees with 3 species then if you don't know which diverged first you could just run the above command 3 times, once with each of the 3 possible outgroup species, and compare your results. It should be very quick!

David

**Comment by agathat** [comment]
Hi,
Thank you, this may be useful. However, currently I am only interested in the pairwise homologs between 2 of the species. This doesn't appear to be possible without running the whole pipeline (including the trees) for 4+ species. It is not a big issue as the proteomes are small, but I was just curious as to whether there was a work around, or whether I had misunderstood the results.

Cheers,
Agatha

**Comment by davidemms** [comment]
Hi

Sorry for the delay in answering. The '-ft' option is to allow you to restart from the inferred gene trees i.e. skipping almost all of the pipeline and only running the stuff which will actually change. See https://github.com/davidemms/OrthoFinder/blob/master/OrthoFinder-options.pdf

All the best
David

**Comment by davidemms** [comment]
Hi

Just to add, I think your understanding of it is correct. To infer the pairwise homologues between 2 species this is the workflow you would have to do. OrthoFinder is mainly focussed on groups of species, hence the approach may seem heavy-handed for the simpler pairwise case.

All the best
David
