### ISSUE TITLE
List index out of range Warning and no SH values

### ISSUE THREAD

**Issue by ViriatoII** [davidemms/OrthoFinder#591]
Hi,

I got a warning message in my run, I wonder if it's problematic. This was a RaxML run, the largest gene trees were taking a long time to finish, maybe they crashed?

Analysing Orthogroups
=====================
2021-06-27 16:24:13 : Starting MSA/Trees
Species tree: Using 102 orthogroups with minimum of 50.0% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2021-06-27 16:25:42 : Done 0 of 102
2021-06-27 16:26:31 : Done 30 of 102
2021-06-27 16:26:12 : Done 10 of 102
2021-06-27 16:26:24 : Done 20 of 102

Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2021-06-30 03:45:31 : Done 1000 of 30805
WARNING:
list index out of range
2021-06-30 20:26:45 : Done 3000 of 30805
2021-07-01 22:30:06 : Done 22000 of 30805
2021-07-01 22:31:03 : Done 28000 of 30805
2021-07-01 22:30:45 : Done 26000 of 30805
2021-07-01 22:30:26 : Done 24000 of 30805
2021-07-01 11:29:17 : Done 7000 of 30805
2021-07-01 22:30:36 : Done 25000 of 30805
WARNING:
list index out of range
2021-07-01 18:51:22 : Done 11000 of 30805
WARNING:
list index out of range
2021-07-01 08:43:51 : Done 6000 of 30805
........... In continues successfully until the end and creates all output files well.

The only thing I think is missing is the SH values in the final Species tree. There are only branch lengths and node ages. Here's the tree:

> (g_gynandra:0.212585,(a_arabicum:0.205354,(a_alpina:0.133205,(a_thaliana:0.132057,(c_annua:0.108042,(d_tenuisiliqua:0.0876985,(((d_harra:0.0757304,((e_sativa:0.062548,d_acris:0.0417114):0.0126422,((b_gravinae:0.0574341,b_repanda:0.045715):0.00695154,(d_tenuifolia:0.0536684,(d_viminea:0.0102224,d_muralis:0.00191954):0.0443954):0.0144899):0.0101031):0.00748391):0.010097,(m_moricandioides:0.042699,(m_sinaica:0.0286433,(m_arvensis:0.0335797,(m_suffruticosa:0.0269214,(m_nitens:0.0207511,m_spinosa:0.0245974):0.00528699):0.00643603):0.00355409):0.0152136):0.0220587):0.00746132,(s_alba:0.0578221,((b_nigra:0.0499745,(b_juncea:0.0262456,(b_oleracea:0.0363712,(b_napus:0.0142453,b_rapa:0.0246998):0.00776489):0.025559):0.023359):0.0105183,(d_erucoides:0.0794458,(((h_incana:0.0515408,h_incana3:0.0561499):0.0091732,b_tournefortii:0.0580792):0.00816731,(r_raphanistrum:0.0214703,r_sativus:0.0200398):0.045893):0.0123752):0.00984929):0.00838218):0.00827639):0.0169171):0.0215178):0.0717041):0.0137344):0.0687074):0.212585);

Unlike https://github.com/davidemms/OrthoFinder/issues/460 and https://github.com/davidemms/OrthoFinder/issues/355, my run does not use the fallback method.

Cheers,
Ricardo

**Comment by davidemms** [comment]
Hi

RAxML is unlikely to be successful for OrthoFinder because its computational requirements are highly likely to exceed the capacity of anyone's computer or server.

I don't think RAxML provides the option of calculating SH support values, although you can check in its manual to see if this is the case. RAxML provides the option of calculating support values using bootstrap replicates, which is the more standard approach, but that option won't have been selected in OrthoFinder as it is even more expensive than using RAxML without bootstrap replicates. 

Either way, to run OrthoFinder using RAxML with bootstrap replicates you can edit the config.json file to say which options you would like OrthoFinder to call RAxML with. However, if you want support values for just your species tree then you can call RAxML yourself on the MultipleSequenceAlignments/SpeciesTreeAlignment.fa file, this would be a more efficient option than doing it via OrthoFinder since you won't be performing bootstrap replicates on all the orthogroup trees, some of which will be many times larger than the species tree.

Given the warnings, I would also check to see if RAxML crash for any of the Gene Tree by looking for empty/missing files in the "Gene_Trees/" directory.

Best wishes
David
