### ISSUE TITLE
OrthoFinder getting orthologs and paralogs gene list

### ISSUE THREAD

**Issue by Hemantcnaik** [davidemms/OrthoFinder#596]
Hello,

Thank you for the tool I have successfully run the OrthoFinder. My main objective is to find the orthologs and paralogs(species specific) I need a gene IDs, which file will provide me details of genes which are orthologs and paralogs. how confidently I can tell genes I am getting which are true orthologs and paralogs

I wanted gene IDs so I used CDS fasta from the ensembl is it correct way of doing?

Thank you

**Comment by davidemms** [comment]
The orthologues are listed in the files in the "Orthologues" directory, there is one file per species-pair. 

The species-specific paralogs are the ones in the "Gene_Duplication_Events/Duplications.tsv" file that duplicated in that species, i.e. the ones where the "Species Tree Node" column has a species name rather than an internal gene tree node name.

These orthologs and paralogs are identified using gene tree inference, so they are more accurate than methods using BLAST scores. Gene tree inference is the most accurate method for determining orthologs.

I would recommend using the proteome files (of amino acid sequences), not CDS. I'd recommend looking at the tutorials for more information: https://davidemms.github.io/menu/tutorials.html

Best wishes 
David
