### ISSUE TITLE
How does orthofinder reconstruct species tree?

### ISSUE THREAD

**Issue by Huanle** [davidemms/OrthoFinder#62]
Hi David,
Can you explain a little bit about how orthofinder reconstruct species tree?
I did not give species tree as input. But it produced a SpeciesTree_rooted.txt file in Orthologoues folder. 

Thanks a lot in advance.

**Comment by lkelly3** [comment]
Hi David

I would also really like to know more about how the species tree is reconstructed. I have run OrthoFinder with the default option for the -M parameter, so I believe the species tree I get should be constructed by DendroBLAST. I've taken a look at the DendroBLAST publication, but in the context of species-tree inference within OrthoFinder I'm not sure which data DendroBLAST is using. Does it create a consensus from selected gene trees inferred by DendroBLAST from the individual orthogroups? Or does it create a combined matrix of pairwise scores from sequences from multiple clusters and then infer the species tree from this?

Many thanks
Laura

**Comment by davidemms** [comment]
Hi Laura

We are preparing the manuscript that describes this (and other) extra functionality added since the first OrthoFinder release. We hope to have this paper submitted in pre-print in the next couple of
months. Basically the dendroblast distances for the species tree come from the median distances for the most closely related genes between those species in the orthogroups. 

The rooting of the species tree is performed using STRIDE, a method that is currently in submission. The preprint version is available here: http://biorxiv.org/content/early/2017/05/19/140020

All the best
David
