### ISSUE TITLE
Skips some blasts from all_vs_all blasts

### ISSUE THREAD

**Issue by ParthKRaval** [davidemms/OrthoFinder#639]
Hi, we are trying to run orthofinder on our cluster, and we find that orthofinder runs are finishing but some blasts from all_vs_all blasts (often that of the genome against itself) are not finished and those genes are discarded altogether from the clustering process. The error says the following:

ERROR: external program called by OrthoFinder returned an error code: -4
Command: diamond blastp -d /gpfs/project/raval/Orthofinder/PlastidBio/OrthoFinder/Results_Oct29_1/WorkingDirectory/diamondDBSpecies1 -q /gpfs/project/raval/Orthofinder/PlastidBio/OrthoFinder/Results_Oct29_1/WorkingDirectory/Species1.fa -o /gpfs/project/raval/Orthofinder/PlastidBio/OrthoFinder/Results_Oct29_1/WorkingDirectory/Blast1_1.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1
stdout
------
b''
stderr
------
b''

This is for blast Blast1_1, but the same error comes for 2_2 and 3_3. As a consequence, the following error comes downstream:

WARNING: Too few hits between species 1 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 3 to normalise the scores, these hits will be ignored

And in the end, smaller than expected fraction of genes are clustered. 
Any help is much appreciated on these issues!

Thanks,
Parth

**Comment by davidemms** [comment]
Hi Parth

Is that using diamond using the command above? You could also try editing the OrthoFinder config.json file to remove '--quiet' option so that it looks like this:
```
    "diamond":{ 
    "program_type": "search",
    "db_cmd": "diamond makedb --in INPUT -d OUTPUT",
    "search_cmd": "diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 -e 0.001 --compress 1"
    },  
```

This way you will get the output from each diamond run and this may have some information as to what the problem was. 

Just and idea, but it may also be worth investigating if you are running out of RAM and the processes are being killed by the linux OOM killer. The self-self BLASTS could be susceptible to this because of exact alignments between particularly long sequences.

All the best
David
