### ISSUE TITLE
It iqtree2 suported by orthofinder?

### ISSUE THREAD

**Issue by Lamm-a** [davidemms/OrthoFinder#642]
Am I able to use iqtree2 instead of v1 with Orthofinder?

**Comment by davidemms** [comment]
Sorry for the slow response on this, if you edit the `scripts_of/config.json` file for orthofinder so that the iqtree line looks like this

```
"cmd_line": "iqtree2 -s INPUT -pre PATH/IDENTIFIER -quiet ; iqtree2 -s INPUT -pre PATH/IDENTIFIER -quiet -safe",
```
then that should call iqtree2 if it is in your system path. 

It's unclear to me if they intend to change the name of their executable to iqtree2 in the long term so I'm not sure what changes I should make in the OrthoFinder codebase at this point. Currently they still list 1.6.12 as their stable release.

Best wishes 
David
