### ISSUE TITLE
Orthogroups_SingleCopyOrthologues.txt is empty as is Single_Copy_Orthologue_Sequences

### ISSUE THREAD

**Issue by Lamm-a** [davidemms/OrthoFinder#649]
I am running orthofinder on 44 fungal species and am looking into using the single copy orthologous to construct a species tree but Orthofinder is suggesting there are none as both Orthogroups_SingleCopyOrthologues.txt  and Single_Copy_Orthologue_Sequences is empty. Is this likely an error? I have use other tools such as BUSCO to recover single copy otrhologues with success so I am a bit confused why these would be empty.

`orthofinder -t 40 -M msa -A mafft -T iqtree -a 1 -f $proteinDatabase`

**Comment by davidemms** [comment]
Hi

Although a BUSCO search will identify single-copy genes in a single species it usually only recovers 70-95% of the expected ones as present and single copy in any particular species (See E.g. Figure 2B here https://doi.org/10.1016/j.cub.2021.08.008). Once you've got 44 species, the probability of getting the same gene to be both present and not duplicated in every one of those 44 species becomes quite unlikely. 

The approach you can take for species tree inference is to remove the requirement that every gene be present and single-copy in every single species. If you ignore species where the gene is missing or duplicated then you will get an MSA that covers all your species. The gaps from missing species will be different for each orthogroup and so that isn't a problem. 

That is what OrthoFinder does when you select the "-M msa" option (if you want the full details they are here: https://github.com/davidemms/OrthoFinder#multiple-sequence-alignment-species-tree-method--m-msa). 

You can see the orthogroups OrthoFinder used for the species tree MSA in this file: `Species_Tree/Orthogroups_for_concatenated_alignment.txt`

and the MSA it produced here: `MultipleSequenceAlignments/SpeciesTreeAlignment.fa`

Best wishes 
David
