### ISSUE TITLE
Average similarity with orthogroups - can we access this info?

### ISSUE THREAD

**Issue by mcmahon-uw** [davidemms/OrthoFinder#654]
Hi!  This is more of a question than an issue per se

I'd like to look at the statistics of within-orthogroup similarity. Most simply, this could just be extracted from the DIAMOND output (right?).  Even better, we could calculate the branch lengths within the orthogroup trees (though I would have to think hard about whether this would be the sum of branch lengths or min and max?).  Does that make sense?

I have some hypotheses I want to test about the extent of divergence of certain orthologs vs others.

thank you!
trina

**Comment by davidemms** [comment]
Hi Trina

This is definitely and interesting analysis and one that could be done, but there's nothing currently in OrthoFinder to do it. I've done similar calculations in the past, I think the average diamond bit score or log-evalue is the easiest. Analysing the trees is also possible but you need to deal with the fact that they have gene duplication events in. Because of this, something like the min for each species pairs is easiest. If you look at this preprint (https://www.biorxiv.org/content/10.1101/267914) and code (https://github.com/davidemms/STAG) you can see how that idea is used to allow species tree inference from multi-copy gene families. I.e. estimate amount of divergence between each pair of species in the orthogroup by looking at the smallest divergence between any two genes in those species, since they will be orthologs rather than paralogs.

Best wishes
David
