### ISSUE TITLE
Can orthofinder work with transcriptome data containing different isoforms ?

### ISSUE THREAD

**Issue by gouwei1** [davidemms/OrthoFinder#674]
Hi

I have some different species' transcripts containing different isoforms (such as alternative splicing), and I want to infer their corresponding orthologues. So can I directly use orthofinder to deal with the data that have different isoforms ? Can results be reliable and Interpretable ？  

Thanks!

**Comment by davidemms** [comment]
Hi 

Since the different isoforms all represent the same locus it is best to just use one representative gene sequence per gene. That way the orthology information for each gene will correspond to each of the isoforms too. 

If you're not able to separate them out this way they you can use these raw files as input however OrthoFinder will think the different isofroms are species-specific gene duplication events. You should still mostly get the correct orthology inference, but with a little loss of accuracy if the gene trees aren't exactly right. 

Best wishes 
David
