### ISSUE TITLE
ERROR: Cannot run diamond

### ISSUE THREAD

**Issue by gouwei1** [davidemms/OrthoFinder#686]
Dear David,

It seems something was wrong with diamond. But when I typed ''diamond help'', it can work normally. I'm wondering if the error is from the Linux cluster (CentOS release 6.8 (Final)) using PBS (Protable Batch System) to submit the task, because there was no error when I used orthofinder (latest installed from conda) on my own laptop using the same installing routine (windows subsystem for Linux, Ubuntu 20.04 LTS).

The following are the detailed error messages:

OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2022-03-09 09:02:01 : Starting OrthoFinder 2.5.4
20 thread(s) for highly parallel tasks (BLAST searches etc.)
2 thread(s) for OrthoFinder algorithm
Checking required programs are installed

ERROR: Cannot run diamond
Format of make database command:
diamond makedb --ignore-warnings --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
diamond blastp --ignore-warnings -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path

ERROR: An error occurred, please review the error messages they may contain useful information about the problem.

Yours,
Wei

**Comment by gouwei1** [comment]
> 

Dear Cecilia,

Thanks for your detailed information.
I failed at the first step: installing diamond...
I followed the diamond's official suggested commond:
wget http://github.com/bbuchfink/diamond/releases/download/v2.0.14/diamond-linux64.tar.gz
tar xzf diamond-linux64.tar.gz
But when I used it, the error said:

./diamond: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./diamond)
./diamond: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./diamond)

I do not have authority to make changes for /lib64/libc.so.6.
So...have you ever dealed with this error without root authority?

Best,
Wei

**Comment by davidemms** [comment]
Hi Wei

You could try building diamond yourself so that it uses the version of glibc that you have.

Best wishes
David

**Comment by gouwei1** [comment]
> Hi Wei
> 
> You could try building diamond yourself so that it uses the version of glibc that you have.
> 
> Best wishes David

OK, I'll have a try. Thank you!

**Comment by Cecilia-Sensalari** [comment]
Hi,

It's a bit late for an update, but here is one: when I provided more memory to the submitted job, OrthoFinder was able to run diamond without giving that diamond error message. Moreover certain clusters needed more memory than others or they would keep showing the error. Example: I ran in parallel with 2 threads each given 10GB or 20GB (depending on the cluster I submitted to).

The presence of the OrthoFinder configuration file, as I suggested above, was not relevant to this matter since I had OrthoFinder working also when deleting the configuration file.

Cecilia

**Comment by Oelsakha** [comment]
> Hi,
> 
> It's a bit late for an update, but here is one: when I provided more memory to the submitted job, OrthoFinder was able to run diamond without giving that diamond error message. Moreover certain clusters needed more memory than others or they would keep showing the error. Example: I ran in parallel with 2 threads each given 10GB or 20GB (depending on the cluster I submitted to).
> 
> The presence of the OrthoFinder configuration file, as I suggested above, was not relevant to this matter since I had OrthoFinder working also when deleting the configuration file.
> 
> Cecilia
Excuse me I have the same issue  and tried config_orthofinder_user.json editing but still the same error. can you tell me how to increase memory to the submitted job ? 

Thank you

**Comment by gforg34** [comment]
Hi,

I know this thread is a two years old thread, but I am struggling understand how you solved the issue here. I am also using a SLURM cluster to run orthofinder, but I changed the partition and nodelist using different combinations of memory even reaching 200Gb. However, the following error still persists. So to give some more info I am using the latest version of orthofinder (2.5.5) and the partition that I am using has 64 threads and more than 1T memory (if that helps).

```
OrthoFinder version 2.5.5 Copyright (C) 2014 David Emms

2024-03-08 15:01:28 : Starting OrthoFinder 2.5.5
12 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
diamond produced the following output:
Error: Invalid option: ignore-warnings
Error: Invalid option: ignore-warnings
ERROR: Cannot run diamond
```
Also how can I locate the config.json file in the cluster? do you have any ideas? Any help will be appreciated!
