### ISSUE TITLE
Issue installing fastme v2.1.5

### ISSUE THREAD

**Issue by jdarias93** [davidemms/OrthoFinder#74]
Hello,

Just for the record, I have contacted Dr. Lefort concerning this issue, but perhaps someone else has had a similar issue and found a solution already.

I am currently trying to install fastme v2.1.5 on my Mac Pro and I am using OSX El Capitan.

In terminal, when I use `./configure && make && make install` everything seems to be fine until the very end when I get these error messages:

```
Making install in src
.././install-sh -c -d '/usr/local/bin'
/usr/bin/install -c fastme '/usr/local/bin'
install: /usr/local/bin/fastme: Permission denied
make[2]: *** [install-binPROGRAMS] Error 71
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
```
I looked into it a bit and one online resource says that El Capitan does not need the /usr/ prefix anymore, but I'm not sure how to change that here, as I am still a beginner in all of this. Any help or advice is appreciated. Thank you in advance, and have a wonderful day.

**Comment by davidemms** [comment]
That sounds like a permissions issue, for example see here: https://stackoverflow.com/questions/32901372/mac-os-dont-have-permission-to-usr-bin-folder-at-all

I don't know too much about how things are setup on Macs but you can see your read/write permissions for /usr/loca/bin by doing:

```
cd /usr/local/bin
ls -la
```
The line with a single dot at the end tells you the permissions for putting something in the directory e.g. on my machine it says:
```drwxr-xr-x  2 root root    4096 Apr 27 10:44 .```
which means that I'd need to be root in order to copy a file there. That is what's happening with the script, it is trying to copy the executable file there are failing because of write permissions. On linux you'd do this step with root privileges using sudo. I'm not exactly sure what you'll need to do on a mac but hopefully this should be enough info for you to be able to search with to find out the solution.

All the best
David

**Comment by jdarias93** [comment]
Hi David,

I was able to use

`./configure
sudo make install`

while I was logged into the root user on the Mac device to install Fastme. Fastme seems to be working now. Thank you for the help!

Josh

**Comment by davidemms** [comment]
That's great, thanks for letting me know.

David
