### ISSUE TITLE
Inferring Orthologs from Gene Trees... more memory needed?

### ISSUE THREAD

**Issue by WallyL** [davidemms/OrthoFinder#75]
Hi David,

From my closed post the other day, I am analyzing a set of 95 de novo assembled and RAST annotated bacterial genomes that are all (likely) the same species, but differ at a strain level.  I am running them in two groups based on their closest GenBank reference.  

The first group of 30 ran fine using ver. 1.0.8 and again with a test restart from blast data using ver. 1.1.4.  Both runs took ca. 8 hr. with 30 cores.  The second set of 65 failed using ver. 1.0.8  and I restarted with 1.1.4 and, after almost 2 days, it's still running.  This set does have about 5 strains that are not as closely related to the closest reference genome.  So trying to see what the difference was, I see that in the out file the group of 30 had this:

Observed 6 duplications. 6 support the best root and 0 contradict it.
Best outgroup for species tree:
  A5104-3, A5104-2

while the group of 65 has this:

Observed 0 duplications. 0 support the best roots and 0 contradict them.
Best outgroups for species tree:
(There are 128 different outgroups that follow)

The run is now reconciling gene trees for root 15 and at this rate it will be ca. two weeks to job completion.  Is there anything I can do at the start of the run to mitigate this?  It seems excessive and my plan was to analyze the both groups together with addition of their closest refs, so 97 samples.  Do you think this is a memory issue (I believe the cluster node it's running on has 48G RAM) or do I need to give it more cores?  I did not use the -a flag on the restart.  Do you think that would make any difference?

Thanks,
Walt

**Comment by davidemms** [comment]
Hi Walt

Yes, you can avoid this by providing a rooted species tree as input using the "-s" option. You can restart from the already inferred gene trees by combining it with the "'-ft" option to avoid redoing any of the previously completed work. The "-a" option probably won't be necessary if you do this. (You can use a program such as dendroscope to look at one of the rooted species trees produced by OrthoFinder and reroot it where you think best. You can also hand edit the position of species within the tree itself if you think any of the species are in the wrong position) 


Background info:
OrthoFinder needs a rooted species tree in order to infer orthologues. To root the species tree it uses gene duplication events but there won't always been enough gene duplication events to narrow down the position of the root to just one branch. In this case orthofinder will infer orthologues for each of the possible root positions for the species tree. It looks like in your case this will mean it performing this analysis for all 128 cases. Providing the rooted species tree that you would like to use will mean that it will only infer the orthologues for this one case. 

All the best
David
