### ISSUE TITLE
Pairwise BLASTs vs. parsing a single large all-vs-all

### ISSUE THREAD

**Issue by kgun12** [davidemms/OrthoFinder#79]
Is there any reason I shouldn't be able to run a single large all-vs-all blast job and then parse out the results into individual pairwise output files that mimic the individual pairwise comparisons?  The e-values will be different, but I believe the bitscore is what's used.  This would allow me to take better advantage of all the nodes in our HPC clusters...

Thanks!

**Comment by davidemms** [comment]
Hi

Yes, I think this would be fine (with the proviso below).

You're right about the bit scores and the evalues. I think you may lose some hits doing this because of the evalue cut-off (the hits would look less significant to BLAST because the database size is larger) but you could either:
- adjust the e-value cut-off used
- not worry about it, especially if the species are closely related (in which case the cut-off wouldn't matter so much)
*** use the -dbsize option to give approximately the same evalues as you'd get if you'd done them separately

I think the last option would be the best and would be easy to do (just specify a value which is about the average for all the species) but it might not matter too much anyway.

All the best
David
