### ISSUE TITLE
Errors in "Inferring gene and species trees"

### ISSUE THREAD

**Issue by jdarias93** [davidemms/OrthoFinder#80]
Hello, so OrthoFinder encountered these errors which prevented the estimation of a species tree. Do you think you could please take a look?

> Inferring gene and species trees
> --------------------------------
> 2017-06-11 09:31:18 : Done 0 of 23626
> 2017-06-11 09:33:09 : Done 1000 of 23626
> 2017-06-11 09:33:34 : Done 2000 of 23626
> 2017-06-11 09:33:55 : Done 3000 of 23626
> 2017-06-11 09:34:14 : Done 4000 of 23626
> 2017-06-11 09:34:31 : Done 5000 of 23626
> 2017-06-11 09:34:48 : Done 6000 of 23626
> 2017-06-11 09:35:05 : Done 7000 of 23626
> 2017-06-11 09:35:21 : Done 8000 of 23626
> 2017-06-11 09:35:36 : Done 9000 of 23626
> 2017-06-11 09:35:52 : Done 10000 of 23626
> 2017-06-11 09:36:08 : Done 11000 of 23626
> 2017-06-11 09:36:23 : Done 12000 of 23626
> 
>  . Error: Leaf (2) '0_55958' in tree not in distance matrix.
> 2017-06-11 09:36:38 : Done 13000 of 23626
> 
>  . Error: Leaf (2) '9_12453' in tree not in distance matrix.
> 2017-06-11 09:36:53 : Done 14000 of 23626
> 2017-06-11 09:37:09 : Done 15000 of 23626
> 2017-06-11 09:37:24 : Done 16000 of 23626
> 2017-06-11 09:37:39 : Done 17000 of 23626
> 2017-06-11 09:37:54 : Done 18000 of 23626
> 
>  . Error: Leaf (1) '4_76651' in tree not in distance matrix.
> 2017-06-11 09:38:10 : Done 19000 of 23626
> 2017-06-11 09:38:24 : Done 20000 of 23626
> 2017-06-11 09:38:39 : Done 21000 of 23626
> 2017-06-11 09:38:55 : Done 22000 of 23626
> 2017-06-11 09:39:10 : Done 23000 of 23626
> A duplicate accession was found using just first part: TRINITY-DN20713-c0-g1-i1|m.1
> Tried to use only the first part of the accession in order to list the sequences in each orthogroup
> more concisely but these were not unique. The full accession line will be used instead.

So I found the problem accession header and altered it so that it doesn't match anything else in any other fasta file, however, I'm not sure what I have to do about those 3 problem sequences it identified. 

Any help is appreciated! Thank you in advance.

**Comment by davidemms** [comment]
Hi 

The actual problem that caused OrthoFinder to stop is: "Error: Leaf (2) '0_55958' in tree not in distance matrix.". The duplicate accession part is fine, it just means that OrthoFinder had to use the full accession line from the fasta file to identify each sequence instead of just the first 'word' which is usually enough.

The "tree not in distance matrix" error message is from fastme, someone reported it to me about two weeks ago and was going to let the developers of fastme know. I will check with them to see if it has been investigated. I've also made a change to OrthoFinder so that it is robust to this ([issue 70](https://github.com/davidemms/OrthoFinder/issues/70)). I'll create a new release in the next couple of hours (version 1.1.7) which includes this fix. If you run using that it should be fine. You can use the option "-fg orthogroup_results_dir"  to restart the analysis from the orthogroups instead of needing to do that again.

For the duplicate accession, if you find the SequenceIDs.txt file and make the change in there then OrthoFinder will use those.

All the best 
David

**Comment by davidemms** [comment]
This issue has now been resolved: https://github.com/davidemms/OrthoFinder/commit/4b97622f4fae8627b9d3548e880430e6e570501e
