### ISSUE TITLE
Single copy genes

### ISSUE THREAD

**Issue by LI-zijian1** [davidemms/OrthoFinder#808]
hi，
I used OrthoFinder to analyze 25 species, but I only got one single-copy gene, is there any parameter to increase the number of single-copy genes? my command:orthofinder -f primary_transcripts -S diamond -t 24 -a 24 -M msa
thank you.

**Comment by davidemms** [comment]
Hi

That sounds very likely for 25 species, since the probability of having exactly one gene per species in every single species decreases geometrically as you add more species. The best thing to do would be to relax your criteria, and allow it to be single copy in x% of species. You can analyse `Orthogroups/Orthogroups.GeneCount.tsv` to identify orthogroups that meet your criteria.

Best wishes
David

**Comment by SWei2333** [comment]
Hi
I apologize for asking this question here. I have read other inquiries about the number of Single_Copy_Orthologue_Sequences. However, I would like to ask, I have only 387 Single_Copy_Orthologue_Sequences, and my species are from 19 different groups within the same suborder. If I want to run CAFE, is this number acceptable, or do I need to relax my criteria to increase the count?
