### ISSUE TITLE
50% of Orthogroups are unassigned genes

### ISSUE THREAD

**Issue by jgrif61** [davidemms/OrthoFinder#81]
Hello, 
I have transcriptomes from two populations of a coral species.  However, 50% of my orthogroups are unassigned genes, which seems a little high for the same species.  For all the unassigned genes, I ran my own BLAST search to see what the top hits were and many of them blasted genes from the other population with high bit scores and long read alignments. I am unsure as to why they are not getting grouped into other Orthogroups. 

Any insight would be appreciated, thank you!
Joanna

**Comment by davidemms** [comment]
Hi Joanna

This sounds quite similar to this issue: https://github.com/davidemms/OrthoFinder/issues/84

The best advice is:
- you'll get a larger number of genes assigned to orthogroups if you use more species (perhaps 5+)
- if you are primarily interested in two species it is still a good approach to run OrthoFinder with a larger number of species and then use the orthologues that it infers from gene trees to do any comparisons you want to do.
- with transcriptomes you often have an inflated number of sequences because of fragments etc. and so these are harder to assign to orthogroups compared to a set of gene models from a fully sequenced genome.

Hope this helps.
David
