### ISSUE TITLE
Cannot run diamond v 2.5.5 

### ISSUE THREAD

**Issue by isokoten** [davidemms/OrthoFinder#826]
Hey there, 
I was trying to run orthofinder on a bunch of samples, but it keeps saying that the diamond cannot be run. 
I tried to resolve the issue by downgrading my diamond, but it seems to be incompatible with the newer versions of python. Even if I use the blast, it says it cannot run diamond
orthofinder -f samples/ -s blast

error:

OrthoFinder version 2.5.5 Copyright (C) 2014 David Emms

2023-05-24 19:02:47 : Starting OrthoFinder 2.5.5
10 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
diamond produced the following output:

Error: Option is not permitted for this workflow: ignore-warnings

Error opening file /Users/kudaybergenb/Development/samples/OrthoFinder/Results_May24/WorkingDirectory/dependencies/diamondDBSpecies0: No such file or directory

ERROR: Cannot run diamond

Could you help me with that?

**Comment by nhartwic** [comment]
See issue #825 

No comment yet from devs.

**Comment by isokoten** [comment]
I resolved the problem by downgrading my diamond to the version 2.0.15, seems to be working well!

**Comment by davidemms** [comment]
Hi

Thanks for reporting this. Currently there are issues with diamond>= 2.1 (up to the current version of 2.1.6). I'll get a permanent fix out as soon as possible, until then the best options are:

# Workarounds

## 1. Use diamond 2.0.15 (e.g. if using conda `conda install "diamond<2.1"`)

## 2. Alternatively, edit orthofinder `config.json` file:

Find where orthofinder is installed:
`which orthofinder`
> /home/david/mambaforge/envs/of255/bin/orthofinder

Edit the corresponding  `config.json` file, in this case `/home/david/mambaforge/envs/of255/bin/scripts_of/config.json` and remove "-ignore-warnings" everywhere it occurs.

# Background
The error occurs because some versions of diamond have a check for files containing only DNA characters but it only looks at the initial sequences, which means it fails for e.g. the Ensembl human proteome: https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/pep/Homo_sapiens.GRCh38.pep.all.fa.gz

To get round this there is an option "-ignore-warnings" to inactivate this. Unfortunately, if used with a version of diamond that doesn't support this option it will also fail. This is currently true for diamond>=2.1 and also some of the earlier diamond versions. I think it's a mistake in >=2.1 so I've reported it and hopefully it can be fixed: https://github.com/bbuchfink/diamond/issues/707

**Comment by davidemms** [comment]
This issue has now been resolved:
- There is now a new release of diamond (v2.1.7) that fixes the issue. 
- OrthoFinder's conda recipe has been updated to exclude versions 2.1.0-2.1.6 so should now only install working versions.
- The version of diamond that comes with the OrthoFinder release package on github was pinned to an earlier version so should always have worked.
- Same is true of the OrthoFinder docker image.
