### ISSUE TITLE
Are there any Bootstrap values on the node of gene tree in Resolved Gene Trees Directory?

### ISSUE THREAD

**Issue by xbx-xbx-1208** [davidemms/OrthoFinder#829]
I wish to show the phylogenetic relationship among some genes in HOGs using the corresponding gene tree in Resolved Gene Trees Directory, but I noted there are not bootstrap value on their nodes. Will you suggest me to do like this? Or what the meanings in the trees from Resolved Gene Trees Directory?

**Comment by davidemms** [comment]
Hi

The trees in the `Gene_Trees` have nodes with support values so they may be of use to you. The idea of support values doesn't apply to the Resolved Gene Trees since some of the bipartitions have been specifically rearranged away from the topology given by the tree inference so as to better support the orthology inference. 

Best wishes 
David
