### ISSUE TITLE
Too few paralogs when Whole Genome Duplication in Species Tree

### ISSUE THREAD

**Issue by jconover11** [davidemms/OrthoFinder#84]
I ran this analysis using Gossypium raimondii and Theobroma cocao. G. raimondii has been shown to have experienced at least a genome duplication (possibly a 5-6X multiplication) event since it divergenced from T. cocao, but Orthofinder only clustered 51% of T. cocao genes, and 55.5% of G. raimondii genes. Also, of the 16,467 orthogroups that were in the result file, 13,688 of these are singleton groups (containing one ortholog from each species). 

Obviously, since there is a whole genome duplication event separating these two species, I expect there to be several groups which would contain a 1:2 (or, potentially a 1:5 or 1:6) ratio which reflects this. 

I think this may be an error in the reciprocal-blast filter step, which excludes all but the slowest evolving gene in each species. 

Is there a way to incorporate this into the program to accommodate for  known ploidy-level differences? Or could you point me to the part of the source code that does this RBH filtering, and I can skip it?

**Comment by davidemms** [comment]
Hi

I think the problem could be with the reciprocal-blast step. When designing how this step would best work I anticipated people using more than 2 species, typically 3 or 4 as a minimum (since orthogroups given extra information from orthologues once we have more than 2 species). With only two species it is hard to distinguish (using blast scores) 1) the more divergent gene from a duplication event after the species diverged from 2) A duplicate gene that diverged before the speciation event.

I think the best thing to do would be to include an extra species that is a closely-related outgroup to these two. This will allow the algorithm to identify the genes that diverged in the whole genome duplication and place all the correct genes in the orthogroups. The second part of the OrthoFinder algorithm, would then be able to use gene trees successfully to identify orthologues with the ratios you were expecting. Note that the duplicate genes from the whole genome duplication would be orthologues of the corresponding T. cocao genes since they diverged at a speciation event. 

You can include an extra species by combining the '-f' and '-b' options, as described in the manual.

I'd be really interested to know how this works out, if you could briefly post here what the results are that'd be great!

Thanks
David

**Comment by jconover11** [comment]
Great, thanks for the advice! I'll try it and let you know what I find.

**Comment by jconover11** [comment]
Hi David, 

I've ran OrthoFinder with a species more distant than T. cacao, and got some interesting results, although I'm not sure they solved my problems. Here are the summary statistics for the first run I asked about: 
[Cotton_Choc_Statistics_PerSpecies.txt](https://github.com/davidemms/OrthoFinder/files/1105888/Cotton_Choc_Statistics_PerSpecies.txt)


And the new statistics summary from adding Citrus clementina : 
[Cotton_Choc_Cclem_Statistics_PerSpecies.txt](https://github.com/davidemms/OrthoFinder/files/1105885/Cotton_Choc_Cclem_Statistics_PerSpecies.txt)

The total number of genes included in the clustering was increased, but still not at the level I thought it would. I'm trying to add another species that has also undergone the WGD, to see if that teases out the groups better. I'll report back when that is finished, but I would appreciate any feedback you have on this.

**Comment by davidemms** [comment]
Hi 

Apologies for the delay but I've been looking at some related work recently and I thought I should update you with the results I get. I've got an analysis of about 40 plant genomes from Phytozome and here are the summary statistics for your three species side-by-side with the numbers I got for those species (as part of the larger analysis):
[Cotton_Choc_Cclem_Statistics_PerSpecies_comparison.txt](https://github.com/davidemms/OrthoFinder/files/1437540/Cotton_Choc_Cclem_Statistics_PerSpecies_comparison.txt)

As you can see, in this analysis the percentage of genes in orthogroups was 95.9%, 86.8% and 94.6%. There seem to be two differences here which may both contribute or it might just be one of them. 

- I used the protein primary transcripts files so I had only one representative transcript per gene. If you look at the spreadsheet then what actually happened was that I got a very similar number of genes in orthogroups for C. clementina and T. cacao, but these were a far higher percentage of the input genes. That said it looks like we used the same proteome for G. raimondii but there were over 7000 more genes in orthogroups with this larger analysis, leading on to the second difference... 
- The analysis included species going all the way back to the green algae so the definition of orthogroup becomes wider. But it also seems to be the case that, higher number of species often gives better orthogroup assignment. Now that you can use [DIAMOND](http://www.nature.com/nmeth/journal/v12/n1/abs/nmeth.3176.html) with OrthoFinder, using more species is really quick to do!

From looking at results from a number of OrthoFinder analyses it does seem that a denser sampling of species gives a higher percentage for orthogroup assignment. I think using one transcript per gene is generally the best approach too, it also makes the analysis a lot quicker. 

All the best
David
