### ISSUE TITLE
Removing species still results in Initial Processing?

### ISSUE THREAD

**Issue by kgun12** [davidemms/OrthoFinder#86]
I'm running an analysis with a few hundred eukaryote proteomes, but I maxed out the wall-clock time (48 hrs) on my HPC cluster hi-memory nodes during processing of the BLAST results.  I pre-computed all BLAST results across the worker nodes.

I commented out a large portion of species from SpeciesIDs.txt and re-ran with -b, but it is still producing .pic files and doing initial processing for all comparisons (including those I commented out), so it appears that removing species only applies to the steps further downstream?  I can remove the species from SpeciesIDs.txt entirely and prune the BLAST results accordingly, but there will be gaps in the numbering scheme.  Is that OK?
 
-- or I guess my real questions is, how do I shrink my analysis without re-running the all-vs-all blast?

**Comment by davidemms** [comment]
Hi

I think that the numbering of the .pic files (and some of the output to the screen) just refers to the ordering of the species being processed. I.e. if you had N species originally, and then removed some so that you only had M left then the pic files will go from 0 up to M-1 instead of going from 0 up to N-1 with gaps for the species removed. 

So I think it should all be fine, it is only doing the work for the species you've included in your cut-down version. There's no need to prune the files.

Let me know if this all works out fine

All the best.
David

**Comment by kgun12** [comment]
Ok, thanks David.  I've resubmitted the job using the SpeciesIDs.txt with proteomes commented out.
