### ISSUE TITLE
Inferring gene trees with for orthogroups with less than 4 sequences

### ISSUE THREAD

**Issue by niconps14** [davidemms/OrthoFinder#897]
Is there any way for OrthoFinder to infer gene trees for the orthogroups with less than 4 sequences?

**Comment by Jonathan-Holmes-Bioinformatics** [comment]
Hi niconps14, 

Orthofinder can only generate trees from orthogroups containing 4 or more genes. Due to limits introduced by the tree building software used to construct the gene trees (such as RAXML have a minimum input of 4 genes). 

Orthofinder will generate the sequences fills for orthogroups of sequence number < 4, so you can generate the trees yourself, but these gene trees may not be meaningful with such a low number of leaves. 

Thanks,
Jonathan
