### ISSUE TITLE
orthofinder failing while making groups - maybe memory issue?

### ISSUE THREAD

**Issue by aGitHasNoName** [davidemms/OrthoFinder#95]
Hi David,
I'm running orthofinder on 65 proteomes. I'm running from -b to -os but it fails after about a week of making the .pic files. It only gives an EOFError. I'm not sure if it's a memory issue or a message passing issue or what. Any help you can give would be appreciated!

job submission I'm using on our server:
#PBS -l nodes=1:ppn=12
#PBS -j oe
#PBS -q default
#PBS -o orthofinder2.out

cd $TMPDIR

/opt/Software/OrthoFinder/orthofinder/orthofinder.py -os -b /home/colby/65genome/orthofinder_final -t 12

cp -r . /home/colby/

.out file attached.
[orthofinder2.out.txt](https://github.com/davidemms/OrthoFinder/files/1131845/orthofinder2.out.txt)

**Comment by davidemms** [comment]
Hi

Is it possible that you ran out of disk space? OrthoFinder caches data in python 'pickle' files to save it from having to hold all the data in RAM at one time. It looks like when it tried to read one of these cached files the file was incomplete. Or is there anything else that could have happened to the file?

All the best
David

**Comment by mossmatters** [comment]
Hi David-- I am the admin on the cluster that we're having troubles with. I think there may be an issue with our computer's storage and the Orthofinder working directory.

Running a job means computation is occurring on the compute node, but I/O is happening on the head node, over ethernet. Our computer seems to have problems when lots of very tiny files (like the Pickles) are created too fast. Orthofinder is probably trying to read a Pickle that has not been copied over to the head node yet. 

Normally the solution would be to run the whole job using the `/scratch/` space on the compute node as the working directory, but we can't do that because of the size of the BLAST directory. The compute nodes have only 128 GB of storage space, so they cannot accommodate all of the BLAST files in `/scratch/`

The solution, I think, is to figure out a way to run Orthofinder post-BLAST using the `$TMPDIR` in the compute node `/scratch/` space without having to copy the BLAST results over to the compute node. The way Orthofinder handles all the temporary files and its own working directory are a bit of a mystery to me, so I am not sure what the commands for this would be. 

Any tips would be greatly appreciated!

**Comment by davidemms** [comment]
Hi

Yes, I see the problem there. I'm just implementing an option that allows the user to specify a directory that the pickle files will be written to. There are some other files that are written and then used by OrthoFinder (e.g. multiple sequence alignments are inferred and then used as input to a tree inference program in some use cases) but hopefully there will be enough of a delay for these cases since they involve external programs being launched which will take time, the pickle files are written and read within the program itself. I'll submit the change in the next hour or so.

The option to use will be "--pickledir /scratch".

All the best
David
